unpackaged/main/default/objects/Account_Service_Product__c/Account_Service_Product__c.object-meta.xml
<CustomObject>
    <label>Account Service Product</label>
    <nameField>
        <displayFormat>a-{00000000}</displayFormat>
        <label>Account Service Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Service Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/T1_Control_Settings__c/T1_Control_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>TechnologyOne settings</description>
    <label>T1 Control Settings</label>
</CustomObject>

unpackaged/main/default/objects/T1_Control_Settings__c/fields/Bypass_Workflow__c.field-meta.xml
<CustomField>
    <fullName>Bypass_Workflow__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bypass Workflow</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/T1_Control_Settings__c/fields/Closed_Date_for_Archiving_Email__c.field-meta.xml
<CustomField>
    <fullName>Closed_Date_for_Archiving_Email__c</fullName>
    <description>This date will be used to select closed cases for email archive purposes.</description>
    <inlineHelpText>This date will be used to select closed cases for email archive purposes.</inlineHelpText>
    <label>Closed Date for Archiving Email</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/T1_Control_Settings__c/fields/Customer_Community_URL__c.field-meta.xml
<CustomField>
    <fullName>Customer_Community_URL__c</fullName>
    <label>Customer Community URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/T1_Control_Settings__c/fields/Employee_Community_URL__c.field-meta.xml
<CustomField>
    <fullName>Employee_Community_URL__c</fullName>
    <label>Employee Community URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/T1_Control_Settings__c/fields/Internal_URL__c.field-meta.xml
<CustomField>
    <fullName>Internal_URL__c</fullName>
    <label>Internal URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/T1_Process_Log__c/T1_Process_Log__c.object-meta.xml
<CustomObject>
    <label>T1 Process Log</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>T1 Process Log Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>T1 Process Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/T1_Process_Log__c/fields/Process_Message__c.field-meta.xml
<CustomField>
    <fullName>Process_Message__c</fullName>
    <label>Process Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/batchDeleteAccServProd.cls
global class batchDeleteAccServProd implements 
   Database.Batchable<sObject>{

   /*
    execute this class via Developer Console with the following code
        batchDeleteAccServProd c = new batchDeleteAccServProd();
        Database.executeBatch(c);
   */
       
   global Database.QueryLocator start(Database.BatchableContext BC){
       // query hardcoded for ease
      String query = 'SELECT id FROM Account_Service_Product__c ';
       
      if(Test.isRunningTest())
          query = 'SELECT id FROM Account_Service_Product__c limit 100';
       
      return Database.getQueryLocator(query);
   }
   
   global void execute(
                Database.BatchableContext BC, 
                List<sObject> scope){

        // ensure triggers, workflow and validation rules are deactivated          
        T1_Control_Settings__c s = T1_Control_Settings__c.getInstance( UserInfo.GetUserID() ); //or Profile
        s.Bypass_Triggers__c = true;
        s.Bypass_Validation_Rules__c = true;
        s.Bypass_Workflow__c = true;
        s.Customer_Community_URL__c = '';
        s.Employee_Community_URL__c = '';
        s.Internal_URL__c = '';
        s.Closed_Date_for_Archiving_Email__c = null;
     	upsert s;
                    
        // ensure triggers, workflow and validation rules are deactivated 
     
        if(s.Bypass_Triggers__c == false || s.Bypass_Validation_Rules__c == false || s.Bypass_Workflow__c == false) {
            T1_Process_Log__c procLog = new T1_Process_Log__c(Process_Name__c = 'batchDeleteAccServProd',
                                      Process_Message__c = 'Triggers etc have not been bypassed. No processing has occurred.');
            insert procLog;
            system.debug('Triggers etc have not been bypassed. No processing has occurred. ');           
            return; 
        }

        Try {
            List<Account_Service_Product__c> l_asp = scope;
            
            if (!l_asp.isEmpty()) {
                T1_Process_Log__c procLog = new T1_Process_Log__c(Process_Name__c = 'batchDeleteAccServProd',
                                          Process_Message__c = 'Account Service Products deleted ' + l_asp.size());
                insert procLog;
                system.debug('Account Service Products deleted ' + l_asp.size());
                delete l_asp;
                DataBase.emptyRecycleBin(l_asp);
            }
        } catch(Exception e) {
            T1_Process_Log__c procLog = new T1_Process_Log__c(Process_Name__c = 'batchDeleteAccServProd',
                Process_Message__c =  e.getMessage().substring(0,254));
                insert procLog;
        }    
   }

   global void finish(Database.BatchableContext BC){
       AsyncApexJob a = 
           [SELECT Id, Status, NumberOfErrors, JobItemsProcessed,
            TotalJobItems, CreatedBy.Email
            FROM AsyncApexJob WHERE Id =
            :BC.getJobId()];
       
       // Now reset the bypass values        
       T1_Control_Settings__c s = T1_Control_Settings__c.getInstance( UserInfo.GetUserID() ); //or Profile
       s.Bypass_Triggers__c = false;
       s.Bypass_Validation_Rules__c = false;
       s.Bypass_Workflow__c = false;
       s.Customer_Community_URL__c = '';
       s.Employee_Community_URL__c = '';
       s.Internal_URL__c = '';
       s.Closed_Date_for_Archiving_Email__c = null;
       upsert s;
                                
       // Send an email to the Apex job's submitter 
       //   notifying of job completion. 
       //   
       Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
       String[] toAddresses = new String[] {a.CreatedBy.Email};
       mail.setToAddresses(toAddresses);
       mail.setSubject('Batch batchDeleteAccServProd Status: ' + a.Status);
       mail.setPlainTextBody
       ('The batch Apex job processed ' + a.TotalJobItems +
       ' batches with '+ a.NumberOfErrors + ' failures.');
       Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
   }

       
       
}