unpackaged/main/default/objects/Survey_Response_Opportunity__c/Survey_Response_Opportunity__c.object-meta.xml
<CustomObject>
    <description>Used to link GetFeedback survey results to Salesforce Service Only / Consulting Request Opportunities</description>
    <label>Survey Response Opportunity</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Survey Response Opportunities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Survey_Response_Opportunity__c/fields/Comment__c.field-meta.xml
<CustomField>
    <fullName>Comment__c</fullName>
    <label>Comment</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Survey_Response_Opportunity__c/fields/Experience_Rating__c.field-meta.xml
<CustomField>
    <fullName>Experience_Rating__c</fullName>
    <label>Experience Rating</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/classes/TestConsultingSurveyResponse.cls
@isTest
public class TestConsultingSurveyResponse {

   public static void CreateSurveyResponseOpportunity() {
        // Create test record
        Survey_Response_Opportunity__c s = new Survey_Response_Opportunity__c (Name='T1 Consulting Survey');
        insert s; 
        s.Experience_Rating__c = 5;
        s.Comment__c = 'Excellent Service';
        s.Improvement__c = 'Communications';
       update s;
       
           Survey_Response_Opportunity__c updatedS = [SELECT Name,Experience_Rating__c,Comment__c FROM
            Survey_Response_Opportunity__c WHERE Id = : s.Id];
            System.assertEquals('T1 Consulting Survey', updatedS.Name);      
            System.assertEquals(5, updatedS.Experience_Rating__c);
        	System.assertEquals('Excellent Service', updatedS.Comment__c);
   }
    
}