unpackaged/main/default/objects/CPEC_Request__c/CPEC_Request__c.object-meta.xml
<CustomObject>
    <description>Submission Requests</description>
    <label>CRC Request</label>
    <nameField>
        <displayFormat>CRC-{000000}</displayFormat>
        <label>Request Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CRC Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/CPEC_Request__c/fields/Action__c.field-meta.xml
<CustomField>
    <fullName>Action__c</fullName>
    <label>Action</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

unpackaged/main/default/objects/CPEC_Request__c/fields/Approval_Level__c.field-meta.xml
<CustomField>
    <fullName>Approval_Level__c</fullName>
    <label>Approval Level</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CRC_Approval_Level</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/CPEC_Request__c/fields/Request_Type__c.field-meta.xml
<CustomField>
    <fullName>Request_Type__c</fullName>
    <label>Request Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CRC_Request_Type</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/CRC_Request_Action__c/CRC_Request_Action__c.object-meta.xml
<CustomObject>
    <label>CRC Request Action</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Action Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CRC Request Actions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/CRC_Request_Action__c/fields/Action__c.field-meta.xml
<CustomField>
    <fullName>Action__c</fullName>
    <label>Action</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/CRC_Request_Action__c/fields/Assigned_To__c.field-meta.xml
<CustomField>
    <fullName>Assigned_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned To</label>
    <referenceTo>User</referenceTo>
    <relationshipName>CPEC_Request_Actions</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/CRC_Request_Action__c/fields/CRC_Request__c.field-meta.xml
<CustomField>
    <fullName>CRC_Request__c</fullName>
    <label>Request</label>
    <referenceTo>CPEC_Request__c</referenceTo>
    <relationshipLabel>CRC Request Actions</relationshipLabel>
    <relationshipName>CRC_Request_Actions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/CRC_Request_Action__c/fields/Instructions__c.field-meta.xml
<CustomField>
    <fullName>Instructions__c</fullName>
    <label>Instructions</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

unpackaged/main/default/objects/CRC_Request_Action_Settings__c/CRC_Request_Action_Settings__c.object-meta.xml
<CustomObject>
    <label>CRC Request Action Settings</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>CRC Request Action Settings Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CRC Request Action Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/CRC_Request_Action_Settings__c/fields/Action_Description__c.field-meta.xml
<CustomField>
    <fullName>Action_Description__c</fullName>
    <label>Action Description</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/CRC_Request_Action_Settings__c/fields/Applies_to_Request_Type__c.field-meta.xml
<CustomField>
    <fullName>Applies_to_Request_Type__c</fullName>
    <label>Applies to Request Type</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CRC_Request_Type</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/CRC_Request_Action_Settings__c/fields/Assigned_To__c.field-meta.xml
<CustomField>
    <fullName>Assigned_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned To</label>
    <referenceTo>User</referenceTo>
    <relationshipName>CRC_Request_Action_Settings</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/CRC_Request_Action_Settings__c/fields/Due_in_Days__c.field-meta.xml
<CustomField>
    <fullName>Due_in_Days__c</fullName>
    <label>Due in Days</label>
    <precision>9</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/CRC_Request_Action_Settings__c/fields/Instructions__c.field-meta.xml
<CustomField>
    <fullName>Instructions__c</fullName>
    <label>Instructions</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

unpackaged/main/default/objects/CRC_Request_Approval__c/CRC_Request_Approval__c.object-meta.xml
<CustomObject>
    <label>CRC Request Approval</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Request Approval Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CRC Request Approvals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/CRC_Request_Approval__c/fields/CRC_Request__c.field-meta.xml
<CustomField>
    <fullName>CRC_Request__c</fullName>
    <label>Request</label>
    <referenceTo>CPEC_Request__c</referenceTo>
    <relationshipLabel>CRC Request Approvals</relationshipLabel>
    <relationshipName>CPEC_Request_Endorsements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/CRC_Request_Approval__c/fields/Endorser__c.field-meta.xml
<CustomField>
    <fullName>Endorser__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Endorser</label>
    <referenceTo>User</referenceTo>
    <relationshipName>CPEC_Request_Endorsements</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/CRC_Request_Approval_Settings__c/CRC_Request_Approval_Settings__c.object-meta.xml
<CustomObject>
    <label>CRC Request Approval Settings</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>CRC Request Approval Settings Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CRC Request Approval Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/CRC_Request_Approval_Settings__c/fields/Approval_Level__c.field-meta.xml
<CustomField>
    <fullName>Approval_Level__c</fullName>
    <label>Approval Level</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CRC_Approval_Level</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/CRC_Request_Approval_Settings__c/fields/Endorser__c.field-meta.xml
<CustomField>
    <fullName>Endorser__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Endorser</label>
    <referenceTo>User</referenceTo>
    <relationshipName>CRC_Request_Approval_Settings</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/globalValueSets/CRC_Approval_Level.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>CRC</fullName>
    </customValue>
    <customValue>
        <fullName>CEO</fullName>
    </customValue>
    <customValue>
        <fullName>COO</fullName>
    </customValue>
    <customValue>
        <fullName>CFO</fullName>
    </customValue>
    <customValue>
        <fullName>GFC</fullName>
    </customValue>
    <customValue>
        <fullName>ER Commitee</fullName>
    </customValue>
    <customValue>
        <fullName>EVP-CS</fullName>
    </customValue>
    <customValue>
        <fullName>EVP-Sales</fullName>
    </customValue>
    <customValue>
        <fullName>GD-CR&amp;R (Sales)</fullName>
    </customValue>
    <customValue>
        <fullName>ER C&#39;tee</fullName>
    </customValue>
    <masterLabel>CRC Approval Level</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/CRC_Request_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AMS Program</fullName>
    </customValue>
    <customValue>
        <fullName>ASM Credit / Payment Holiday</fullName>
    </customValue>
    <customValue>
        <fullName>Free of Charge Module / Licence</fullName>
    </customValue>
    <customValue>
        <fullName>Module Swap</fullName>
    </customValue>
    <customValue>
        <fullName>Non-Billable Consulting</fullName>
    </customValue>
    <customValue>
        <fullName>Pandemic Relief</fullName>
    </customValue>
    <customValue>
        <fullName>Temporary Licence Extension</fullName>
    </customValue>
    <customValue>
        <fullName>Waiver of Annual increase</fullName>
    </customValue>
    <customValue>
        <fullName>Waiver of Notification Period</fullName>
    </customValue>
    <customValue>
        <fullName>Go-Live Issues</fullName>
        <isActive>false</isActive>
        <label>Go-Live Issues</label>
    </customValue>
    <customValue>
        <fullName>Product Issues</fullName>
        <isActive>false</isActive>
        <label>Product Issues</label>
    </customValue>
    <customValue>
        <fullName>SaaS Flip</fullName>
        <isActive>false</isActive>
        <label>SaaS Flip</label>
    </customValue>
    <customValue>
        <fullName>Reduction of Licence / ASM  / CSF</fullName>
        <isActive>false</isActive>
        <label>Reduction of Licence / ASM  / CSF</label>
    </customValue>
    <customValue>
        <fullName>Non-standard contract terms</fullName>
        <isActive>false</isActive>
        <label>Non-standard contract terms</label>
    </customValue>
    <masterLabel>CRC Request Type</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/CPECRequestTriggerHandler.cls
/**
     CPECRequestTrigger Handler
 */
public class CPECRequestTriggerHandler {

   static public void onAfterInsert(CPEC_Request__c[] newRecs) {
        createDefaults(newRecs);
    }

    static public void onBeforeInsert(CPEC_Request__c[] newRecs) {

        /* for(CPEC_Request__c newReqs : newRecs){
            if (String.IsBlank(newReqs.Requester__c)){
                newReqs.Requester__c = UserInfo.getUserId();
            }
        } */
    }

    static public void onBeforeUpdate(CPEC_Request__c[] updatedRecs, Map<ID, CPEC_Request__c> oldMap) {
    }
    
    static public void onAfterUpdate(CPEC_Request__c[] updatedRecs, Map<ID, CPEC_Request__c> oldMap) {
    }

    static public void createDefaults(CPEC_Request__c[] newRecs) {
    
        list <CRC_Request_Action__c> l_ReqActions = new list<CRC_Request_Action__c>(); 
        list <CRC_Request_Approval__c> l_ReqApps = new list<CRC_Request_Approval__c>();
        Map<ID,CRC_Request_Action_Settings__c> mapActions = new Map<ID,CRC_Request_Action_Settings__c>(
            [ SELECT Action_Description__c, Applies_to_Request_Type__c, Assigned_To__c
                                                                , Due_in_Days__c, Instructions__c
                                                                 FROM CRC_Request_Action_Settings__c]); 
        Map<ID,CRC_Request_Approval_Settings__c> mapApps = new Map<ID,CRC_Request_Approval_Settings__c>(
            [ SELECT Approval_Level__c, Endorser__c FROM CRC_Request_Approval_Settings__c]); 
 
        for(CPEC_Request__c newReqs : newRecs){
            // Create the default Actions
            for(CRC_Request_Action_Settings__c rASs : mapActions.values()){
                if(rASs.Applies_to_Request_Type__c.contains(newReqs.Request_Type__c)){
                    CRC_Request_Action__c reqAct = new CRC_Request_Action__c();
                    reqAct.Assigned_To__c = rASs.Assigned_To__c;
                    reqAct.Action__c = rASs.Action_Description__c;
                    reqAct.Instructions__c = rASs.Instructions__c;
                    reqAct.CRC_Request__c = newReqs.Id;
                    if (rASs.Due_in_Days__c != null && rASs.Due_in_Days__c > 0){
                        reqAct.Due_Date__c = system.today().addDays(rASs.Due_in_Days__c.intValue());
                    }
                    l_ReqActions.add(reqAct);
                }
 

            }
            if(newReqs.Approval_Level__c.contains('Level 6')){
                CRC_Request_Action__c reqAct = new CRC_Request_Action__c();
                //reqAct.Assigned_To__c = newReqs.Requester__c;
                reqAct.Action__c = 'Gain approval from your RM/RCD';
                reqAct.CRC_Request__c = newReqs.Id;
                l_ReqActions.add(reqAct);
            }

            // Create the default Approvals
            for(CRC_Request_Approval_Settings__c rApps : mapApps.values()){
                if(rApps.Approval_Level__c.contains(newReqs.Approval_Level__c)){
                    CRC_Request_Approval__c reqApp = new CRC_Request_Approval__c();
                    reqApp.Endorser__c = rApps.Endorser__c;
                    reqApp.CRC_Request__c = newReqs.Id;
                    l_ReqApps.add(reqApp);
                }
           }
        } 
  
        if (!l_ReqActions.isEmpty()){
            insert l_ReqActions;
        }   
        if (!l_ReqApps.isEmpty()){
            insert l_ReqApps;
        }
    }
    

}