unpackaged/main/default/objects/Notification_Log__c/Notification_Log__c.object-meta.xml
<CustomObject>
    <label>Notification Log</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{DD}{0}</displayFormat>
        <label>Log #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notification Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Notification_Log__c/fields/Http_Error__c.field-meta.xml
<CustomField>
    <fullName>Http_Error__c</fullName>
    <label>Http Error</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Notification_Log__c/fields/Http_Status__c.field-meta.xml
<CustomField>
    <fullName>Http_Status__c</fullName>
    <label>Http Status</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Notification_Log__c/fields/Request_Payload__c.field-meta.xml
<CustomField>
    <fullName>Request_Payload__c</fullName>
    <label>Request Payload</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Notification_Log__c/fields/Response_Payload__c.field-meta.xml
<CustomField>
    <fullName>Response_Payload__c</fullName>
    <label>Response Payload</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Notification_Log__c/fields/TNE_ID__c.field-meta.xml
<CustomField>
    <fullName>TNE_ID__c</fullName>
    <description>TNE-generated GUID that uniquely identifies the notification so that TNE can update the notification later once it has been processed (TOCB-1615)</description>
    <externalId>true</externalId>
    <label>TNE ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/T1_Control_Settings__c/T1_Control_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>TechnologyOne settings</description>
    <label>T1 Control Settings</label>
</CustomObject>

unpackaged/main/default/objects/T1_Control_Settings__c/fields/Notification_URL__c.field-meta.xml
<CustomField>
    <fullName>Notification_URL__c</fullName>
    <label>Notification URL</label>
    <type>Url</type>
</CustomField>

unpackaged/main/default/objects/T1_Control_Settings__c/fields/T1_OAuth_Client_Id__c.field-meta.xml
<CustomField>
    <fullName>T1_OAuth_Client_Id__c</fullName>
    <label>T1 OAuth Client Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/T1_Control_Settings__c/fields/T1_OAuth_Client_Secret__c.field-meta.xml
<CustomField>
    <fullName>T1_OAuth_Client_Secret__c</fullName>
    <label>T1 OAuth Client Secret</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/T1_Control_Settings__c/fields/T1_Timeout_milliseconds__c.field-meta.xml
<CustomField>
    <fullName>T1_Timeout_milliseconds__c</fullName>
    <label>T1 Timeout milliseconds</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/T1_OAuth_Token__c/T1_OAuth_Token__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>T1 OAuth Token</label>
</CustomObject>

unpackaged/main/default/objects/T1_OAuth_Token__c/fields/Expiry__c.field-meta.xml
<CustomField>
    <fullName>Expiry__c</fullName>
    <label>Expiry</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/classes/T1NotificationServiceImpl.cls
/*******************************************************************************************************
* Class Name      	: T1NotificationServiceImpl
* Description		: Implementation for T1 notifications 
* Author          	: Simplus - Abeer Qureshi
* Created On      	: 
* Modification Log	:
* -----------------------------------------------------------------------------------------------------
* Developer				Date			Modification ID		Description
* -----------------------------------------------------------------------------------------------------
* Abeer Qureshi         		        1000				Initial version
******************************************************************************************************/
public class T1NotificationServiceImpl implements INotificationService {

    public class NotImplementedException extends Exception{}

    public T1NotificationServiceImpl() {

    }

    public static void notifyF(String req)
    {
        throw new NotImplementedException();
    }

/*
    *@description Makes api call to send notification to T1
    *@author Abeer Qureshi - Simplus 
    *@param NotificationRequest payload
    *@return 
*/ 
    public NotificationResponse notify(NotificationRequest req){
        T1_Control_Settings__c CS = T1_Control_Settings__c.getOrgDefaults();
        NotificationResponse ret = new NotificationResponse();

        HttpRequest httpReq = new HttpRequest();

        httpReq.setEndpoint(cs.Notification_URL__c);
        httpReq.setHeader('Content-Type','application/json');
        httpReq.setMethod('POST');
        if(CS.T1_Timeout_milliseconds__c != null)
        	httpReq.setTimeout(integer.valueOf(CS.T1_Timeout_milliseconds__c));
        httpReq.setBody(
            JSON.serialize(req)
        );


        T1_OAuth_Token__c settings = T1_OAuth_Token__c.getOrgDefaults();

        OAuthResponse oauthres;

        if(settings.Expiry__c > System.now()){
            httpReq.setHeader('Authorization', 'Bearer ' + settings.access_token__c);
        } else {
            oauthres = getAccessToken();
        }
        
        HttpResponse res;
        
        try {
        	res = new Http().send(httpReq);
        } catch(System.CalloutException e) {
            System.debug(LoggingLevel.Info, 'CalloutException');
            System.debug(LoggingLevel.Info, e.getMessage());
            ret.msg = e.getMessage();
            logRequest(req, ret, null);
            return ret;
        }

        if( res.getStatusCode() == 200 )
        {
            DOM.Document doc = res.getBodyDocument();
            
            for(Dom.XmlNode fluxChildNode: doc.getRootElement().getChildElements()) 
            {
                
                if(fluxChildNode.getName() == 'res_result') {
                    ret.result = fluxChildNode.getText().trim();
                }
                if(fluxChildNode.getName() == 'res_msg') {
                    ret.msg = fluxChildNode.getText().trim();
                }
                if(fluxChildNode.getName() == 'tne_id') {
                    ret.tneid = fluxChildNode.getText().trim();
                }
            }
            
        } else {
            ret = new NotificationResponse();
        }
        
        System.debug(LoggingLevel.Info, 'Response');
        System.debug(LoggingLevel.Info, ret);
        
        if(oauthres != null){
            OAuthService.setAccessToken(oauthres);
        }
        
        logRequest(req, ret, res);
        
        return ret;
    }

/*
    *@description Makes api call to get access token from T1
    *@author Abeer Qureshi - Simplus 
    *@param 
    *@return 
*/ 
    private OAuthResponse getAccessToken()
    {
        T1_Control_Settings__c CS = T1_Control_Settings__c.getOrgDefaults();

        OAuthRequest req = new OAuthRequest();
        req.grant_type = 'client_credentials';
        req.client_id = cs.T1_OAuth_Client_Id__c;
        req.client_secret = cs.T1_OAuth_Client_Secret__c;        

        return OAuthService.newInstance().getAccessToken(req);
    }

/*
    *@description logs request in notification log
    *@author Abeer Qureshi - Simplus 
    *@param NotificationRequest to log request paylaod 
    *@param NotificationResponse to log response payload
    *@param HttpResponse to log http response code and error message
    *@return 
*/     
    private void logRequest(NotificationRequest req, NotificationResponse res, HttpResponse httpRes){
        Notification_Log__c l;

        if(req.requestId <> null)
            l = (Notification_Log__c)StaticUtil.Single([select Attempts__c from Notification_Log__c where id =: req.requestId]);
		
        upsert new Notification_Log__c(
            Id = req.requestId,
            Request_Payload__c = JSON.serializePretty(req),
            Response_Payload__c = JSON.serializePretty(res),
            Is_Success__c = (res.result != null && res.result.toLowerCase().contains('success') ? true : false),
            Http_Status__c = (httpRes != null ? String.valueOf(httpRes.getStatusCode()) : ''),
            Http_Error__C = (httpRes != null && httpRes.getStatusCode() != 200 ? httpRes.getBody() : ''),
            TNE_ID__c = res.tneid,
            Attempts__c = (l <> null) ? l.Attempts__c + 1 : 1,
            Response_Time__c = System.now()
        );
    }

}