unpackaged/main/default/objects/Notification_Log__c/Notification_Log__c.object-meta.xml
<CustomObject>
    <label>Notification Log</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{DD}{0}</displayFormat>
        <label>Log #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notification Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Notification_Log__c/fields/TNE_ID__c.field-meta.xml
<CustomField>
    <fullName>TNE_ID__c</fullName>
    <description>TNE-generated GUID that uniquely identifies the notification so that TNE can update the notification later once it has been processed (TOCB-1615)</description>
    <externalId>true</externalId>
    <label>TNE ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/T1_Control_Settings__c/T1_Control_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>TechnologyOne settings</description>
    <label>T1 Control Settings</label>
</CustomObject>

unpackaged/main/default/objects/T1_Control_Settings__c/fields/Notification_URL__c.field-meta.xml
<CustomField>
    <fullName>Notification_URL__c</fullName>
    <label>Notification URL</label>
    <type>Url</type>
</CustomField>

unpackaged/main/default/objects/T1_Control_Settings__c/fields/T1_Max_Attempts__c.field-meta.xml
<CustomField>
    <fullName>T1_Max_Attempts__c</fullName>
    <label>T1 Max Attempts</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/T1_Control_Settings__c/fields/T1_OAuth_Endpoint__c.field-meta.xml
<CustomField>
    <fullName>T1_OAuth_Endpoint__c</fullName>
    <label>T1 OAuth Endpoint</label>
    <type>Url</type>
</CustomField>

unpackaged/main/default/objects/T1_Control_Settings__c/fields/T1_Retry_Frequency__c.field-meta.xml
<CustomField>
    <fullName>T1_Retry_Frequency__c</fullName>
    <description>T1 Retry schedule frequency in minutes</description>
    <label>T1 Retry Frequency</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/T1_Invoice__c/T1_Invoice__c.object-meta.xml
<CustomObject>
    <description>Storing the T1 Invoices.</description>
    <label>T1 Invoice</label>
    <nameField>
        <label>Invoice Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>T1 Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/T1_Invoice__c/fields/ApprovalStatus__c.field-meta.xml
<CustomField>
    <fullName>ApprovalStatus__c</fullName>
    <description>Field to support Advanced Approvals - TOCB-116</description>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Approval_Status</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/T1_Invoice__c/fields/Finance_Reviewed__c.field-meta.xml
<CustomField>
    <fullName>Finance_Reviewed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Finance Reviewed checkbox will stop the integration from syncing the invoicing until Finance have reviewed and updated the Purchase Order Number.</description>
    <label>Finance Reviewed</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/T1_Invoice__c/fields/InvoiceStatus__c.field-meta.xml
<CustomField>
    <fullName>InvoiceStatus__c</fullName>
    <description>Warning: Invoice Status is an internal field. Changing it could cause basic functionality to fail or become unstable.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>blng__InvoiceStatus</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/T1_OAuth_Token__c/T1_OAuth_Token__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>T1 OAuth Token</label>
</CustomObject>

unpackaged/main/default/globalValueSets/Approval_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Pending</fullName>
    </customValue>
    <customValue>
        <fullName>Approved</fullName>
    </customValue>
    <customValue>
        <fullName>Rejected</fullName>
    </customValue>
    <customValue>
        <fullName>Recalled</fullName>
    </customValue>
    <description>Values for Advanced Approvals Status field</description>
    <masterLabel>Approval Status</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/T1_InvoiceTrigger_Test.cls
/*******************************************************************************************************
* @Class Name   : T1_InvoiceTrigger_Test
* @description  : Test class for T1_InvoiceTrigger
* @author       : Philip Clark
* @date         : 10/03/2021
* @mod-log 
* -----------------------------------------------------------------------------------------------------
* Developer             Date            Mod ID      Description
* -----------------------------------------------------------------------------------------------------
* Philip Clark          10/03/2021      1000        Initial version
******************************************************************************************************/
@isTest
public class T1_InvoiceTrigger_Test {


    @isTest
    public static void testT1InvoiceNotificationService(){
        
        // create Notification Service test data
        insert new T1_Control_Settings__c(
            T1_OAuth_Endpoint__c =  'https://test.notification.url/oauth',
            Notification_URL__c = 'https://test.notification.url/notify',
            T1_Max_Attempts__c = 8,
            T1_Retry_Frequency__c = 120
        );

        insert new T1_OAuth_Token__c();
        
        // create Account
        Account testAccount = TestUtility.createAccount('Test Account');
        insert testAccount;
        // create T1 Invoice
        T1_Invoice__c t1i = TestUtility.createT1Invoice(testAccount.Id);
        insert t1i;
        
        Map<String,Object> r1 = (Map<String,Object>)JSON.deserializeUntyped('{        "access_token": "2YotnFZFEjr1zCsicMWpAA",        "token_type": "example",        "expires_in": 3600,        "refresh_token": "tGzv3JOkF0XG5Qx2TlKWIA"    }');

        AnyServiceMockImpl.postResponse.put(
            '/oauth',
            r1
        );

        AnyServiceMockImpl.postResponse.put(
            '/notify',
            '<?xml version="1.0" encoding="UTF-8"?>' +
            '<QTCnotres>' +
            '	<res_result>Success</res_result>' +
            '	<res_msg></res_msg>' +
            '	<tne_id>870c59fd-ebf7-f4b3-8b66-c8057f8f3dac</tne_id>' +
            '</QTCnotres>'
        );

        Test.setMock(HttpCalloutMock.class, new AnyServiceMockImpl());
        
        Test.startTest();
        t1i.ApprovalStatus__c = 'Approved';
        t1i.InvoiceStatus__c = 'Posted';
        t1i.Finance_Reviewed__c = TRUE;
        update t1i;
        Test.stopTest();
        
        list<Notification_Log__c> nl = [select Id, TNE_ID__c from Notification_Log__c];
        system.AssertEquals(1,nl.size());
        system.AssertEquals('870c59fd-ebf7-f4b3-8b66-c8057f8f3dac',nl[0].TNE_ID__c);

    }


}