unpackaged/main/default/objects/Case_Content_Purge_Action__c/Case_Content_Purge_Action__c.object-meta.xml
<CustomObject>
    <description>Used to manage Case Content Purging in regard to Privacy policy</description>
    <label>Case Content Purge Action</label>
    <nameField>
        <label>Case Content Purge Action Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Content Purge Action</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Case_Content_Purge_Action__c/fields/Action__c.field-meta.xml
<CustomField>
    <fullName>Action__c</fullName>
    <defaultValue>&#39;Delete&#39;</defaultValue>
    <inlineHelpText>Choose the type of action to be processed. Statistics Only will generate an Action Process record containing the number of records affected and it will not delete any data.</inlineHelpText>
    <label>Action</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Statistics Only - No delete</fullName>
            </value>
            <value>
                <fullName>Delete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Case_Content_Purge_Action__c/fields/Closed_Date_From__c.field-meta.xml
<CustomField>
    <fullName>Closed_Date_From__c</fullName>
    <label>Closed Date From</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Case_Content_Purge_Action__c/fields/Closed_Date_To__c.field-meta.xml
<CustomField>
    <fullName>Closed_Date_To__c</fullName>
    <defaultValue>ADDMONTHS( TODAY() ,$Setup.T1_Control_Settings__c.Case_Content_Retention_Months__c * -1)</defaultValue>
    <label>Closed Date To</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Case_Content_Purge_Action__c/fields/Commencement_Date__c.field-meta.xml
<CustomField>
    <fullName>Commencement_Date__c</fullName>
    <label>Commencement Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Case_Content_Purge_Action__c/fields/Items_to_Purge__c.field-meta.xml
<CustomField>
    <fullName>Items_to_Purge__c</fullName>
    <label>Items to Purge</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Items_to_Purge</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Case_Content_Purge_Action__c/fields/Recurring_Action__c.field-meta.xml
<CustomField>
    <fullName>Recurring_Action__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If checked this causes the Closed Date To to be recalculated after each process using Case Content Retention Months from T1 Control Setting. This allows for continuous processing based on age.</description>
    <inlineHelpText>If checked this causes the Closed Date To to be recalculated after each process using Case Content Retention Months from T1 Control Setting. This allows for continuous processing based on age.</inlineHelpText>
    <label>Recurring Action</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Case_Content_Purge_Action__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Unscheduled</fullName>
                <default>true</default>
                <label>Unscheduled</label>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/T1_Control_Settings__c/T1_Control_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>TechnologyOne settings</description>
    <label>T1 Control Settings</label>
</CustomObject>

unpackaged/main/default/objects/T1_Control_Settings__c/fields/Case_Content_Retention_Months__c.field-meta.xml
<CustomField>
    <fullName>Case_Content_Retention_Months__c</fullName>
    <label>Case Content Retention Months</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/T1_Process_Log__c/T1_Process_Log__c.object-meta.xml
<CustomObject>
    <label>T1 Process Log</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>T1 Process Log Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>T1 Process Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/T1_Process_Log__c/fields/Process_Message__c.field-meta.xml
<CustomField>
    <fullName>Process_Message__c</fullName>
    <label>Process Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/globalValueSets/Items_to_Purge.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>All</fullName>
        <default>true</default>
        <label>All</label>
    </customValue>
    <customValue>
        <fullName>Email</fullName>
    </customValue>
    <customValue>
        <fullName>Attachments</fullName>
    </customValue>
    <customValue>
        <fullName>Files</fullName>
    </customValue>
    <masterLabel>Items to Purge</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/schedCaseContentPurge.cls
global class schedCaseContentPurge implements Schedulable {
    
   	global void execute(SchedulableContext sc) {
   		
        Integer retentionMonths=60; // defaulting to 5 years
        
        T1_Control_Settings__c s = T1_Control_Settings__c.getOrgDefaults();
        if (s.Case_Content_Retention_Months__c <> NULL){
            retentionMonths = Integer.valueOf(s.Case_Content_Retention_Months__c);
        }
        
        //get the first valid Purge Action by using Limit 1 in soql
      	List<Case_Content_Purge_Action__c> ccpa = [select id, closed_date_from__c, closed_date_to__c, items_to_purge__c, recurring_action__c, action__c from Case_Content_Purge_Action__c
	   			where status__c = 'Scheduled' and commencement_date__c <= TODAY order by commencement_date__c, closed_date_from__c, createddate limit 1];
       
	  	if(ccpa.size() == 0){ // Did not find any scheduled Action
            T1_Process_Log__c procLog = new T1_Process_Log__c(Process_Name__c = 'schedCaseContentPurge',
                Process_Message__c = 'No Content Purge Actions to process.');
            insert procLog;
            system.debug('Nothing to process');
	  		return;
	  	}
	  	
        Boolean recurringAction;
        String ccpaId;
        String toProcess;
        DateTime dateFrom;
        DateTime dateTo;
        String actionType;
        
	  	for (Case_Content_Purge_Action__c d : ccpa) {
            ccpaId = d.Id;
            dateFrom = d.closed_date_from__c;
            dateTo = d.closed_date_to__c;
            toProcess = d.Items_to_Purge__c;
            recurringAction = d.Recurring_Action__c;
            actionType = d.action__c;
        }    
 
        String dateFromS = dateFrom.formatGMT('yyyy-MM-dd\'T\'HH:mm:ss\'Z\'');
        String dateToS = dateTo.formatGMT('yyyy-MM-dd\'T\'HH:mm:ss\'Z\'');
        String query;
        List<Case> cases;
        cases = [select id from case where status = 'Closed' and closeddate >= :dateFrom and closeddate <= :dateTo order by createddate limit 50000];
        query = 'select id from case where status = \'Closed\' and closeddate >= ' + dateFromS + ' and closeddate <= ' + dateToS + ' order by createddate limit 50000';

        
        if (test.isRunningTest()){
            cases = [select id from case where status = 'Closed' and closeddate >= :dateFrom and closeddate <= :dateTo order by createddate limit 10];
        	query = 'select id from case where status = \'Closed\' and closeddate >= ' + dateFromS + ' and closeddate <= ' + dateToS + ' order by createddate limit 10';
        }
        system.debug(query);
        system.debug(cases.size());
            
        if (cases.size() == 0){
            T1_Process_Log__c procLog = new T1_Process_Log__c(Process_Name__c = 'schedCaseContentPurge',
                Process_Message__c = 'No Cases to process.');
            insert procLog;
            system.debug('No cases to process');
            //complete the Action if nothing to process so it does not get in the way of future processing
            for (Case_Content_Purge_Action__c d : ccpa) {
                if (d.recurring_Action__c == true){
                    //recalc the To date
                    d.Closed_Date_From__c = d.Closed_Date_From__c.addDays(1);
                    d.Closed_Date_To__c = (system.today().addMonths(retentionMonths * -1)).addDays(1);
                    if (d.Closed_Date_From__c <= d.Closed_Date_To__c){
                        d.Closed_Date_From__c = d.Closed_Date_To__c.addDays(-1);
                    }
                }
                else {
                    d.status__c = 'Complete';
                }
            	update d;
        	}
            return;
        }
  			
        for (Case_Content_Purge_Action__c d : ccpa) {
        	d.status__c = 'In Progress';
            update d;
        }
        
        if (cases.size() > 0){
            CaseContentPurge a = new CaseContentPurge();
            a.query = query;
            a.ccpaId = ccpaId;
            a.toProcess = toProcess;
            a.recurringAction = recurringAction;
            a.actionType = actionType;
            database.executebatch(a);
        }
        
        
   	}
}