unpackaged/main/default/objects/Case_Content_Purge_Action__c/Case_Content_Purge_Action__c.object-meta.xml
<CustomObject>
    <description>Used to manage Case Content Purging in regard to Privacy policy</description>
    <label>Case Content Purge Action</label>
    <nameField>
        <label>Case Content Purge Action Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Content Purge Action</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Case_Content_Purge_Action__c/fields/Action__c.field-meta.xml
<CustomField>
    <fullName>Action__c</fullName>
    <defaultValue>&#39;Delete&#39;</defaultValue>
    <inlineHelpText>Choose the type of action to be processed. Statistics Only will generate an Action Process record containing the number of records affected and it will not delete any data.</inlineHelpText>
    <label>Action</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Statistics Only - No delete</fullName>
            </value>
            <value>
                <fullName>Delete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Case_Content_Purge_Action__c/fields/Closed_Date_From__c.field-meta.xml
<CustomField>
    <fullName>Closed_Date_From__c</fullName>
    <label>Closed Date From</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Case_Content_Purge_Action__c/fields/Closed_Date_To__c.field-meta.xml
<CustomField>
    <fullName>Closed_Date_To__c</fullName>
    <defaultValue>ADDMONTHS( TODAY() ,$Setup.T1_Control_Settings__c.Case_Content_Retention_Months__c * -1)</defaultValue>
    <label>Closed Date To</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Case_Content_Purge_Action__c/fields/Commencement_Date__c.field-meta.xml
<CustomField>
    <fullName>Commencement_Date__c</fullName>
    <label>Commencement Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Case_Content_Purge_Action__c/fields/Items_to_Purge__c.field-meta.xml
<CustomField>
    <fullName>Items_to_Purge__c</fullName>
    <label>Items to Purge</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Items_to_Purge</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Case_Content_Purge_Action__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Unscheduled</fullName>
                <default>true</default>
                <label>Unscheduled</label>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/T1_Control_Settings__c/T1_Control_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>TechnologyOne settings</description>
    <label>T1 Control Settings</label>
</CustomObject>

unpackaged/main/default/objects/T1_Control_Settings__c/fields/Case_Content_Retention_Months__c.field-meta.xml
<CustomField>
    <fullName>Case_Content_Retention_Months__c</fullName>
    <label>Case Content Retention Months</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/globalValueSets/Items_to_Purge.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>All</fullName>
        <default>true</default>
        <label>All</label>
    </customValue>
    <customValue>
        <fullName>Email</fullName>
    </customValue>
    <customValue>
        <fullName>Attachments</fullName>
    </customValue>
    <customValue>
        <fullName>Files</fullName>
    </customValue>
    <masterLabel>Items to Purge</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/schedCaseContentPurgeTest.cls
@isTest(seealldata=true)
public class schedCaseContentPurgeTest {

    static testMethod void testMethod1() 
    {
        Test.startTest();
        DateTime earliestDate;    
        for (Case cc : [select ClosedDate from case where status = 'Closed' order by ClosedDate Limit 1])
        {
            earliestDate = datetime.valueof(cc.ClosedDate);
        }    

        Case_Content_Purge_Action__c TestCCPA = new Case_Content_Purge_Action__c(Name = 'Test1',
                                      status__c = 'Unscheduled',
                                      Commencement_Date__c = date.ValueOf(system.Today()),
                                      Items_to_Purge__c = 'All',
                                      action__c = 'Delete',
                                      Closed_Date_From__c = Date.valueof('2014-09-01'),
                                      Closed_Date_To__c = Date.valueof('2014-09-02'));
        insert TestCCPA;
        schedCaseContentPurge q = new schedCaseContentPurge();
        SchedulableContext scq;
        q.execute(scq);
        
        TestCCPA.status__c = 'Scheduled';
        update TestCCPA;
        schedCaseContentPurge q2 = new schedCaseContentPurge();
        SchedulableContext scq2;
        q2.execute(scq2);

        Integer retentionMonths=36;             
        T1_Control_Settings__c custs = T1_Control_Settings__c.getOrgDefaults();
        if (custs.Case_Content_Retention_Months__c <> NULL){
            retentionMonths = Integer.valueOf(custs.Case_Content_Retention_Months__c);
        }
        
        system.debug(custs.Case_Content_Retention_Months__c);
        
        TestCCPA.Closed_Date_From__c = date.ValueOf(earliestDate);
        TestCCPA.Closed_Date_To__c = date.ValueOf(earliestDate).addDays(2);
        update TestCCPA;
        schedCaseContentPurge q3 = new schedCaseContentPurge();
        SchedulableContext scq3;
        q3.execute(scq3); 
        
        // 14/12/2018 - The below code suddenly stopped working in Prod with a Too Many Queries error. The temporary removal was necessary.
        TestCCPA.Closed_Date_To__c = date.valueof(system.today().addMonths(retentionMonths * -1).addDays(-2));
        TestCCPA.Closed_Date_From__c = TestCCPA.Closed_Date_To__c.addDays(-2);
        update TestCCPA;
        schedCaseContentPurge q4 = new schedCaseContentPurge();
        SchedulableContext scq4;
        q4.execute(scq4); 
                
        Test.stopTest();  
    }
 
}