unpackaged/main/default/objects/Account/fields/CountryArea__c.field-meta.xml
<CustomField>
    <fullName>CountryArea__c</fullName>
    <label>Country/Area</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>New Zealand</fullName>
            </value>
            <value>
                <fullName>United Kingdom</fullName>
            </value>
            <value>
                <fullName>Asia</fullName>
            </value>
            <value>
                <fullName>Pacific</fullName>
            </value>
            <value>
                <fullName>Distributors</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/T1_Industry__c.field-meta.xml
<CustomField>
    <fullName>T1_Industry__c</fullName>
    <label>Segment</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Vertical_Market__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>State Government</fullName>
            </value>
            <value>
                <fullName>Federal Government</fullName>
            </value>
            <value>
                <fullName>Central Government</fullName>
            </value>
            <value>
                <fullName>Other Government</fullName>
            </value>
            <value>
                <fullName>Local Government</fullName>
            </value>
            <value>
                <fullName>Other Local Government</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Higher Education - University</fullName>
            </value>
            <value>
                <fullName>VET Sector - TAFE/Polytech</fullName>
            </value>
            <value>
                <fullName>Private Training Provider</fullName>
            </value>
            <value>
                <fullName>Education Research Institution</fullName>
            </value>
            <value>
                <fullName>K-12/Schools</fullName>
            </value>
            <value>
                <fullName>Other Education</fullName>
            </value>
            <value>
                <fullName>Banks, Credit Unions, Building Societies</fullName>
            </value>
            <value>
                <fullName>Wealth Management (Funds and Financial Advisors)</fullName>
            </value>
            <value>
                <fullName>Superannuation</fullName>
            </value>
            <value>
                <fullName>Insurance</fullName>
            </value>
            <value>
                <fullName>Property Investment</fullName>
            </value>
            <value>
                <fullName>Other Finance</fullName>
            </value>
            <value>
                <fullName>Aged, Disability and Community Care</fullName>
            </value>
            <value>
                <fullName>Community Services</fullName>
            </value>
            <value>
                <fullName>Health</fullName>
            </value>
            <value>
                <fullName>Housing</fullName>
            </value>
            <value>
                <fullName>Other Utilities</fullName>
            </value>
            <value>
                <fullName>Natural Resources Management</fullName>
            </value>
            <value>
                <fullName>Project-centric, Engineering and Mining</fullName>
            </value>
            <value>
                <fullName>Membership-based</fullName>
            </value>
            <value>
                <fullName>Media, Entertainment, Events and Facilities Managers</fullName>
            </value>
            <value>
                <fullName>Corporate</fullName>
            </value>
            <value>
                <fullName>Other Corporate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Vertical_Market__c.field-meta.xml
<CustomField>
    <fullName>Vertical_Market__c</fullName>
    <label>Industry/Vertical</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Education</fullName>
                <color>#0B6FCE</color>
                <label>Education</label>
            </value>
            <value>
                <fullName>Financial Services</fullName>
                <color>#78C953</color>
                <label>Financial Services</label>
            </value>
            <value>
                <fullName>Government</fullName>
                <color>#E27001</color>
                <label>Government</label>
            </value>
            <value>
                <fullName>Health and Community Services</fullName>
                <color>#A845DC</color>
                <label>Health and Community Services</label>
            </value>
            <value>
                <fullName>Asset Intensive</fullName>
                <color>#999999</color>
                <label>Asset Intensive</label>
            </value>
            <value>
                <fullName>Project Intensive</fullName>
                <color>#9999FF</color>
                <label>Project Intensive</label>
            </value>
            <value>
                <fullName>Local Government</fullName>
                <color>#F3D904</color>
                <label>Local Government</label>
            </value>
            <value>
                <fullName>Corporate</fullName>
                <color>#66E9BD</color>
                <label>Corporate</label>
            </value>
            <value>
                <fullName>Finance Adjustment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Case/fields/Created_From_Case__c.field-meta.xml
<CustomField>
    <fullName>Created_From_Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is the Case from which this Case was created from. For example, when viewing a Problem Case, this would contain the Incident the Problem was initiated from when it was created.</description>
    <inlineHelpText>This is the Case from which this Case was created. For example, when viewing a Problem Case, this would contain the Incident the Problem was initiated from when it was created.</inlineHelpText>
    <label>Created From Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Cases (Created From Case)</relationshipLabel>
    <relationshipName>CasesProbtoInc</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Number_of_Related_Cases__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Related_Cases__c</fullName>
    <label>Number of Related Cases</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Problem_Cases__c.field-meta.xml
<CustomField>
    <fullName>Problem_Cases__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Problem Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Case/recordTypes/Incident.recordType-meta.xml
<RecordType>
    <fullName>Incident</fullName>
    <active>true</active>
    <businessProcess>Product Support Process</businessProcess>
    <description>Use this option if you are experiencing an issue with our software</description>
    <label>I am experiencing an issue</label>
</RecordType>

unpackaged/main/default/objects/Case/recordTypes/Problem.recordType-meta.xml
<RecordType>
    <fullName>Problem</fullName>
    <active>true</active>
    <businessProcess>S%26E Support Process</businessProcess>
    <description>Problem Record</description>
    <label>Problem</label>
</RecordType>

unpackaged/main/default/objects/Contact/fields/Vertical_Market__c.field-meta.xml
<CustomField>
    <fullName>Vertical_Market__c</fullName>
    <formula>TEXT(Account.Vertical_Market__c)</formula>
    <label>Industry/Vertical</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/recordTypes/Other.recordType-meta.xml
<RecordType>
    <fullName>Other</fullName>
    <active>true</active>
    <description>Partner/Associate/Consultant/Other</description>
    <label>Other</label>
</RecordType>

unpackaged/main/default/classes/TestupdateIncidentforProblemCase.cls
@isTest
public class TestupdateIncidentforProblemCase {
/*    
    public static testmethod void testRelatedCases() {
        Id problemRecordTypeID = [Select Id from RecordType where sObjectType = 'Case' and DeveloperName ='Problem'].Id;
        System.debug(problemRecordTypeID);

        Id incidentRecordTypeID = [Select Id from RecordType where sObjectType = 'Case' and DeveloperName ='Incident'].Id;
        System.debug(problemRecordTypeID);
        
        Account ac = new Account();
        ac.type = 'Customer';
        ac.CountryArea__c = 'Australia';
        ac.Vertical_Market__c = 'Education';
        ac.T1_Industry__c = 'Other';
        ac.Name = 'Test Account';
        insert ac;
        
        Contact con = new Contact();
        con.AccountId = ac.id;
        con.LastName = 'Test Contact';
        insert con;
        
        BusinessHours bhs = [select id from BusinessHours where IsDefault=true];
        
        Case c = new Case();
        c.AccountId = ac.id;
        c.ContactId = con.id;
        c.RecordTypeId = problemRecordTypeID;
        c.CurrencyIsoCode = 'AUD';
        c.BusinessHoursId = bhs.id;
        c.Status = 'New';
        insert c;
        
        List<Case> children = new List<Case>();
        for (integer i = 0; i < 3; i++) {
            Case child = new case();
            child.AccountId = ac.id;
            child.ContactId = con.id;
            child.CurrencyIsoCode = 'AUD';
            child.BusinessHoursId = bhs.id;
            child.Problem_Cases__c = c.id;
            child.Status = 'New';
            children.add(child);
        }
        insert children;
        
        // insert new incident
        Case c2 = new Case();
        c2.AccountId = ac.id;
        c2.ContactId = con.id;
        c2.RecordTypeId = incidentRecordTypeID;
        c2.CurrencyIsoCode = 'AUD';
        c2.BusinessHoursId = bhs.id;
        //c2.Created_From_Case__C = c.id;
        c2.Status = 'New';
        insert c2;

        // insert new problem for incident
        Case c3 = new Case();
        c3.AccountId = ac.id;
        c3.ContactId = con.id;
        c3.RecordTypeId = problemRecordTypeID;
        c3.CurrencyIsoCode = 'AUD';
        c3.BusinessHoursId = bhs.id;
        c3.Created_From_Case__C = c2.id;
        c3.Status = 'New';
        insert c3;
                
        c = [select id, Number_of_Related_Cases__c from Case where id = :c.id];
        System.assertEquals(3, c.Number_of_Related_Cases__c);
        
        children[0].Problem_Cases__c = null;
        update children[0];
        c = [select id, Number_of_Related_Cases__c from Case where id = :c.id];
        System.assertEquals(2, c.Number_of_Related_Cases__c);
        
        delete children[2];
        c = [select id, Number_of_Related_Cases__c from Case where id = :c.id];
        System.assertEquals(1, c.Number_of_Related_Cases__c);

        delete children[1];
        c = [select id, Number_of_Related_Cases__c from Case where id = :c.id];
        System.assertEquals(0, c.Number_of_Related_Cases__c);
    }
    */
}