unpackaged/main/default/objects/Account/fields/CountryArea__c.field-meta.xml
<CustomField>
    <fullName>CountryArea__c</fullName>
    <label>Country/Area</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>New Zealand</fullName>
            </value>
            <value>
                <fullName>United Kingdom</fullName>
            </value>
            <value>
                <fullName>Asia</fullName>
            </value>
            <value>
                <fullName>Pacific</fullName>
            </value>
            <value>
                <fullName>Distributors</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>CountryArea__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>ACT</fullName>
            </value>
            <value>
                <fullName>New South Wales</fullName>
            </value>
            <value>
                <fullName>Northern Territory</fullName>
            </value>
            <value>
                <fullName>Queensland</fullName>
            </value>
            <value>
                <fullName>South Australia</fullName>
            </value>
            <value>
                <fullName>Tasmania</fullName>
            </value>
            <value>
                <fullName>Victoria</fullName>
            </value>
            <value>
                <fullName>Western Australia</fullName>
            </value>
            <value>
                <fullName>New Zealand North</fullName>
            </value>
            <value>
                <fullName>New Zealand South</fullName>
            </value>
            <value>
                <fullName>UK PS South</fullName>
            </value>
            <value>
                <fullName>UK PS Central</fullName>
            </value>
            <value>
                <fullName>UK HE</fullName>
            </value>
            <value>
                <fullName>UK North &amp; Scotland</fullName>
            </value>
            <value>
                <fullName>UK Other</fullName>
                <label>UK Other (USD)</label>
            </value>
            <value>
                <fullName>Indonesia</fullName>
            </value>
            <value>
                <fullName>Malaysia</fullName>
            </value>
            <value>
                <fullName>Mongolia</fullName>
            </value>
            <value>
                <fullName>Philippines</fullName>
            </value>
            <value>
                <fullName>Singapore</fullName>
            </value>
            <value>
                <fullName>Sri Lanka</fullName>
            </value>
            <value>
                <fullName>Vietnam</fullName>
            </value>
            <value>
                <fullName>Cook Islands</fullName>
            </value>
            <value>
                <fullName>Fiji</fullName>
            </value>
            <value>
                <fullName>Kiribati</fullName>
            </value>
            <value>
                <fullName>Nauru</fullName>
            </value>
            <value>
                <fullName>PNG</fullName>
            </value>
            <value>
                <fullName>Samoa</fullName>
            </value>
            <value>
                <fullName>Solomon Islands</fullName>
            </value>
            <value>
                <fullName>Timor-Leste</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/T1_Industry__c.field-meta.xml
<CustomField>
    <fullName>T1_Industry__c</fullName>
    <label>Segment</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Vertical_Market__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>State Government</fullName>
            </value>
            <value>
                <fullName>Federal Government</fullName>
            </value>
            <value>
                <fullName>Central Government</fullName>
            </value>
            <value>
                <fullName>Other Government</fullName>
            </value>
            <value>
                <fullName>Local Government</fullName>
            </value>
            <value>
                <fullName>Other Local Government</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Higher Education - University</fullName>
            </value>
            <value>
                <fullName>VET Sector - TAFE/Polytech</fullName>
            </value>
            <value>
                <fullName>Private Training Provider</fullName>
            </value>
            <value>
                <fullName>Education Research Institution</fullName>
            </value>
            <value>
                <fullName>K-12/Schools</fullName>
            </value>
            <value>
                <fullName>Other Education</fullName>
            </value>
            <value>
                <fullName>Banks, Credit Unions, Building Societies</fullName>
            </value>
            <value>
                <fullName>Wealth Management (Funds and Financial Advisors)</fullName>
            </value>
            <value>
                <fullName>Superannuation</fullName>
            </value>
            <value>
                <fullName>Insurance</fullName>
            </value>
            <value>
                <fullName>Property Investment</fullName>
            </value>
            <value>
                <fullName>Other Finance</fullName>
            </value>
            <value>
                <fullName>Aged, Disability and Community Care</fullName>
            </value>
            <value>
                <fullName>Community Services</fullName>
            </value>
            <value>
                <fullName>Health</fullName>
            </value>
            <value>
                <fullName>Housing</fullName>
            </value>
            <value>
                <fullName>Other Utilities</fullName>
            </value>
            <value>
                <fullName>Natural Resources Management</fullName>
            </value>
            <value>
                <fullName>Project-centric, Engineering and Mining</fullName>
            </value>
            <value>
                <fullName>Membership-based</fullName>
            </value>
            <value>
                <fullName>Media, Entertainment, Events and Facilities Managers</fullName>
            </value>
            <value>
                <fullName>Corporate</fullName>
            </value>
            <value>
                <fullName>Other Corporate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Vertical_Market__c.field-meta.xml
<CustomField>
    <fullName>Vertical_Market__c</fullName>
    <label>Industry/Vertical</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Education</fullName>
                <color>#0B6FCE</color>
                <label>Education</label>
            </value>
            <value>
                <fullName>Financial Services</fullName>
                <color>#78C953</color>
                <label>Financial Services</label>
            </value>
            <value>
                <fullName>Government</fullName>
                <color>#E27001</color>
                <label>Government</label>
            </value>
            <value>
                <fullName>Health and Community Services</fullName>
                <color>#A845DC</color>
                <label>Health and Community Services</label>
            </value>
            <value>
                <fullName>Asset Intensive</fullName>
                <color>#999999</color>
                <label>Asset Intensive</label>
            </value>
            <value>
                <fullName>Project Intensive</fullName>
                <color>#9999FF</color>
                <label>Project Intensive</label>
            </value>
            <value>
                <fullName>Local Government</fullName>
                <color>#F3D904</color>
                <label>Local Government</label>
            </value>
            <value>
                <fullName>Corporate</fullName>
                <color>#66E9BD</color>
                <label>Corporate</label>
            </value>
            <value>
                <fullName>Finance Adjustment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Case/fields/Affected_Version__c.field-meta.xml
<CustomField>
    <fullName>Affected_Version__c</fullName>
    <description>Affected Version will capture the Customer&#39;s affected environment, e.g. Prod, Test etc.</description>
    <label>Affected Environment</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Production</fullName>
            </value>
            <value>
                <fullName>non-Production</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Case/fields/Customer_Product__c.field-meta.xml
<CustomField>
    <fullName>Customer_Product__c</fullName>
    <label>Product Affected</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Applicable</fullName>
            </value>
            <value>
                <fullName>Asset Management (AM)</fullName>
            </value>
            <value>
                <fullName>Business Process Management (BPM)</fullName>
            </value>
            <value>
                <fullName>Corporate Performance Management (CPM)</fullName>
            </value>
            <value>
                <fullName>Customer Relationship Management (CRM)</fullName>
            </value>
            <value>
                <fullName>Enterprise Cash Receipting (ECR)</fullName>
            </value>
            <value>
                <fullName>Enterprise Content Management (ECM)</fullName>
            </value>
            <value>
                <fullName>Financials (FIN)</fullName>
            </value>
            <value>
                <fullName>Human Resource &amp; Payroll (HRP)</fullName>
            </value>
            <value>
                <fullName>Property &amp; Rating (P&amp;R)</fullName>
            </value>
            <value>
                <fullName>Spatial</fullName>
            </value>
            <value>
                <fullName>Student Management (SM)</fullName>
            </value>
            <value>
                <fullName>Supply Chain Management (SCM)</fullName>
            </value>
            <value>
                <fullName>Enterprise App Store</fullName>
            </value>
            <value>
                <fullName>Customer Community</fullName>
            </value>
            <value>
                <fullName>Technical</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Job_Classification__c.field-meta.xml
<CustomField>
    <fullName>Job_Classification__c</fullName>
    <label>Job Classification</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Administration</fullName>
            </value>
            <value>
                <fullName>Asset Management</fullName>
            </value>
            <value>
                <fullName>Business Analyst</fullName>
            </value>
            <value>
                <fullName>Chairman / Board</fullName>
            </value>
            <value>
                <fullName>Chief Executive Officer / MD</fullName>
            </value>
            <value>
                <fullName>Chief Financial Officer</fullName>
            </value>
            <value>
                <fullName>Chief Information Officer</fullName>
            </value>
            <value>
                <fullName>Chief Operating Officer</fullName>
            </value>
            <value>
                <fullName>Corporate Performance Management</fullName>
            </value>
            <value>
                <fullName>Corporate Services Management</fullName>
            </value>
            <value>
                <fullName>Customer Service</fullName>
            </value>
            <value>
                <fullName>Education</fullName>
            </value>
            <value>
                <fullName>Finance Officer</fullName>
            </value>
            <value>
                <fullName>Finance - Senior</fullName>
            </value>
            <value>
                <fullName>Fleet Management</fullName>
            </value>
            <value>
                <fullName>Fundraising Manager</fullName>
            </value>
            <value>
                <fullName>Grants Management</fullName>
            </value>
            <value>
                <fullName>Head of Transformation</fullName>
            </value>
            <value>
                <fullName>Health</fullName>
            </value>
            <value>
                <fullName>Housing Manager</fullName>
            </value>
            <value>
                <fullName>HR - Junior</fullName>
            </value>
            <value>
                <fullName>HR - Senior</fullName>
            </value>
            <value>
                <fullName>HR Safety</fullName>
            </value>
            <value>
                <fullName>HR Training and Development</fullName>
            </value>
            <value>
                <fullName>IT - Junior &amp; Systems Admin</fullName>
            </value>
            <value>
                <fullName>IT - Senior</fullName>
            </value>
            <value>
                <fullName>Mayor and Councillors</fullName>
            </value>
            <value>
                <fullName>Ministerial Liaison</fullName>
            </value>
            <value>
                <fullName>Payroll - Junior</fullName>
            </value>
            <value>
                <fullName>Payroll - Senior</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <description>Region of the account to use in List View/Reports etc</description>
    <formula>TEXT(Account.Region__c)</formula>
    <label>Region</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Vertical_Market__c.field-meta.xml
<CustomField>
    <fullName>Vertical_Market__c</fullName>
    <formula>TEXT(Account.Vertical_Market__c)</formula>
    <label>Industry/Vertical</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/CSFeedItemTriggerHandler_Test.cls
/**
 * File Info
 * ----------------------------------
 * @filename       CSFeedItemTriggerHandler_Test.cls
 * @created        24.SEPT.2014
 * @author         Kristian Vegerano
 * @description    Test Class for FeedItem Triggers Handler Class
 */
@isTest(SeeAllData=True)
private class CSFeedItemTriggerHandler_Test {
    /**
     * @description    This method tests case comment creation on case priority change
     * @author         Kristian Vegerano - 24.SEPT.2014
     */
     static testMethod void Test_SetCasePortalFlag() {
        //Initialize Variables
        Case testCase;
        User currentAdminUser = CreateStandardRunningUser();
        currentAdminUser.UserRoleId = [SELECT Id FROM UserRole LIMIT 1].Id;
        insert currentAdminUser;
        
        //Create Account and Contact for the CommunityUser
        Account testAccount;
        Contact testContact;
        system.runAs(currentAdminUser){
                        testAccount = new Account(Name = 'Test Account',
                                      CountryArea__c = 'Australia',
									  Region__c = 'ACT',                                                  
                                      Type = 'Customer',
                                      T1_Industry__c = 'State Government',
                                      Vertical_Market__c = 'Education');
            insert testAccount;
            
            testContact = new Contact(LastName = 'TestContact', AccountId = testAccount.Id, Job_Classification__c = 'A', Title = 'Mr');
            insert testContact;
            insert testCase = new Case(Description = 'A Description', Customer_Product__c = 'Financials (FIN)', Affected_Version__c = 'non-Production', 
                                 Subject = 'A subject', Work_around_Details__c = 'A bit of text', CFunctional_Area__c = 'testing', 
                                 Has_it_worked_before__c = 'No', Is_there_a_scalable_work_around__c = 'No', Steps_to_reproduce__c = '12345678910', AccountId = testAccount.Id);

        }
        
        User currentCommunityUser = CreateCommunityRunningUser();
        currentCommunityUser.contactId = testContact.Id;
        insert currentCommunityUser;
        
        system.runAs(currentAdminUser){
            Test.startTest();
                FeedItem testFeedItem = new FeedItem(Type = 'TextPost', ParentId = testCase.Id, Body = 'TestBody');
                insert testFeedItem;
            Test.stopTest();
        }
        
        System.assertEquals(true, [SELECT Id, new_portal_case_comment__c FROM Case WHERE Id = :testCase.Id].new_portal_case_comment__c);
    }
    
    /**
     * @description    This method tests case comment creation on case owner change
     * @author         Kristian Vegerano - 24.SEPT.2014
     */
    static testMethod void Test_SetCasePortalAttachmentFlag() {
        //Initialize Variables
        Case testCase;
        User currentAdminUser = CreateStandardRunningUser();
        currentAdminUser.UserRoleId = [SELECT Id FROM UserRole LIMIT 1].Id;
        insert currentAdminUser;
        
        //Create Account and Contact for the CommunityUser
        Account testAccount;
        Contact testContact;
        system.runAs(currentAdminUser){
           
            testAccount = new Account(Name = 'Test Account',
                                      CountryArea__c = 'Australia',
                                      Region__c = 'ACT',
                                      Type = 'Customer',
                                      T1_Industry__c = 'State Government',
                                      Vertical_Market__c = 'Education');
            insert testAccount;
            testContact = new Contact(LastName = 'TestContact', AccountId = testAccount.Id, Job_Classification__c = 'A', Title = 'Mr');
            insert testContact;
            insert testCase = new Case(Description = 'A Description', Customer_Product__c = 'Financials (FIN)', Affected_Version__c = 'non-Production', 
                                 Subject = 'A subject', Work_around_Details__c = 'A bit of text', CFunctional_Area__c = 'testing', 
                                 Has_it_worked_before__c = 'No', Is_there_a_scalable_work_around__c = 'No', Steps_to_reproduce__c = '12345678910', AccountId = testAccount.Id);
        }
        
        User currentCommunityUser = CreateCommunityRunningUser();
        currentCommunityUser.contactId = testContact.Id;
        insert currentCommunityUser;
        
        system.runAs(currentAdminUser){
            Test.startTest();
                FeedItem testFeedItem = new FeedItem(Type = 'ContentPost', ParentId = testCase.Id, Body = 'TestBody', ContentFileName = 'TestFileName', ContentData = Blob.valueOf('TestPost'));
                insert testFeedItem;
            Test.stopTest();
        }
        
        System.assertEquals(true, [SELECT Id, new_customer_attachment__c FROM Case WHERE Id = :testCase.Id].new_customer_attachment__c);
    }
    
    /**
      * @description Test method for creating running user with standard profile.
      * @author Kristian Vegerano - 24.SEPT.2014
      */
     @isTest(SeeAllData=True) public static User CreateStandardRunningUser(){
          Profile p1 = [SELECT Id FROM Profile WHERE Name='System Administrator']; 
          User dummyUser = new User();
          dummyUser.Alias = 'standt'; 
          dummyUser.Email='standarduser@testorg.com';
          dummyUser.EmailEncodingKey='UTF-8';
          dummyUser.LastName='Testing';
          dummyUser.LanguageLocaleKey='en_US';
          dummyUser.LocaleSidKey='en_US'; 
          dummyUser.ProfileId = p1.Id;
          dummyUser.TimeZoneSidKey='America/Los_Angeles';
          dummyUser.UserName='u2@u1.com';
          return dummyUser;
     }
     
     /**
      * @description Test method for creating running user with standard profile.
      * @author Kristian Vegerano - 24.SEPT.2014
      */
     @isTest(SeeAllData=True) public static User CreateCommunityRunningUser(){
          Profile p1 = [SELECT Id FROM Profile WHERE Name LIKE '%Customer Support Community%' LIMIT 1]; 
          User dummyUser = new User();
          dummyUser.Alias = 'commun'; 
          dummyUser.Email='communityuser@testorg.com';
          dummyUser.EmailEncodingKey='UTF-8';
          dummyUser.LastName='Community';
          dummyUser.LanguageLocaleKey='en_US';
          dummyUser.LocaleSidKey='en_US'; 
          dummyUser.ProfileId = p1.Id;
          dummyUser.TimeZoneSidKey='America/Los_Angeles';
          dummyUser.UserName='c2@u1.com';
          return dummyUser;
     }
}