unpackaged/main/default/objects/Account/fields/Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Country_Code__c</fullName>
    <label>Country Code</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>CountryArea__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>13</fullName>
            </value>
            <value>
                <fullName>15</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/CountryArea__c.field-meta.xml
<CustomField>
    <fullName>CountryArea__c</fullName>
    <label>Country/Area</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>New Zealand</fullName>
            </value>
            <value>
                <fullName>United Kingdom</fullName>
            </value>
            <value>
                <fullName>Asia</fullName>
            </value>
            <value>
                <fullName>Pacific</fullName>
            </value>
            <value>
                <fullName>Distributors</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>CountryArea__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>ACT</fullName>
            </value>
            <value>
                <fullName>New South Wales</fullName>
            </value>
            <value>
                <fullName>Northern Territory</fullName>
            </value>
            <value>
                <fullName>Queensland</fullName>
            </value>
            <value>
                <fullName>South Australia</fullName>
            </value>
            <value>
                <fullName>Tasmania</fullName>
            </value>
            <value>
                <fullName>Victoria</fullName>
            </value>
            <value>
                <fullName>Western Australia</fullName>
            </value>
            <value>
                <fullName>New Zealand North</fullName>
            </value>
            <value>
                <fullName>New Zealand South</fullName>
            </value>
            <value>
                <fullName>UK PS South</fullName>
            </value>
            <value>
                <fullName>UK PS Central</fullName>
            </value>
            <value>
                <fullName>UK HE</fullName>
            </value>
            <value>
                <fullName>UK North &amp; Scotland</fullName>
            </value>
            <value>
                <fullName>UK Other</fullName>
                <label>UK Other (USD)</label>
            </value>
            <value>
                <fullName>Indonesia</fullName>
            </value>
            <value>
                <fullName>Malaysia</fullName>
            </value>
            <value>
                <fullName>Mongolia</fullName>
            </value>
            <value>
                <fullName>Philippines</fullName>
            </value>
            <value>
                <fullName>Singapore</fullName>
            </value>
            <value>
                <fullName>Sri Lanka</fullName>
            </value>
            <value>
                <fullName>Vietnam</fullName>
            </value>
            <value>
                <fullName>Cook Islands</fullName>
            </value>
            <value>
                <fullName>Fiji</fullName>
            </value>
            <value>
                <fullName>Kiribati</fullName>
            </value>
            <value>
                <fullName>Nauru</fullName>
            </value>
            <value>
                <fullName>PNG</fullName>
            </value>
            <value>
                <fullName>Samoa</fullName>
            </value>
            <value>
                <fullName>Solomon Islands</fullName>
            </value>
            <value>
                <fullName>Timor-Leste</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/T1_Industry__c.field-meta.xml
<CustomField>
    <fullName>T1_Industry__c</fullName>
    <label>Segment</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Vertical_Market__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>State Government</fullName>
            </value>
            <value>
                <fullName>Federal Government</fullName>
            </value>
            <value>
                <fullName>Central Government</fullName>
            </value>
            <value>
                <fullName>Other Government</fullName>
            </value>
            <value>
                <fullName>Local Government</fullName>
            </value>
            <value>
                <fullName>Other Local Government</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Higher Education - University</fullName>
            </value>
            <value>
                <fullName>VET Sector - TAFE/Polytech</fullName>
            </value>
            <value>
                <fullName>Private Training Provider</fullName>
            </value>
            <value>
                <fullName>Education Research Institution</fullName>
            </value>
            <value>
                <fullName>K-12/Schools</fullName>
            </value>
            <value>
                <fullName>Other Education</fullName>
            </value>
            <value>
                <fullName>Banks, Credit Unions, Building Societies</fullName>
            </value>
            <value>
                <fullName>Wealth Management (Funds and Financial Advisors)</fullName>
            </value>
            <value>
                <fullName>Superannuation</fullName>
            </value>
            <value>
                <fullName>Insurance</fullName>
            </value>
            <value>
                <fullName>Property Investment</fullName>
            </value>
            <value>
                <fullName>Other Finance</fullName>
            </value>
            <value>
                <fullName>Aged, Disability and Community Care</fullName>
            </value>
            <value>
                <fullName>Community Services</fullName>
            </value>
            <value>
                <fullName>Health</fullName>
            </value>
            <value>
                <fullName>Housing</fullName>
            </value>
            <value>
                <fullName>Other Utilities</fullName>
            </value>
            <value>
                <fullName>Natural Resources Management</fullName>
            </value>
            <value>
                <fullName>Project-centric, Engineering and Mining</fullName>
            </value>
            <value>
                <fullName>Membership-based</fullName>
            </value>
            <value>
                <fullName>Media, Entertainment, Events and Facilities Managers</fullName>
            </value>
            <value>
                <fullName>Corporate</fullName>
            </value>
            <value>
                <fullName>Other Corporate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Vertical_Market__c.field-meta.xml
<CustomField>
    <fullName>Vertical_Market__c</fullName>
    <label>Industry/Vertical</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Education</fullName>
                <color>#0B6FCE</color>
                <label>Education</label>
            </value>
            <value>
                <fullName>Financial Services</fullName>
                <color>#78C953</color>
                <label>Financial Services</label>
            </value>
            <value>
                <fullName>Government</fullName>
                <color>#E27001</color>
                <label>Government</label>
            </value>
            <value>
                <fullName>Health and Community Services</fullName>
                <color>#A845DC</color>
                <label>Health and Community Services</label>
            </value>
            <value>
                <fullName>Asset Intensive</fullName>
                <color>#999999</color>
                <label>Asset Intensive</label>
            </value>
            <value>
                <fullName>Project Intensive</fullName>
                <color>#9999FF</color>
                <label>Project Intensive</label>
            </value>
            <value>
                <fullName>Local Government</fullName>
                <color>#F3D904</color>
                <label>Local Government</label>
            </value>
            <value>
                <fullName>Corporate</fullName>
                <color>#66E9BD</color>
                <label>Corporate</label>
            </value>
            <value>
                <fullName>Finance Adjustment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contract/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <formula>TEXT(Account.Region__c)</formula>
    <label>Region</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Auto_Renew__c.field-meta.xml
<CustomField>
    <fullName>Auto_Renew__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Auto Renew</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Auto_Renewal_Date__c.field-meta.xml
<CustomField>
    <fullName>Auto_Renewal_Date__c</fullName>
    <label>Auto-Renewal Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Auto_Renewal_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Auto_Renewal_End_Date__c</fullName>
    <label>Auto-Renewal End Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Auto_Renewal_Treatment__c.field-meta.xml
<CustomField>
    <fullName>Auto_Renewal_Treatment__c</fullName>
    <label>Auto-Renewal Treatment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Auto_Renewal_Treatment</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Country_Code__c</fullName>
    <description>Returns the BU Code depending on the Account&#39;s Country/Region selected.</description>
    <formula>CASE( Account.CountryArea__c ,
&quot;Australia&quot;,&quot;11&quot;,
&quot;New Zealand&quot;,&quot;13&quot;,
&quot;United Kingdom&quot;,&quot;15&quot;,
&quot;Asia&quot;,&quot;12&quot;,
&quot;Pacific&quot;,&quot;11&quot;,
&quot;Distributors&quot;,&quot;11&quot;,
NULL)</formula>
    <inlineHelpText>Country Code of the corresponding Account&#39;s Country/Region selected.</inlineHelpText>
    <label>Country Code</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <formula>TEXT( Account.Region__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Region</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Stop_Auto_Renewal__c.field-meta.xml
<CustomField>
    <fullName>Stop_Auto_Renewal__c</fullName>
    <label>Stop Auto-Order</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/T1_Industry__c.field-meta.xml
<CustomField>
    <fullName>T1_Industry__c</fullName>
    <formula>TEXT( Account.T1_Industry__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Segment</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Vertical_Market__c.field-meta.xml
<CustomField>
    <fullName>Vertical_Market__c</fullName>
    <formula>TEXT(Account.Vertical_Market__c )</formula>
    <label>Industry/Vertical</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ServiceContract/fields/Auto_Renew__c.field-meta.xml
<CustomField>
    <fullName>Auto_Renew__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Auto Renew</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/ServiceContract/fields/Auto_Renewal_Date__c.field-meta.xml
<CustomField>
    <fullName>Auto_Renewal_Date__c</fullName>
    <label>Auto-Renewal Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/ServiceContract/fields/Auto_Renewal_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Auto_Renewal_End_Date__c</fullName>
    <label>Auto-Renewal End Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/ServiceContract/fields/Auto_Renewal_Treatment__c.field-meta.xml
<CustomField>
    <fullName>Auto_Renewal_Treatment__c</fullName>
    <label>Auto-Renewal Treatment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Auto_Renewal_Treatment</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ServiceContract/fields/Stop_Auto_Renewal__c.field-meta.xml
<CustomField>
    <fullName>Stop_Auto_Renewal__c</fullName>
    <label>Stop Auto-Order</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/globalValueSets/Auto_Renewal_Treatment.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Auto-Renew continuously – 12 months</fullName>
        <default>true</default>
        <label>Auto-Renew continuously – 12 months</label>
    </customValue>
    <customValue>
        <fullName>Auto-Create Opportunity and Quote</fullName>
    </customValue>
    <customValue>
        <fullName>Do Not Auto-Renew</fullName>
    </customValue>
    <masterLabel>Auto-Renewal Treatment</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/TestDataFactory.cls
/*******************************************************************************************************
* @Class Name   : TestDataFactory
* @description  : Test data factory
* @author       : Carlos Roy Billones
* @date         : 08/12/2020
* @mod-log 
* -----------------------------------------------------------------------------------------------------
* Developer             Date            Mod ID      Description
* -----------------------------------------------------------------------------------------------------
* Carlos Roy Billones   08/12/2020      1000        Initial version
* Yi Zhang              12/03/2021      2000        Applied comments
******************************************************************************************************/
@isTest
public class TestDataFactory {
	
    public static SBQQ__Quote__c createQuote() {
        SBQQ__Quote__c quote = new SBQQ__Quote__c();
        
        quote.SBQQ__StartDate__c = Date.today();
        
        return quote;
    }
    
    public static SBQQ__QuoteLineGroup__c createQuoteLineGroup(SBQQ__Quote__c quote) {
       SBQQ__QuoteLineGroup__c quotelinegroup = new SBQQ__QuoteLineGroup__c();
        quotelinegroup.SBQQ__Quote__c = quote.Id;
        quotelinegroup.Period_Type__c = 'Free Period';
        quotelinegroup.Name = 'Free Period';
        quotelinegroup.SBQQ__StartDate__c = Date.today();
        quotelinegroup.SBQQ__EndDate__c = Date.today().addMonths(3);
        
        return quotelinegroup;
    }
    
    public static SBQQ__QuoteLine__c createQuoteLine(SBQQ__Quote__c quote) {
       SBQQ__QuoteLine__c quoteline = new SBQQ__QuoteLine__c();
        quoteline.SBQQ__Quote__c = quote.Id;
        return quoteline;
    }
    
    public static ServiceContract createServiceContractforRenewalBatchApex() {
       ServiceContract serveCon = new ServiceContract(Name='Test Service Contract',
                                                      StartDate=Date.newInstance(2021, 1, 6),
                                                      EndDate=Date.newInstance(2022, 1, 6),
                                                      Auto_Renewal_Date__c=Date.newInstance(2021, 1, 6),
                                                      Auto_Renewal_Treatment__c='Auto-Renew continuously – 12 months',
                                                      Auto_Renewal_End_Date__c = Date.newInstance(2022, 1, 6),
                                                      Stop_Auto_Renewal__c = null);
        return serveCon;
    }
    
    public static Opportunity createOpportunityforRenewalBatchApex() {
       Opportunity opp = new Opportunity(Name='Test Opportunity Carlos123', 
                                         CloseDate=Date.newInstance(2022, 1, 6),
                                         StageName='Discovery',
                                         Auto_Renew__c = true);

        return opp;
    }
    
    public static Account createAccount() {
       Account acct = new Account(Name='Carlos Test Account',
                                  CountryArea__c='Australia', 
                                  Region__c='Western Australia', 
                                  T1_Industry__c='Other Education', 
                                  Vertical_Market__c='Education', 
                                  Type='Customer',
                                  Country_Code__c='11');

        return acct;
    }
    
    
}