unpackaged/main/default/objects/Account/fields/CountryArea__c.field-meta.xml
<CustomField>
    <fullName>CountryArea__c</fullName>
    <label>Country/Area</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>New Zealand</fullName>
            </value>
            <value>
                <fullName>United Kingdom</fullName>
            </value>
            <value>
                <fullName>Asia</fullName>
            </value>
            <value>
                <fullName>Pacific</fullName>
            </value>
            <value>
                <fullName>Distributors</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>CountryArea__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>ACT</fullName>
            </value>
            <value>
                <fullName>New South Wales</fullName>
            </value>
            <value>
                <fullName>Northern Territory</fullName>
            </value>
            <value>
                <fullName>Queensland</fullName>
            </value>
            <value>
                <fullName>South Australia</fullName>
            </value>
            <value>
                <fullName>Tasmania</fullName>
            </value>
            <value>
                <fullName>Victoria</fullName>
            </value>
            <value>
                <fullName>Western Australia</fullName>
            </value>
            <value>
                <fullName>New Zealand North</fullName>
            </value>
            <value>
                <fullName>New Zealand South</fullName>
            </value>
            <value>
                <fullName>UK PS South</fullName>
            </value>
            <value>
                <fullName>UK PS Central</fullName>
            </value>
            <value>
                <fullName>UK HE</fullName>
            </value>
            <value>
                <fullName>UK North &amp; Scotland</fullName>
            </value>
            <value>
                <fullName>UK Other</fullName>
                <label>UK Other (USD)</label>
            </value>
            <value>
                <fullName>Indonesia</fullName>
            </value>
            <value>
                <fullName>Malaysia</fullName>
            </value>
            <value>
                <fullName>Mongolia</fullName>
            </value>
            <value>
                <fullName>Philippines</fullName>
            </value>
            <value>
                <fullName>Singapore</fullName>
            </value>
            <value>
                <fullName>Sri Lanka</fullName>
            </value>
            <value>
                <fullName>Vietnam</fullName>
            </value>
            <value>
                <fullName>Cook Islands</fullName>
            </value>
            <value>
                <fullName>Fiji</fullName>
            </value>
            <value>
                <fullName>Kiribati</fullName>
            </value>
            <value>
                <fullName>Nauru</fullName>
            </value>
            <value>
                <fullName>PNG</fullName>
            </value>
            <value>
                <fullName>Samoa</fullName>
            </value>
            <value>
                <fullName>Solomon Islands</fullName>
            </value>
            <value>
                <fullName>Timor-Leste</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/T1_Industry__c.field-meta.xml
<CustomField>
    <fullName>T1_Industry__c</fullName>
    <label>Segment</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Vertical_Market__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>State Government</fullName>
            </value>
            <value>
                <fullName>Federal Government</fullName>
            </value>
            <value>
                <fullName>Central Government</fullName>
            </value>
            <value>
                <fullName>Other Government</fullName>
            </value>
            <value>
                <fullName>Local Government</fullName>
            </value>
            <value>
                <fullName>Other Local Government</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Higher Education - University</fullName>
            </value>
            <value>
                <fullName>VET Sector - TAFE/Polytech</fullName>
            </value>
            <value>
                <fullName>Private Training Provider</fullName>
            </value>
            <value>
                <fullName>Education Research Institution</fullName>
            </value>
            <value>
                <fullName>K-12/Schools</fullName>
            </value>
            <value>
                <fullName>Other Education</fullName>
            </value>
            <value>
                <fullName>Banks, Credit Unions, Building Societies</fullName>
            </value>
            <value>
                <fullName>Wealth Management (Funds and Financial Advisors)</fullName>
            </value>
            <value>
                <fullName>Superannuation</fullName>
            </value>
            <value>
                <fullName>Insurance</fullName>
            </value>
            <value>
                <fullName>Property Investment</fullName>
            </value>
            <value>
                <fullName>Other Finance</fullName>
            </value>
            <value>
                <fullName>Aged, Disability and Community Care</fullName>
            </value>
            <value>
                <fullName>Community Services</fullName>
            </value>
            <value>
                <fullName>Health</fullName>
            </value>
            <value>
                <fullName>Housing</fullName>
            </value>
            <value>
                <fullName>Other Utilities</fullName>
            </value>
            <value>
                <fullName>Natural Resources Management</fullName>
            </value>
            <value>
                <fullName>Project-centric, Engineering and Mining</fullName>
            </value>
            <value>
                <fullName>Membership-based</fullName>
            </value>
            <value>
                <fullName>Media, Entertainment, Events and Facilities Managers</fullName>
            </value>
            <value>
                <fullName>Corporate</fullName>
            </value>
            <value>
                <fullName>Other Corporate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Vertical_Market__c.field-meta.xml
<CustomField>
    <fullName>Vertical_Market__c</fullName>
    <label>Industry/Vertical</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Education</fullName>
                <color>#0B6FCE</color>
                <label>Education</label>
            </value>
            <value>
                <fullName>Financial Services</fullName>
                <color>#78C953</color>
                <label>Financial Services</label>
            </value>
            <value>
                <fullName>Government</fullName>
                <color>#E27001</color>
                <label>Government</label>
            </value>
            <value>
                <fullName>Health and Community Services</fullName>
                <color>#A845DC</color>
                <label>Health and Community Services</label>
            </value>
            <value>
                <fullName>Asset Intensive</fullName>
                <color>#999999</color>
                <label>Asset Intensive</label>
            </value>
            <value>
                <fullName>Project Intensive</fullName>
                <color>#9999FF</color>
                <label>Project Intensive</label>
            </value>
            <value>
                <fullName>Local Government</fullName>
                <color>#F3D904</color>
                <label>Local Government</label>
            </value>
            <value>
                <fullName>Corporate</fullName>
                <color>#66E9BD</color>
                <label>Corporate</label>
            </value>
            <value>
                <fullName>Finance Adjustment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account_Service_Product__c/Account_Service_Product__c.object-meta.xml
<CustomObject>
    <label>Account Service Product</label>
    <nameField>
        <displayFormat>a-{00000000}</displayFormat>
        <label>Account Service Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Service Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Account_Service_Product__c/fields/AccountId__c.field-meta.xml
<CustomField>
    <fullName>AccountId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Service Products</relationshipLabel>
    <relationshipName>Account_Service_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Asset/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Earnie IQ</fullName>
            </value>
            <value>
                <fullName>Escrow</fullName>
            </value>
            <value>
                <fullName>Health Metrics</fullName>
            </value>
            <value>
                <fullName>IT Glovebox</fullName>
            </value>
            <value>
                <fullName>ScanWatcher</fullName>
            </value>
            <value>
                <fullName>TechnologyOne Adaptive Solutions</fullName>
            </value>
            <value>
                <fullName>TechnologyOne ADF</fullName>
            </value>
            <value>
                <fullName>TechnologyOne Breakout Packs</fullName>
            </value>
            <value>
                <fullName>TechnologyOne Corporate Performance Management</fullName>
            </value>
            <value>
                <fullName>TechnologyOne CPM External Systems Connectors</fullName>
            </value>
            <value>
                <fullName>TechnologyOne ECM</fullName>
            </value>
            <value>
                <fullName>TechnologyOne ECR External Systems</fullName>
            </value>
            <value>
                <fullName>TechnologyOne Enterprise Asset Management</fullName>
            </value>
            <value>
                <fullName>TechnologyOne Enterprise Cash Receipting</fullName>
            </value>
            <value>
                <fullName>TechnologyOne Fax Gateway</fullName>
            </value>
            <value>
                <fullName>TechnologyOne Financials</fullName>
            </value>
            <value>
                <fullName>TechnologyOne Fleet Solution</fullName>
            </value>
            <value>
                <fullName>TechnologyOne HR and Payroll</fullName>
            </value>
            <value>
                <fullName>TechnologyOne Mobile</fullName>
            </value>
            <value>
                <fullName>TechnologyOne Performance Planning</fullName>
            </value>
            <value>
                <fullName>TechnologyOne PLUS</fullName>
            </value>
            <value>
                <fullName>TechnologyOne Property</fullName>
            </value>
            <value>
                <fullName>TechnologyOne Publisher</fullName>
            </value>
            <value>
                <fullName>TechnologyOne R &amp; D</fullName>
            </value>
            <value>
                <fullName>TechnologyOne Services Only</fullName>
            </value>
            <value>
                <fullName>TechnologyOne Solution Fee</fullName>
            </value>
            <value>
                <fullName>TechnologyOne Solution Template</fullName>
            </value>
            <value>
                <fullName>TechnologyOne Stock Usage</fullName>
            </value>
            <value>
                <fullName>TechnologyOne Student Management</fullName>
            </value>
            <value>
                <fullName>TechnologyOne Supply Chain Management</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Product_or_Module__c.field-meta.xml
<CustomField>
    <fullName>Product_or_Module__c</fullName>
    <label>Hierarchy Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Product</fullName>
            </value>
            <value>
                <fullName>Module</fullName>
                <default>true</default>
                <label>Module</label>
            </value>
            <value>
                <fullName>Solution</fullName>
            </value>
            <value>
                <fullName>Service Pack</fullName>
            </value>
            <value>
                <fullName>AMS Program</fullName>
            </value>
            <value>
                <fullName>Saas Platform</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/T1_Control_Settings__c/T1_Control_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>TechnologyOne settings</description>
    <label>T1 Control Settings</label>
</CustomObject>

unpackaged/main/default/objects/T1_Control_Settings__c/fields/Bypass_Workflow__c.field-meta.xml
<CustomField>
    <fullName>Bypass_Workflow__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bypass Workflow</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/T1_Control_Settings__c/fields/Customer_Community_URL__c.field-meta.xml
<CustomField>
    <fullName>Customer_Community_URL__c</fullName>
    <label>Customer Community URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/T1_Control_Settings__c/fields/Employee_Community_URL__c.field-meta.xml
<CustomField>
    <fullName>Employee_Community_URL__c</fullName>
    <label>Employee Community URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/batchUpdateAccServProdDailyTest.cls
/**
 * @description       : 
 * @author            : Grant Hamlyn
 * @group             : 
 * @last modified on  : 19-02-2021
 * @last modified by  : Grant Hamlyn
 * Modifications Log 
 * Ver   Date         Author         Modification
 * 1.0   19-02-2021   Grant Hamlyn   Initial Version
**/
@isTest(SeeAllData=True)
public inherited sharing class batchUpdateAccServProdDailyTest {
         static testMethod void testMethod1() 
        {

            Id modId1 = null;
            Id modId2 = null;

            // get a couple of Modules
            List<Product2> lProduct2 = [SELECT id FROM Product2 where product_or_module__c = 'Module'];
            for (Product2 l_Product2 : lProduct2) {
                if (modId1 == null){
                    modId1 = l_Product2.Id;
                    continue;
                }
                if(modId2 == null){
                    modId2 = l_Product2.Id;
                    continue;
                }
                break;
            }
            Account ac = new Account();
            ac.type = 'Customer';
            ac.CountryArea__c = 'Australia';
            ac.Region__c = 'ACT';
            ac.Vertical_Market__c = 'Education';
            ac.T1_Industry__c = 'Other';
            ac.Name = 'Test Account for batchUpdateAccServProdDaily';
            
            insert ac;
            
            Asset ass = new Asset();
            ass.AccountId = ac.Id;
            ass.Product__c = 'TechnologyOne Financials';
            ass.status = 'Active';
            ass.Name = 'Test Asset for batchUpdateAccServProdDaily 1';
            ass.Product2Id = modId1;
            insert ass;

            Asset ass2 = new Asset();
            ass2.AccountId = ac.Id;
            ass2.Product__c = 'TechnologyOne Something else';
            ass2.status = 'Active';
            ass2.Name = 'Test Account for batchUpdateAccServProdDaily 2';
            ass2.Product2Id = modId2;
            insert ass2;
    
            // insert Account Service Product record
            Account_Service_Product__c asp = new Account_Service_Product__c();
            asp.AccountId__c = ac.Id;
            insert asp;
                        
            // ensure triggers, workflow and validation rules are deactivated          
            T1_Control_Settings__c s = T1_Control_Settings__c.getInstance( UserInfo.GetUserID() ); //or Profile
            s.Bypass_Triggers__c = true;
            s.Bypass_Validation_Rules__c = true;
            s.Bypass_Workflow__c = true;
            s.Customer_Community_URL__c = '';
            s.Employee_Community_URL__c = '';
            s.Internal_URL__c = '';
            s.Closed_Date_for_Archiving_Email__c = null;
            upsert s;
    
            Test.startTest();
                batchUpdateAccServProdDaily c = new batchUpdateAccServProdDaily();
                Database.executeBatch(c);
            Test.stopTest();
            
            s.Bypass_Triggers__c = false;
            s.Bypass_Validation_Rules__c = false;
            s.Bypass_Workflow__c = false;
            s.Customer_Community_URL__c = '';
            s.Employee_Community_URL__c = '';
            s.Internal_URL__c = '';
            s.Closed_Date_for_Archiving_Email__c = null;
            upsert s;
        } 
    }