unpackaged/main/default/objects/Account/fields/CountryArea__c.field-meta.xml
<CustomField>
    <fullName>CountryArea__c</fullName>
    <label>Country/Area</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>New Zealand</fullName>
            </value>
            <value>
                <fullName>United Kingdom</fullName>
            </value>
            <value>
                <fullName>Asia</fullName>
            </value>
            <value>
                <fullName>Pacific</fullName>
            </value>
            <value>
                <fullName>Distributors</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>CountryArea__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>ACT</fullName>
            </value>
            <value>
                <fullName>New South Wales</fullName>
            </value>
            <value>
                <fullName>Northern Territory</fullName>
            </value>
            <value>
                <fullName>Queensland</fullName>
            </value>
            <value>
                <fullName>South Australia</fullName>
            </value>
            <value>
                <fullName>Tasmania</fullName>
            </value>
            <value>
                <fullName>Victoria</fullName>
            </value>
            <value>
                <fullName>Western Australia</fullName>
            </value>
            <value>
                <fullName>New Zealand North</fullName>
            </value>
            <value>
                <fullName>New Zealand South</fullName>
            </value>
            <value>
                <fullName>UK PS South</fullName>
            </value>
            <value>
                <fullName>UK PS Central</fullName>
            </value>
            <value>
                <fullName>UK HE</fullName>
            </value>
            <value>
                <fullName>UK North &amp; Scotland</fullName>
            </value>
            <value>
                <fullName>UK Other</fullName>
                <label>UK Other (USD)</label>
            </value>
            <value>
                <fullName>Indonesia</fullName>
            </value>
            <value>
                <fullName>Malaysia</fullName>
            </value>
            <value>
                <fullName>Mongolia</fullName>
            </value>
            <value>
                <fullName>Philippines</fullName>
            </value>
            <value>
                <fullName>Singapore</fullName>
            </value>
            <value>
                <fullName>Sri Lanka</fullName>
            </value>
            <value>
                <fullName>Vietnam</fullName>
            </value>
            <value>
                <fullName>Cook Islands</fullName>
            </value>
            <value>
                <fullName>Fiji</fullName>
            </value>
            <value>
                <fullName>Kiribati</fullName>
            </value>
            <value>
                <fullName>Nauru</fullName>
            </value>
            <value>
                <fullName>PNG</fullName>
            </value>
            <value>
                <fullName>Samoa</fullName>
            </value>
            <value>
                <fullName>Solomon Islands</fullName>
            </value>
            <value>
                <fullName>Timor-Leste</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/T1_Industry__c.field-meta.xml
<CustomField>
    <fullName>T1_Industry__c</fullName>
    <label>Segment</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Vertical_Market__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>State Government</fullName>
            </value>
            <value>
                <fullName>Federal Government</fullName>
            </value>
            <value>
                <fullName>Central Government</fullName>
            </value>
            <value>
                <fullName>Other Government</fullName>
            </value>
            <value>
                <fullName>Local Government</fullName>
            </value>
            <value>
                <fullName>Other Local Government</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Higher Education - University</fullName>
            </value>
            <value>
                <fullName>VET Sector - TAFE/Polytech</fullName>
            </value>
            <value>
                <fullName>Private Training Provider</fullName>
            </value>
            <value>
                <fullName>Education Research Institution</fullName>
            </value>
            <value>
                <fullName>K-12/Schools</fullName>
            </value>
            <value>
                <fullName>Other Education</fullName>
            </value>
            <value>
                <fullName>Banks, Credit Unions, Building Societies</fullName>
            </value>
            <value>
                <fullName>Wealth Management (Funds and Financial Advisors)</fullName>
            </value>
            <value>
                <fullName>Superannuation</fullName>
            </value>
            <value>
                <fullName>Insurance</fullName>
            </value>
            <value>
                <fullName>Property Investment</fullName>
            </value>
            <value>
                <fullName>Other Finance</fullName>
            </value>
            <value>
                <fullName>Aged, Disability and Community Care</fullName>
            </value>
            <value>
                <fullName>Community Services</fullName>
            </value>
            <value>
                <fullName>Health</fullName>
            </value>
            <value>
                <fullName>Housing</fullName>
            </value>
            <value>
                <fullName>Other Utilities</fullName>
            </value>
            <value>
                <fullName>Natural Resources Management</fullName>
            </value>
            <value>
                <fullName>Project-centric, Engineering and Mining</fullName>
            </value>
            <value>
                <fullName>Membership-based</fullName>
            </value>
            <value>
                <fullName>Media, Entertainment, Events and Facilities Managers</fullName>
            </value>
            <value>
                <fullName>Corporate</fullName>
            </value>
            <value>
                <fullName>Other Corporate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Vertical_Market__c.field-meta.xml
<CustomField>
    <fullName>Vertical_Market__c</fullName>
    <label>Industry/Vertical</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Education</fullName>
                <color>#0B6FCE</color>
                <label>Education</label>
            </value>
            <value>
                <fullName>Financial Services</fullName>
                <color>#78C953</color>
                <label>Financial Services</label>
            </value>
            <value>
                <fullName>Government</fullName>
                <color>#E27001</color>
                <label>Government</label>
            </value>
            <value>
                <fullName>Health and Community Services</fullName>
                <color>#A845DC</color>
                <label>Health and Community Services</label>
            </value>
            <value>
                <fullName>Asset Intensive</fullName>
                <color>#999999</color>
                <label>Asset Intensive</label>
            </value>
            <value>
                <fullName>Project Intensive</fullName>
                <color>#9999FF</color>
                <label>Project Intensive</label>
            </value>
            <value>
                <fullName>Local Government</fullName>
                <color>#F3D904</color>
                <label>Local Government</label>
            </value>
            <value>
                <fullName>Corporate</fullName>
                <color>#66E9BD</color>
                <label>Corporate</label>
            </value>
            <value>
                <fullName>Finance Adjustment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/ConsultingS_Required__c.field-meta.xml
<CustomField>
    <fullName>ConsultingS_Required__c</fullName>
    <label>Consulting Required</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
                <default>true</default>
                <label>Yes</label>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Include_in_Forecast__c.field-meta.xml
<CustomField>
    <fullName>Include_in_Forecast__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Opportunities that have a 50% chance of closing that particular quarter</inlineHelpText>
    <label>Upside</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Overview__c.field-meta.xml
<CustomField>
    <fullName>Overview__c</fullName>
    <inlineHelpText>Please provide a brief overview of the opportunity</inlineHelpText>
    <label>Overview</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Project_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Project_Start_Date__c</fullName>
    <inlineHelpText>The Project start date should be 8 weeks after the opportunity close date if consulting services is required.</inlineHelpText>
    <label>Project Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <formula>TEXT( Account.Region__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Region</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <description>Opportunity Start Date</description>
    <inlineHelpText>Opportunity Start Date</inlineHelpText>
    <label>Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/T1_Industry__c.field-meta.xml
<CustomField>
    <fullName>T1_Industry__c</fullName>
    <formula>TEXT( Account.T1_Industry__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Segment</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Vertical_Market__c.field-meta.xml
<CustomField>
    <fullName>Vertical_Market__c</fullName>
    <formula>TEXT(Account.Vertical_Market__c )</formula>
    <label>Industry/Vertical</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Win_Price_Customer_Budget__c.field-meta.xml
<CustomField>
    <fullName>Win_Price_Customer_Budget__c</fullName>
    <inlineHelpText>Total budget: TechOne licence fees and consulting</inlineHelpText>
    <label>Win Price / Customer Budget</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Product_or_Module__c.field-meta.xml
<CustomField>
    <fullName>Product_or_Module__c</fullName>
    <label>Hierarchy Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Product</fullName>
            </value>
            <value>
                <fullName>Module</fullName>
                <default>true</default>
                <label>Module</label>
            </value>
            <value>
                <fullName>Solution</fullName>
            </value>
            <value>
                <fullName>Service Pack</fullName>
            </value>
            <value>
                <fullName>AMS Program</fullName>
            </value>
            <value>
                <fullName>Saas Platform</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/TestDataBuilder.cls
@isTest
public class TestDataBuilder{
    public static Account createAccountTest(Integer i){
        Account acc = new Account();
        acc.Name = 'Test Account ' + i;
        acc.Type = 'Prospect';
        acc.Vertical_Market__c = 'Education';
        acc.T1_Industry__c = 'Private Training Provider';
        acc.CountryArea__c = 'Australia';
        acc.Region__c = 'ACT';
        acc.CurrencyIsoCode = 'AUD';
        return acc;
    }

    public static Opportunity createOpportunityTest(Integer i, Account acc, String userCurrencyIsoCode, String stageName, Decimal amount /*String recType*/){
        
        ID RType = RecordTypeUtil.getRecordTypeIdByName(Opportunity.SObjectType, 'Licence Fee');
        
        Opportunity opp = new Opportunity();
        opp.RecordTypeId = RType;
        opp.Name = 'Opportunity ' + i;
        opp.AccountId = acc.Id;
        opp.Type = 'Existing Business';  
        opp.Start_Date__c = date.today();      
        opp.CloseDate = date.today();
        opp.StageName = stageName;
        opp.LeadSource = 'Web';
        opp.Amount = amount;
        opp.CurrencyIsoCode = userCurrencyIsoCode;
        opp.Overview__c = 'Test Overview ' + i;
        opp.Include_in_Forecast__c = true;
        opp.ConsultingS_Required__c = 'Yes';
        opp.Project_Start_Date__c = date.today();

        return opp;
    }
    
    public static List<Opportunity> createOpportunities(integer noOfRecords, Boolean applyDML, Id recordTypeId){
        List<Opportunity> opps = new List<Opportunity>();
        for(integer i=0;i<noOfRecords;i++){
            Opportunity oNewOpp= new Opportunity();
            oNewOpp.name= 'Opp'+i;
            oNewOpp.closedate = date.newinstance(2035,11,11);
            oNewOpp.stagename ='1 - Discovery';
            oNewOpp.Overview__c = 'Test Pusher';
            oNewOpp.Type='New Business';
            oNewOpp.LeadSource = 'Web';
            oNewOpp.Win_Price_Customer_Budget__c=10000;
            oNewOpp.RecordTypeId =recordTypeId;
            opps.add(oNewOpp);
        }
        if(applyDML){
            insert opps;
        }
        return opps;
    }


    public static Product2 initializeProduct( String name, String family, String pOrM, Boolean applyDML)
    {
        Product2 prod = new Product2();
        prod.Name = name;
        prod.Family = family;
        prod.CurrencyIsoCode = 'AUD';
        prod.Product_or_Module__c = pOrM;
        prod.IsActive=true;
        if(applyDML){
            insert prod;
        }
        return prod;
    }

    public static PricebookEntry initializeProductPricebook(Id pbId, Id prodId, Boolean applyDML)
    {
        PricebookEntry pbe = new PricebookEntry();
        pbe.UseStandardPrice = false;
        pbe.Pricebook2Id=pbId;
        pbe.Product2Id=prodId;
        pbe.IsActive=true;
        pbe.UnitPrice=2.0;
        if(applyDML){
            insert pbe;
        }
        return pbe;
    }
  //  public static void createSolutionProductMatrix() {
  //      Solution_Product_Matrix__c spm1 = new Solution_Product_Matrix__c(name = 'spm1', Solution__c = 'OneCareXX', Product__c = 'Financials', Weight__c = 50);
  //      Solution_Product_Matrix__c spm2 = new Solution_Product_Matrix__c(name = 'spm2', Solution__c = 'OneCareXX', Product__c = 'Enterprise Case Receipting', Weight__c = 30);
  //      Solution_Product_Matrix__c spm3 = new Solution_Product_Matrix__c(name = 'spm3', Solution__c = 'OneCareXX', Product__c = 'Student Management', Weight__c = 15);
  //      Solution_Product_Matrix__c spm4 = new Solution_Product_Matrix__c(name = 'spm4', Solution__c = 'OneCareXX', Product__c = 'Property And Rating', Weight__c = 5);
  //      insert spm1;
  //      insert spm2;
  //      insert spm3;
  //      insert spm4;
  //  }

    public static List<Account> createAccounts(integer noOfRecords, Boolean applyDML){
        List<Account> accs = new List<Account>();
        for(integer i=0;i<noOfRecords;i++) {
            Account acc = new Account();
            acc.Name = 'Test Account ' + i;
            acc.Type = 'Prospect';
            acc.Vertical_Market__c = 'Education';
            acc.T1_Industry__c = 'Private Training Provider';
            acc.CountryArea__c = 'Australia';
            acc.Region__c = 'ACT';
            accs.add(acc);
        }
        if(applyDML){
            insert accs;
        }
        return accs;
    }
}