unpackaged/main/default/objects/Account/fields/CountryArea__c.field-meta.xml
<CustomField>
    <fullName>CountryArea__c</fullName>
    <label>Country/Area</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>New Zealand</fullName>
            </value>
            <value>
                <fullName>United Kingdom</fullName>
            </value>
            <value>
                <fullName>Asia</fullName>
            </value>
            <value>
                <fullName>Pacific</fullName>
            </value>
            <value>
                <fullName>Distributors</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Rate_Day__c.field-meta.xml
<CustomField>
    <fullName>Rate_Day__c</fullName>
    <description>Special Consulting Rate per Day</description>
    <inlineHelpText>Special Consulting Rate per Day</inlineHelpText>
    <label>Consulting Rate/Day</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>CountryArea__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>ACT</fullName>
            </value>
            <value>
                <fullName>New South Wales</fullName>
            </value>
            <value>
                <fullName>Northern Territory</fullName>
            </value>
            <value>
                <fullName>Queensland</fullName>
            </value>
            <value>
                <fullName>South Australia</fullName>
            </value>
            <value>
                <fullName>Tasmania</fullName>
            </value>
            <value>
                <fullName>Victoria</fullName>
            </value>
            <value>
                <fullName>Western Australia</fullName>
            </value>
            <value>
                <fullName>New Zealand North</fullName>
            </value>
            <value>
                <fullName>New Zealand South</fullName>
            </value>
            <value>
                <fullName>UK PS South</fullName>
            </value>
            <value>
                <fullName>UK PS Central</fullName>
            </value>
            <value>
                <fullName>UK HE</fullName>
            </value>
            <value>
                <fullName>UK North &amp; Scotland</fullName>
            </value>
            <value>
                <fullName>UK Other</fullName>
                <label>UK Other (USD)</label>
            </value>
            <value>
                <fullName>Indonesia</fullName>
            </value>
            <value>
                <fullName>Malaysia</fullName>
            </value>
            <value>
                <fullName>Mongolia</fullName>
            </value>
            <value>
                <fullName>Philippines</fullName>
            </value>
            <value>
                <fullName>Singapore</fullName>
            </value>
            <value>
                <fullName>Sri Lanka</fullName>
            </value>
            <value>
                <fullName>Vietnam</fullName>
            </value>
            <value>
                <fullName>Cook Islands</fullName>
            </value>
            <value>
                <fullName>Fiji</fullName>
            </value>
            <value>
                <fullName>Kiribati</fullName>
            </value>
            <value>
                <fullName>Nauru</fullName>
            </value>
            <value>
                <fullName>PNG</fullName>
            </value>
            <value>
                <fullName>Samoa</fullName>
            </value>
            <value>
                <fullName>Solomon Islands</fullName>
            </value>
            <value>
                <fullName>Timor-Leste</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/T1_Industry__c.field-meta.xml
<CustomField>
    <fullName>T1_Industry__c</fullName>
    <label>Segment</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Vertical_Market__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>State Government</fullName>
            </value>
            <value>
                <fullName>Federal Government</fullName>
            </value>
            <value>
                <fullName>Central Government</fullName>
            </value>
            <value>
                <fullName>Other Government</fullName>
            </value>
            <value>
                <fullName>Local Government</fullName>
            </value>
            <value>
                <fullName>Other Local Government</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Higher Education - University</fullName>
            </value>
            <value>
                <fullName>VET Sector - TAFE/Polytech</fullName>
            </value>
            <value>
                <fullName>Private Training Provider</fullName>
            </value>
            <value>
                <fullName>Education Research Institution</fullName>
            </value>
            <value>
                <fullName>K-12/Schools</fullName>
            </value>
            <value>
                <fullName>Other Education</fullName>
            </value>
            <value>
                <fullName>Banks, Credit Unions, Building Societies</fullName>
            </value>
            <value>
                <fullName>Wealth Management (Funds and Financial Advisors)</fullName>
            </value>
            <value>
                <fullName>Superannuation</fullName>
            </value>
            <value>
                <fullName>Insurance</fullName>
            </value>
            <value>
                <fullName>Property Investment</fullName>
            </value>
            <value>
                <fullName>Other Finance</fullName>
            </value>
            <value>
                <fullName>Aged, Disability and Community Care</fullName>
            </value>
            <value>
                <fullName>Community Services</fullName>
            </value>
            <value>
                <fullName>Health</fullName>
            </value>
            <value>
                <fullName>Housing</fullName>
            </value>
            <value>
                <fullName>Other Utilities</fullName>
            </value>
            <value>
                <fullName>Natural Resources Management</fullName>
            </value>
            <value>
                <fullName>Project-centric, Engineering and Mining</fullName>
            </value>
            <value>
                <fullName>Membership-based</fullName>
            </value>
            <value>
                <fullName>Media, Entertainment, Events and Facilities Managers</fullName>
            </value>
            <value>
                <fullName>Corporate</fullName>
            </value>
            <value>
                <fullName>Other Corporate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Vertical_Market__c.field-meta.xml
<CustomField>
    <fullName>Vertical_Market__c</fullName>
    <label>Industry/Vertical</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Education</fullName>
                <color>#0B6FCE</color>
                <label>Education</label>
            </value>
            <value>
                <fullName>Financial Services</fullName>
                <color>#78C953</color>
                <label>Financial Services</label>
            </value>
            <value>
                <fullName>Government</fullName>
                <color>#E27001</color>
                <label>Government</label>
            </value>
            <value>
                <fullName>Health and Community Services</fullName>
                <color>#A845DC</color>
                <label>Health and Community Services</label>
            </value>
            <value>
                <fullName>Asset Intensive</fullName>
                <color>#999999</color>
                <label>Asset Intensive</label>
            </value>
            <value>
                <fullName>Project Intensive</fullName>
                <color>#9999FF</color>
                <label>Project Intensive</label>
            </value>
            <value>
                <fullName>Local Government</fullName>
                <color>#F3D904</color>
                <label>Local Government</label>
            </value>
            <value>
                <fullName>Corporate</fullName>
                <color>#66E9BD</color>
                <label>Corporate</label>
            </value>
            <value>
                <fullName>Finance Adjustment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Employee_Classification__c.field-meta.xml
<CustomField>
    <fullName>Employee_Classification__c</fullName>
    <label>Employee Classification</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Bid Manager</fullName>
            </value>
            <value>
                <fullName>Business Development Manager</fullName>
            </value>
            <value>
                <fullName>Consultant</fullName>
            </value>
            <value>
                <fullName>Consulting Director</fullName>
            </value>
            <value>
                <fullName>Customer Account Manager</fullName>
            </value>
            <value>
                <fullName>Customer Development Manager</fullName>
            </value>
            <value>
                <fullName>Executive</fullName>
            </value>
            <value>
                <fullName>General Manager</fullName>
            </value>
            <value>
                <fullName>Marketing Partner</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Practice Lead</fullName>
            </value>
            <value>
                <fullName>Presales Consultant</fullName>
            </value>
            <value>
                <fullName>Product Customer Service Manager</fullName>
            </value>
            <value>
                <fullName>Regional Manager</fullName>
            </value>
            <value>
                <fullName>Sales Administrator</fullName>
            </value>
            <value>
                <fullName>Sales Operations</fullName>
            </value>
            <value>
                <fullName>Solution Manager</fullName>
            </value>
            <value>
                <fullName>Telemarketing Partner</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <description>Region of the account to use in List View/Reports etc</description>
    <formula>TEXT(Account.Region__c)</formula>
    <label>Region</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Vertical_Market__c.field-meta.xml
<CustomField>
    <fullName>Vertical_Market__c</fullName>
    <formula>TEXT(Account.Vertical_Market__c)</formula>
    <label>Industry/Vertical</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/recordTypes/Other.recordType-meta.xml
<RecordType>
    <fullName>Other</fullName>
    <active>true</active>
    <description>Partner/Associate/Consultant/Other</description>
    <label>Other</label>
</RecordType>

unpackaged/main/default/objects/Opportunity/fields/Overview__c.field-meta.xml
<CustomField>
    <fullName>Overview__c</fullName>
    <inlineHelpText>Please provide a brief overview of the opportunity</inlineHelpText>
    <label>Overview</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <formula>TEXT( Account.Region__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Region</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/T1_Industry__c.field-meta.xml
<CustomField>
    <fullName>T1_Industry__c</fullName>
    <formula>TEXT( Account.T1_Industry__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Segment</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Vertical_Market__c.field-meta.xml
<CustomField>
    <fullName>Vertical_Market__c</fullName>
    <formula>TEXT(Account.Vertical_Market__c )</formula>
    <label>Industry/Vertical</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Win_Price_Customer_Budget__c.field-meta.xml
<CustomField>
    <fullName>Win_Price_Customer_Budget__c</fullName>
    <inlineHelpText>Total budget: TechOne licence fees and consulting</inlineHelpText>
    <label>Win Price / Customer Budget</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Service_Only_Consulting_Request__c/Service_Only_Consulting_Request__c.object-meta.xml
<CustomObject>
    <description>Resource/Rate information for Service Only/Consulting Request Opportunity type</description>
    <label>Service Only/Consulting Request</label>
    <nameField>
        <displayFormat>R-{0000000}</displayFormat>
        <label>Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Only/Consulting Request</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Service_Only_Consulting_Request__c/fields/No_Days__c.field-meta.xml
<CustomField>
    <fullName>No_Days__c</fullName>
    <label>No. Days</label>
    <precision>12</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Service_Only_Consulting_Request__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Resource</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Technology One Employee</value>
        </filterItems>
        <infoMessage>Search Technology One Employees</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Service Only/Consulting Request</relationshipLabel>
    <relationshipName>Service_Only_Consulting_Request</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/ConsultingSurveyResponseTriggerTest.cls
@isTest
public class ConsultingSurveyResponseTriggerTest {

   public static testmethod void testConsultingSurveyResponseTrigger() {
       //Create an account    
        Account acc= new Account(name= 'TechnologyOne');
        acc.type = 'Customer';
        acc.CountryArea__c = 'Australia';
        acc.Vertical_Market__c = 'Education';
        acc.T1_Industry__c = 'Other Education';
        acc.Region__c = 'Queensland';
        acc.CurrencyIsoCode = 'AUD';
        insert acc;

       //Create an Opportunity
        Schema.DescribeSObjectResult cfrSchema = Schema.SObjectType.Opportunity; 
        Map<String,Schema.RecordTypeInfo> OpportunityRecordTypeInfo = cfrSchema.getRecordTypeInfosByName(); 
        Id rtId = OpportunityRecordTypeInfo .get('Services Only / Consulting request').getRecordTypeId();  
            
        Opportunity o = new Opportunity();
        o.RecordTypeId = rtid;
        o.Name = 'Opportunity Test 1';
        o.AccountId = acc.Id;
        o.StageName = 'Stage 8 - Preferred Vendor';
        o.CurrencyIsoCode = 'AUD';
        o.CloseDate = date.today()+30;
        
        o.Overview__c = 'ABCD'; o.type='New Business';   
        o.LeadSource = 'Web';
        o.Win_Price_Customer_Budget__c=10000;
        insert o;
       
       //Create a Contact 
        Schema.DescribeSObjectResult cSchema = Schema.SObjectType.Contact; 
        Map<String,Schema.RecordTypeInfo> ContactRecordTypeInfo = cSchema.getRecordTypeInfosByName(); 
        Id cId = ContactRecordTypeInfo.get('Technology One Employee').getRecordTypeId();  
   
       Contact c = new Contact(firstname='Consulting', lastname='Management') ;
       c.AccountId = acc.id;
       c.Employee_Classification__c = 'Other';
       c.Title = 'Consultant';
       c.RecordTypeId = cId;
	   insert c; 	
             
       //Create a Consulting Request
       Service_Only_Consulting_Request__c sc = new Service_Only_Consulting_Request__c();
       sc.Resource__c = c.Id;
       sc.No_Days__c = 2;
       sc.Rate_Day__c = 1880;
       sc.Opportunity__c = o.Id;
       insert sc;
                    
       System.Test.startTest();       
       // Create a Survey_Response_Opportunity record
        Survey_Response_Opportunity__c s = new Survey_Response_Opportunity__c (Name='T1 Consulting Survey');
        s.Opportunity_Number__c = o.Id;
        s.Experience_Rating__c = 5;
        s.Comment__c = 'Excellent Service';
        s.Improvement__c = 'Communications';
        insert s;
           Survey_Response_Opportunity__c updatedS = [SELECT Name,Experience_Rating__c,Comment__c FROM
           Survey_Response_Opportunity__c WHERE Id = : s.Id];
           System.assertEquals('T1 Consulting Survey', updatedS.Name);      
           System.assertEquals(5, updatedS.Experience_Rating__c);
           System.assertEquals('Excellent Service', updatedS.Comment__c);
    
       System.Test.stopTest();
   }
    
}