unpackaged/main/default/objects/Account/fields/CountryArea__c.field-meta.xml
<CustomField>
    <fullName>CountryArea__c</fullName>
    <label>Country/Area</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>New Zealand</fullName>
            </value>
            <value>
                <fullName>United Kingdom</fullName>
            </value>
            <value>
                <fullName>Asia</fullName>
            </value>
            <value>
                <fullName>Pacific</fullName>
            </value>
            <value>
                <fullName>Distributors</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>CountryArea__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>ACT</fullName>
            </value>
            <value>
                <fullName>New South Wales</fullName>
            </value>
            <value>
                <fullName>Northern Territory</fullName>
            </value>
            <value>
                <fullName>Queensland</fullName>
            </value>
            <value>
                <fullName>South Australia</fullName>
            </value>
            <value>
                <fullName>Tasmania</fullName>
            </value>
            <value>
                <fullName>Victoria</fullName>
            </value>
            <value>
                <fullName>Western Australia</fullName>
            </value>
            <value>
                <fullName>New Zealand North</fullName>
            </value>
            <value>
                <fullName>New Zealand South</fullName>
            </value>
            <value>
                <fullName>UK PS South</fullName>
            </value>
            <value>
                <fullName>UK PS Central</fullName>
            </value>
            <value>
                <fullName>UK HE</fullName>
            </value>
            <value>
                <fullName>UK North &amp; Scotland</fullName>
            </value>
            <value>
                <fullName>UK Other</fullName>
                <label>UK Other (USD)</label>
            </value>
            <value>
                <fullName>Indonesia</fullName>
            </value>
            <value>
                <fullName>Malaysia</fullName>
            </value>
            <value>
                <fullName>Mongolia</fullName>
            </value>
            <value>
                <fullName>Philippines</fullName>
            </value>
            <value>
                <fullName>Singapore</fullName>
            </value>
            <value>
                <fullName>Sri Lanka</fullName>
            </value>
            <value>
                <fullName>Vietnam</fullName>
            </value>
            <value>
                <fullName>Cook Islands</fullName>
            </value>
            <value>
                <fullName>Fiji</fullName>
            </value>
            <value>
                <fullName>Kiribati</fullName>
            </value>
            <value>
                <fullName>Nauru</fullName>
            </value>
            <value>
                <fullName>PNG</fullName>
            </value>
            <value>
                <fullName>Samoa</fullName>
            </value>
            <value>
                <fullName>Solomon Islands</fullName>
            </value>
            <value>
                <fullName>Timor-Leste</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/T1_Industry__c.field-meta.xml
<CustomField>
    <fullName>T1_Industry__c</fullName>
    <label>Segment</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Vertical_Market__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>State Government</fullName>
            </value>
            <value>
                <fullName>Federal Government</fullName>
            </value>
            <value>
                <fullName>Central Government</fullName>
            </value>
            <value>
                <fullName>Other Government</fullName>
            </value>
            <value>
                <fullName>Local Government</fullName>
            </value>
            <value>
                <fullName>Other Local Government</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Higher Education - University</fullName>
            </value>
            <value>
                <fullName>VET Sector - TAFE/Polytech</fullName>
            </value>
            <value>
                <fullName>Private Training Provider</fullName>
            </value>
            <value>
                <fullName>Education Research Institution</fullName>
            </value>
            <value>
                <fullName>K-12/Schools</fullName>
            </value>
            <value>
                <fullName>Other Education</fullName>
            </value>
            <value>
                <fullName>Banks, Credit Unions, Building Societies</fullName>
            </value>
            <value>
                <fullName>Wealth Management (Funds and Financial Advisors)</fullName>
            </value>
            <value>
                <fullName>Superannuation</fullName>
            </value>
            <value>
                <fullName>Insurance</fullName>
            </value>
            <value>
                <fullName>Property Investment</fullName>
            </value>
            <value>
                <fullName>Other Finance</fullName>
            </value>
            <value>
                <fullName>Aged, Disability and Community Care</fullName>
            </value>
            <value>
                <fullName>Community Services</fullName>
            </value>
            <value>
                <fullName>Health</fullName>
            </value>
            <value>
                <fullName>Housing</fullName>
            </value>
            <value>
                <fullName>Other Utilities</fullName>
            </value>
            <value>
                <fullName>Natural Resources Management</fullName>
            </value>
            <value>
                <fullName>Project-centric, Engineering and Mining</fullName>
            </value>
            <value>
                <fullName>Membership-based</fullName>
            </value>
            <value>
                <fullName>Media, Entertainment, Events and Facilities Managers</fullName>
            </value>
            <value>
                <fullName>Corporate</fullName>
            </value>
            <value>
                <fullName>Other Corporate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Vertical_Market__c.field-meta.xml
<CustomField>
    <fullName>Vertical_Market__c</fullName>
    <label>Industry/Vertical</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Education</fullName>
                <color>#0B6FCE</color>
                <label>Education</label>
            </value>
            <value>
                <fullName>Financial Services</fullName>
                <color>#78C953</color>
                <label>Financial Services</label>
            </value>
            <value>
                <fullName>Government</fullName>
                <color>#E27001</color>
                <label>Government</label>
            </value>
            <value>
                <fullName>Health and Community Services</fullName>
                <color>#A845DC</color>
                <label>Health and Community Services</label>
            </value>
            <value>
                <fullName>Asset Intensive</fullName>
                <color>#999999</color>
                <label>Asset Intensive</label>
            </value>
            <value>
                <fullName>Project Intensive</fullName>
                <color>#9999FF</color>
                <label>Project Intensive</label>
            </value>
            <value>
                <fullName>Local Government</fullName>
                <color>#F3D904</color>
                <label>Local Government</label>
            </value>
            <value>
                <fullName>Corporate</fullName>
                <color>#66E9BD</color>
                <label>Corporate</label>
            </value>
            <value>
                <fullName>Finance Adjustment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/ConsultingS_Required__c.field-meta.xml
<CustomField>
    <fullName>ConsultingS_Required__c</fullName>
    <label>Consulting Required</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
                <default>true</default>
                <label>Yes</label>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Include_in_Forecast__c.field-meta.xml
<CustomField>
    <fullName>Include_in_Forecast__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Opportunities that have a 50% chance of closing that particular quarter</inlineHelpText>
    <label>Upside</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Overview__c.field-meta.xml
<CustomField>
    <fullName>Overview__c</fullName>
    <inlineHelpText>Please provide a brief overview of the opportunity</inlineHelpText>
    <label>Overview</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Project_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Project_Start_Date__c</fullName>
    <inlineHelpText>The Project start date should be 8 weeks after the opportunity close date if consulting services is required.</inlineHelpText>
    <label>Project Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <formula>TEXT( Account.Region__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Region</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <description>Opportunity Start Date</description>
    <inlineHelpText>Opportunity Start Date</inlineHelpText>
    <label>Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/T1_Industry__c.field-meta.xml
<CustomField>
    <fullName>T1_Industry__c</fullName>
    <formula>TEXT( Account.T1_Industry__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Segment</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Vertical_Market__c.field-meta.xml
<CustomField>
    <fullName>Vertical_Market__c</fullName>
    <formula>TEXT(Account.Vertical_Market__c )</formula>
    <label>Industry/Vertical</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/TestDataBuilder_Test.cls
@isTest(SeeAllData=true)
public class TestDataBuilder_Test {
    
       static testmethod void createAccountTest(){
        Account acc = new Account();
        acc.Name = 'Test Account 1';
        acc.Type = 'Prospect';
        acc.Vertical_Market__c = 'Education';
        acc.T1_Industry__c = 'Private Training Provider';
        acc.CountryArea__c = 'Australia';
        acc.Region__c = 'ACT';
        acc.CurrencyIsoCode = 'AUD';

       }
    
        static testmethod void createOpportunityTest(){
        Account acc= TestDataBuilder.createAccounts(1, true)[0];     
        ID RType = RecordTypeUtil.getRecordTypeIdByName(Opportunity.SObjectType, 'Licence Fee');
        Opportunity opp = new Opportunity();
        opp.RecordTypeId = RType;
        opp.Name = 'Opportunity 1';
          
        opp.AccountId = acc.Id;
        opp.Type = 'Existing Business';  
        opp.Start_Date__c = date.today();      
        opp.CloseDate = date.today();
        opp.StageName = '1 - Discovery';
        opp.LeadSource = 'Web';
        opp.Amount = 2000;
        opp.CurrencyIsoCode = 'AUD';
        opp.Overview__c = 'Test Overview ' + 1;
        opp.Include_in_Forecast__c = true;
        opp.ConsultingS_Required__c = 'Yes';
        opp.Project_Start_Date__c = date.today();
            
    }
    
    
    
}