unpackaged/main/default/objects/Account/fields/CountryArea__c.field-meta.xml
<CustomField>
    <fullName>CountryArea__c</fullName>
    <label>Country/Area</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>New Zealand</fullName>
            </value>
            <value>
                <fullName>United Kingdom</fullName>
            </value>
            <value>
                <fullName>Asia</fullName>
            </value>
            <value>
                <fullName>Pacific</fullName>
            </value>
            <value>
                <fullName>Distributors</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>CountryArea__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>ACT</fullName>
            </value>
            <value>
                <fullName>New South Wales</fullName>
            </value>
            <value>
                <fullName>Northern Territory</fullName>
            </value>
            <value>
                <fullName>Queensland</fullName>
            </value>
            <value>
                <fullName>South Australia</fullName>
            </value>
            <value>
                <fullName>Tasmania</fullName>
            </value>
            <value>
                <fullName>Victoria</fullName>
            </value>
            <value>
                <fullName>Western Australia</fullName>
            </value>
            <value>
                <fullName>New Zealand North</fullName>
            </value>
            <value>
                <fullName>New Zealand South</fullName>
            </value>
            <value>
                <fullName>UK PS South</fullName>
            </value>
            <value>
                <fullName>UK PS Central</fullName>
            </value>
            <value>
                <fullName>UK HE</fullName>
            </value>
            <value>
                <fullName>UK North &amp; Scotland</fullName>
            </value>
            <value>
                <fullName>UK Other</fullName>
                <label>UK Other (USD)</label>
            </value>
            <value>
                <fullName>Indonesia</fullName>
            </value>
            <value>
                <fullName>Malaysia</fullName>
            </value>
            <value>
                <fullName>Mongolia</fullName>
            </value>
            <value>
                <fullName>Philippines</fullName>
            </value>
            <value>
                <fullName>Singapore</fullName>
            </value>
            <value>
                <fullName>Sri Lanka</fullName>
            </value>
            <value>
                <fullName>Vietnam</fullName>
            </value>
            <value>
                <fullName>Cook Islands</fullName>
            </value>
            <value>
                <fullName>Fiji</fullName>
            </value>
            <value>
                <fullName>Kiribati</fullName>
            </value>
            <value>
                <fullName>Nauru</fullName>
            </value>
            <value>
                <fullName>PNG</fullName>
            </value>
            <value>
                <fullName>Samoa</fullName>
            </value>
            <value>
                <fullName>Solomon Islands</fullName>
            </value>
            <value>
                <fullName>Timor-Leste</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/T1_Industry__c.field-meta.xml
<CustomField>
    <fullName>T1_Industry__c</fullName>
    <label>Segment</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Vertical_Market__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>State Government</fullName>
            </value>
            <value>
                <fullName>Federal Government</fullName>
            </value>
            <value>
                <fullName>Central Government</fullName>
            </value>
            <value>
                <fullName>Other Government</fullName>
            </value>
            <value>
                <fullName>Local Government</fullName>
            </value>
            <value>
                <fullName>Other Local Government</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Higher Education - University</fullName>
            </value>
            <value>
                <fullName>VET Sector - TAFE/Polytech</fullName>
            </value>
            <value>
                <fullName>Private Training Provider</fullName>
            </value>
            <value>
                <fullName>Education Research Institution</fullName>
            </value>
            <value>
                <fullName>K-12/Schools</fullName>
            </value>
            <value>
                <fullName>Other Education</fullName>
            </value>
            <value>
                <fullName>Banks, Credit Unions, Building Societies</fullName>
            </value>
            <value>
                <fullName>Wealth Management (Funds and Financial Advisors)</fullName>
            </value>
            <value>
                <fullName>Superannuation</fullName>
            </value>
            <value>
                <fullName>Insurance</fullName>
            </value>
            <value>
                <fullName>Property Investment</fullName>
            </value>
            <value>
                <fullName>Other Finance</fullName>
            </value>
            <value>
                <fullName>Aged, Disability and Community Care</fullName>
            </value>
            <value>
                <fullName>Community Services</fullName>
            </value>
            <value>
                <fullName>Health</fullName>
            </value>
            <value>
                <fullName>Housing</fullName>
            </value>
            <value>
                <fullName>Other Utilities</fullName>
            </value>
            <value>
                <fullName>Natural Resources Management</fullName>
            </value>
            <value>
                <fullName>Project-centric, Engineering and Mining</fullName>
            </value>
            <value>
                <fullName>Membership-based</fullName>
            </value>
            <value>
                <fullName>Media, Entertainment, Events and Facilities Managers</fullName>
            </value>
            <value>
                <fullName>Corporate</fullName>
            </value>
            <value>
                <fullName>Other Corporate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Vertical_Market__c.field-meta.xml
<CustomField>
    <fullName>Vertical_Market__c</fullName>
    <label>Industry/Vertical</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Education</fullName>
                <color>#0B6FCE</color>
                <label>Education</label>
            </value>
            <value>
                <fullName>Financial Services</fullName>
                <color>#78C953</color>
                <label>Financial Services</label>
            </value>
            <value>
                <fullName>Government</fullName>
                <color>#E27001</color>
                <label>Government</label>
            </value>
            <value>
                <fullName>Health and Community Services</fullName>
                <color>#A845DC</color>
                <label>Health and Community Services</label>
            </value>
            <value>
                <fullName>Asset Intensive</fullName>
                <color>#999999</color>
                <label>Asset Intensive</label>
            </value>
            <value>
                <fullName>Project Intensive</fullName>
                <color>#9999FF</color>
                <label>Project Intensive</label>
            </value>
            <value>
                <fullName>Local Government</fullName>
                <color>#F3D904</color>
                <label>Local Government</label>
            </value>
            <value>
                <fullName>Corporate</fullName>
                <color>#66E9BD</color>
                <label>Corporate</label>
            </value>
            <value>
                <fullName>Finance Adjustment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Case/fields/AwaitInfoFinalFollowupDue__c.field-meta.xml
<CustomField>
    <fullName>AwaitInfoFinalFollowupDue__c</fullName>
    <label>AwaitInfoFinalFollowupDue</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/AwaitInfoFirstFollowupDue__c.field-meta.xml
<CustomField>
    <fullName>AwaitInfoFirstFollowupDue__c</fullName>
    <description>The date the first followup is required if the user has not provided the requested information</description>
    <label>AwaitInfoFirstFollowupDue</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/AwaitInfoSecondFollowupDue__c.field-meta.xml
<CustomField>
    <fullName>AwaitInfoSecondFollowupDue__c</fullName>
    <label>AwaitInfoSecondFollowupDue</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Quote_Expiry__c.field-meta.xml
<CustomField>
    <fullName>Quote_Expiry__c</fullName>
    <description>The date/time the quote expires. This is calculated when the quote is sent. The value is used to automatically close the Case if there is no response from the customer.</description>
    <inlineHelpText>The date/time the quote expires, and the case closed if there is no response from the customer.</inlineHelpText>
    <label>Quote Expiry</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Quote_Reminder__c.field-meta.xml
<CustomField>
    <fullName>Quote_Reminder__c</fullName>
    <description>The date/time that a reminder will be sent to the customer if there has been no response to the intial quote. The field is calculated via workflow field update.</description>
    <inlineHelpText>The date/time that a reminder will be sent to the customer if there has been no response to the initial quote.</inlineHelpText>
    <label>Quote Reminder</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Job_Classification__c.field-meta.xml
<CustomField>
    <fullName>Job_Classification__c</fullName>
    <label>Job Classification</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Administration</fullName>
            </value>
            <value>
                <fullName>Asset Management</fullName>
            </value>
            <value>
                <fullName>Business Analyst</fullName>
            </value>
            <value>
                <fullName>Chairman / Board</fullName>
            </value>
            <value>
                <fullName>Chief Executive Officer / MD</fullName>
            </value>
            <value>
                <fullName>Chief Financial Officer</fullName>
            </value>
            <value>
                <fullName>Chief Information Officer</fullName>
            </value>
            <value>
                <fullName>Chief Operating Officer</fullName>
            </value>
            <value>
                <fullName>Corporate Performance Management</fullName>
            </value>
            <value>
                <fullName>Corporate Services Management</fullName>
            </value>
            <value>
                <fullName>Customer Service</fullName>
            </value>
            <value>
                <fullName>Education</fullName>
            </value>
            <value>
                <fullName>Finance Officer</fullName>
            </value>
            <value>
                <fullName>Finance - Senior</fullName>
            </value>
            <value>
                <fullName>Fleet Management</fullName>
            </value>
            <value>
                <fullName>Fundraising Manager</fullName>
            </value>
            <value>
                <fullName>Grants Management</fullName>
            </value>
            <value>
                <fullName>Head of Transformation</fullName>
            </value>
            <value>
                <fullName>Health</fullName>
            </value>
            <value>
                <fullName>Housing Manager</fullName>
            </value>
            <value>
                <fullName>HR - Junior</fullName>
            </value>
            <value>
                <fullName>HR - Senior</fullName>
            </value>
            <value>
                <fullName>HR Safety</fullName>
            </value>
            <value>
                <fullName>HR Training and Development</fullName>
            </value>
            <value>
                <fullName>IT - Junior &amp; Systems Admin</fullName>
            </value>
            <value>
                <fullName>IT - Senior</fullName>
            </value>
            <value>
                <fullName>Mayor and Councillors</fullName>
            </value>
            <value>
                <fullName>Ministerial Liaison</fullName>
            </value>
            <value>
                <fullName>Payroll - Junior</fullName>
            </value>
            <value>
                <fullName>Payroll - Senior</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <description>Region of the account to use in List View/Reports etc</description>
    <formula>TEXT(Account.Region__c)</formula>
    <label>Region</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Vertical_Market__c.field-meta.xml
<CustomField>
    <fullName>Vertical_Market__c</fullName>
    <formula>TEXT(Account.Vertical_Market__c)</formula>
    <label>Industry/Vertical</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/recordTypes/Other.recordType-meta.xml
<RecordType>
    <fullName>Other</fullName>
    <active>true</active>
    <description>Partner/Associate/Consultant/Other</description>
    <label>Other</label>
</RecordType>

unpackaged/main/default/classes/WorkDayCalcsTest.cls
@isTest(SeeAllData=True)
public class WorkDayCalcsTest{
    
    public static testmethod void testWorkDayCalcs() {


        Account ac = new Account();
        ac.type = 'Customer';
        ac.CountryArea__c = 'Australia';
        ac.Region__c = 'ACT';
        ac.Vertical_Market__c = 'Education';
        ac.T1_Industry__c = 'Other';
        ac.Name = 'Test Account';
        insert ac;
        
        Contact con = new Contact();
        con.AccountId = ac.id;
        con.LastName = 'Test Contact';
        con.Job_Classification__c = 'abc';
        con.title = 'Mr';
        insert con;
        
        BusinessHours bhs = [select id from BusinessHours where IsDefault=true];
        
        Case c = new Case();
        c.AccountId = ac.id;
        c.ContactId = con.id;
        c.CurrencyIsoCode = 'AUD';
        c.BusinessHoursId = bhs.id;
        c.Status = 'New';
        c.AwaitInfoFinalFollowupDue__c = datetime.newInstance(2014, 9, 15, 12, 30, 0);
        c.AwaitInfoFirstFollowupDue__c = datetime.newInstance(2014, 9, 15, 12, 30, 0);
        c.AwaitInfoSecondFollowupDue__c = datetime.newInstance(2014, 9, 15, 12, 30, 0);
        c.Quote_Reminder__c = datetime.newInstance(2014, 9, 15, 12, 30, 0);
        c.Quote_Expiry__c = datetime.newInstance(2014, 9, 15, 12, 30, 0);
        c.Description = 'A Description';
        c.Customer_Product__c = 'Financials (FIN)';
        c.Affected_Version__c = 'non-Production';
        c.Subject = 'A subject';
        c.Work_around_Details__c = 'A bit of text';
        c.CFunctional_Area__c = 'testing';
        c.Has_it_worked_before__c = 'No';
        c.Is_there_a_scalable_work_around__c = 'No';
        c.Steps_to_reproduce__c = '12345678910'; 
        insert c;
        
        c.AwaitInfoFinalFollowupDue__c = datetime.newInstance(2016, 1, 1, 12, 30, 1);
        c.AwaitInfoFirstFollowupDue__c = datetime.newInstance(2016, 1, 1, 12, 30, 1);
        c.AwaitInfoSecondFollowupDue__c = datetime.newInstance(2016, 1, 1, 12, 30, 1);
        update c;
        
        List<Holiday> hols = [Select StartTimeInMinutes, Name, ActivityDate From Holiday];
        
        c.AwaitInfoSecondFollowupDue__c = Workdaycalcs.calculateNthWorkingDay(date.newInstance(2016, 02, 01), 5, hols);
 
    }
    

}