unpackaged/main/default/objects/Account/fields/CPQ_Migration_Status__c.field-meta.xml
<CustomField>
    <fullName>CPQ_Migration_Status__c</fullName>
    <description>The state, on an Account, related to the migration of data from SRS format to CPQ format</description>
    <label>CPQ Migration Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
                <default>true</default>
                <label>Complete</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/T1_Control_Settings__c/T1_Control_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>TechnologyOne settings</description>
    <label>T1 Control Settings</label>
</CustomObject>

unpackaged/main/default/objects/T1_Control_Settings__c/fields/Bypass_Workflow__c.field-meta.xml
<CustomField>
    <fullName>Bypass_Workflow__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bypass Workflow</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/T1_Control_Settings__c/fields/Closed_Date_for_Archiving_Email__c.field-meta.xml
<CustomField>
    <fullName>Closed_Date_for_Archiving_Email__c</fullName>
    <description>This date will be used to select closed cases for email archive purposes.</description>
    <inlineHelpText>This date will be used to select closed cases for email archive purposes.</inlineHelpText>
    <label>Closed Date for Archiving Email</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/T1_Control_Settings__c/fields/Customer_Community_URL__c.field-meta.xml
<CustomField>
    <fullName>Customer_Community_URL__c</fullName>
    <label>Customer Community URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/T1_Control_Settings__c/fields/Employee_Community_URL__c.field-meta.xml
<CustomField>
    <fullName>Employee_Community_URL__c</fullName>
    <label>Employee Community URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/T1_Control_Settings__c/fields/Internal_URL__c.field-meta.xml
<CustomField>
    <fullName>Internal_URL__c</fullName>
    <label>Internal URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/BatchInitAccountCPQMigrationStatus.cls
global class BatchInitAccountCPQMigrationStatus implements 
   Database.Batchable<sObject>{

   /*
    execute this class via Developer Console with the following code
        BatchInitAccountCPQMigrationStatus c = new BatchInitAccountCPQMigrationStatus();
        Database.executeBatch(c);
   */
       
   global Database.QueryLocator start(Database.BatchableContext BC){
       // query hardcoded for ease
      String query = 'select id, CPQ_Migration_Status__c from Account where CPQ_Migration_Status__c = null ';
       
      if(Test.isRunningTest())
          query = 'select id, CPQ_Migration_Status__c from Account where CPQ_Migration_Status__c = null limit 100';
       
      return Database.getQueryLocator(query);
   }
   
   global void execute(
                Database.BatchableContext BC, 
                List<sObject> scope){

        // ensure triggers, workflow and validation rules are deactivated          
        T1_Control_Settings__c s = T1_Control_Settings__c.getInstance( UserInfo.GetUserID() ); //or Profile
        s.Bypass_Triggers__c = true;
        s.Bypass_Validation_Rules__c = true;
        s.Bypass_Workflow__c = true;
        s.Customer_Community_URL__c = '';
        s.Employee_Community_URL__c = '';
        s.Internal_URL__c = '';
        s.Closed_Date_for_Archiving_Email__c = null;
        upsert s;
                    
        // ensure triggers, workflow and validation rules are deactivated    
        if(s.Bypass_Triggers__c == false || s.Bypass_Validation_Rules__c == false || s.Bypass_Workflow__c == false) {
            system.debug('Triggers etc have not been bypassed. No processing has occurred. ');           
            return; 
        }

        list<Account> l_Accs = new list<Account>(); //list of accounts to be updated
        List<Account> accountList = scope;
        
        for (Account updAcc : accountList) {
            
              	updAcc.CPQ_Migration_Status__c = 'Not Started' ;
            	system.debug('After - ' + updAcc.CPQ_Migration_Status__c);
            	l_Accs.add(updAcc);                 
            
        }
        
        if (!l_Accs.isEmpty()) {
            system.debug('Accounts effected ' + l_Accs.size());
            // DML statement
            Database.SaveResult[] srList = Database.update(l_Accs, false);
            
            // Iterate through each returned result
            for (Database.SaveResult sr : srList) {
                if (!sr.isSuccess()) {
                    // Operation failed, so get all errors                
                    for(Database.Error err : sr.getErrors()) {
                        System.debug('The following error has occurred.');                    
                        System.debug(err.getStatusCode() + ': ' + err.getMessage());
                        System.debug('Fields that affected this error: ' + err.getFields());
                    }
                }
            }
        }
                    
   }

   global void finish(Database.BatchableContext BC){
       AsyncApexJob a = 
           [SELECT Id, Status, NumberOfErrors, JobItemsProcessed,
            TotalJobItems, CreatedBy.Email
            FROM AsyncApexJob WHERE Id =
            :BC.getJobId()];
       
       // Now reset the bypass values        
       T1_Control_Settings__c s = T1_Control_Settings__c.getInstance( UserInfo.GetUserID() ); //or Profile
       s.Bypass_Triggers__c = false;
       s.Bypass_Validation_Rules__c = false;
       s.Bypass_Workflow__c = false;
       s.Customer_Community_URL__c = '';
       s.Employee_Community_URL__c = '';
       s.Internal_URL__c = '';
       s.Closed_Date_for_Archiving_Email__c = null;
       upsert s;
                                
       // Send an email to the Apex job's submitter 
       //   notifying of job completion. 
       //   
       Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
       String[] toAddresses = new String[] {a.CreatedBy.Email};
       mail.setToAddresses(toAddresses);
       mail.setSubject('BatchInitAccountCPQMigrationStatus Status: ' + a.Status);
       mail.setPlainTextBody
       ('The batch Apex job processed ' + a.TotalJobItems +
       ' batches with '+ a.NumberOfErrors + ' failures.');
       Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
   }

       
       
}