unpackaged/main/default/objects/Case/fields/AwaitInfoFinalFollowupDue__c.field-meta.xml
<CustomField>
    <fullName>AwaitInfoFinalFollowupDue__c</fullName>
    <label>AwaitInfoFinalFollowupDue</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/AwaitInfoFirstFollowupDue__c.field-meta.xml
<CustomField>
    <fullName>AwaitInfoFirstFollowupDue__c</fullName>
    <description>The date the first followup is required if the user has not provided the requested information</description>
    <label>AwaitInfoFirstFollowupDue</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/AwaitInfoSecondFollowupDue__c.field-meta.xml
<CustomField>
    <fullName>AwaitInfoSecondFollowupDue__c</fullName>
    <label>AwaitInfoSecondFollowupDue</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Case_Age_In_Business_Hours__c.field-meta.xml
<CustomField>
    <fullName>Case_Age_In_Business_Hours__c</fullName>
    <description>The total case age in the customer&#39;s business hours from open to close.</description>
    <inlineHelpText>The total case age in the customer&#39;s business hours from open to close.</inlineHelpText>
    <label>Case Age (B/H)</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/CreatedDate_Mod__c.field-meta.xml
<CustomField>
    <fullName>CreatedDate_Mod__c</fullName>
    <description>A version of CreatedDate that allows us to manipulate data to suit. CreatedDate is a timestamp that we cannot change. This field is required to affect time-based processes. It is set in the after insert trigger of the Case.</description>
    <label>Created Date Modifiable</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Customer_Product__c.field-meta.xml
<CustomField>
    <fullName>Customer_Product__c</fullName>
    <label>Product Affected</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Applicable</fullName>
            </value>
            <value>
                <fullName>Asset Management (AM)</fullName>
            </value>
            <value>
                <fullName>Business Process Management (BPM)</fullName>
            </value>
            <value>
                <fullName>Corporate Performance Management (CPM)</fullName>
            </value>
            <value>
                <fullName>Customer Relationship Management (CRM)</fullName>
            </value>
            <value>
                <fullName>Enterprise Cash Receipting (ECR)</fullName>
            </value>
            <value>
                <fullName>Enterprise Content Management (ECM)</fullName>
            </value>
            <value>
                <fullName>Financials (FIN)</fullName>
            </value>
            <value>
                <fullName>Human Resource &amp; Payroll (HRP)</fullName>
            </value>
            <value>
                <fullName>Property &amp; Rating (P&amp;R)</fullName>
            </value>
            <value>
                <fullName>Spatial</fullName>
            </value>
            <value>
                <fullName>Student Management (SM)</fullName>
            </value>
            <value>
                <fullName>Supply Chain Management (SCM)</fullName>
            </value>
            <value>
                <fullName>Enterprise App Store</fullName>
            </value>
            <value>
                <fullName>Customer Community</fullName>
            </value>
            <value>
                <fullName>Technical</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Case/fields/Development_Status__c.field-meta.xml
<CustomField>
    <fullName>Development_Status__c</fullName>
    <label>Development Status</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Duration_to_Closed_Cal_Days__c.field-meta.xml
<CustomField>
    <fullName>Duration_to_Closed_Cal_Days__c</fullName>
    <description>The total work days to close the case. T1 daily business hours are calculated using the default Business Hours Monday Start to Finish times. Using the example of 7am to 7pm gives a 12 hour day for which a value of 0.5 equals 6 hours.</description>
    <inlineHelpText>The total work days to close the case. T1 daily business hours are calculated using the default Business Hours. Using the example of 7am to 7pm gives a 12 hour day for which a value of 0.5 equals 6 hours.</inlineHelpText>
    <label>Work Days to Close</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Duration_to_Resolved_Cal_Days__c.field-meta.xml
<CustomField>
    <fullName>Duration_to_Resolved_Cal_Days__c</fullName>
    <description>The total work days to resolve the case. T1 daily business hours are calculated using the default Business Hours Monday Start to Finish times. Using the example of 7am to 7pm gives a 12 hour day for which a value of 0.5 equals 6 hours.</description>
    <inlineHelpText>The total work days to resolve the case. T1 daily business hours are calculated using the default Business Hours. Using the example of 7am to 7pm gives a 12 hour day for which a value of 0.5 equals 6 hours.</inlineHelpText>
    <label>Work Days to Resolve</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Exit_Entitlement_Process__c.field-meta.xml
<CustomField>
    <fullName>Exit_Entitlement_Process__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used to determine when the Entitlement process will be exited. This is required to overcome an issue with Competing Milestones after a Case has been closed.</description>
    <label>Exit Entitlement Process</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Final_Resolution_MS_Warning__c.field-meta.xml
<CustomField>
    <fullName>Final_Resolution_MS_Warning__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Final Resolution Milestone Warning</description>
    <label>Final Resolution MS Warning</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Interim_Resolution_MS_Warning__c.field-meta.xml
<CustomField>
    <fullName>Interim_Resolution_MS_Warning__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Interim Resolution Milestone Warning</description>
    <label>Interim Resolution MS Warning</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Interim_Solution_Provided__c.field-meta.xml
<CustomField>
    <fullName>Interim_Solution_Provided__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Denotes whether an Interim Solution was provided. Affects the Update milestone behaviour.</description>
    <label>Interim Solution Provided</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Jira_Dev_Issue_Count__c.field-meta.xml
<CustomField>
    <fullName>Jira_Dev_Issue_Count__c</fullName>
    <description>The number of Jira Dev Issues linked to this Case.</description>
    <inlineHelpText>The number of Jira Dev Issues linked to this Case.</inlineHelpText>
    <label>Jira Dev Issue Count</label>
    <summaryForeignKey>Jira_Dev_Issue__c.Case__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Jira_Issue_No__c.field-meta.xml
<CustomField>
    <fullName>Jira_Issue_No__c</fullName>
    <label>Jira Issue No</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Last_Status_Change__c.field-meta.xml
<CustomField>
    <fullName>Last_Status_Change__c</fullName>
    <description>Stores the last time the status changed -- used by the Case Business Hours Tools package.</description>
    <label>Last Status Change</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/New_Customer_Attachment__c.field-meta.xml
<CustomField>
    <fullName>New_Customer_Attachment__c</fullName>
    <defaultValue>false</defaultValue>
    <label>New Customer Attachment</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/New_Customer_Email__c.field-meta.xml
<CustomField>
    <fullName>New_Customer_Email__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Make sure to uncheck this field when you have read the New Incoming Email</inlineHelpText>
    <label>New Customer Email</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/New_Portal_Case_Comment__c.field-meta.xml
<CustomField>
    <fullName>New_Portal_Case_Comment__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>A portal customer has added in a comment via the case comments or chatter</inlineHelpText>
    <label>New Portal Case Comment</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Priority_Has_Changed__c.field-meta.xml
<CustomField>
    <fullName>Priority_Has_Changed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Priority Has Changed</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Quote_Expiry__c.field-meta.xml
<CustomField>
    <fullName>Quote_Expiry__c</fullName>
    <description>The date/time the quote expires. This is calculated when the quote is sent. The value is used to automatically close the Case if there is no response from the customer.</description>
    <inlineHelpText>The date/time the quote expires, and the case closed if there is no response from the customer.</inlineHelpText>
    <label>Quote Expiry</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Quote_Reminder__c.field-meta.xml
<CustomField>
    <fullName>Quote_Reminder__c</fullName>
    <description>The date/time that a reminder will be sent to the customer if there has been no response to the intial quote. The field is calculated via workflow field update.</description>
    <inlineHelpText>The date/time that a reminder will be sent to the customer if there has been no response to the initial quote.</inlineHelpText>
    <label>Quote Reminder</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Resolved_Date__c.field-meta.xml
<CustomField>
    <fullName>Resolved_Date__c</fullName>
    <description>The date and time the Case Status was set to Resolved</description>
    <inlineHelpText>The date and time the Case Status was set to Resolved</inlineHelpText>
    <label>Date/Time Resolved</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Response_MS_Warning__c.field-meta.xml
<CustomField>
    <fullName>Response_MS_Warning__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Response Milestone Warning</description>
    <label>Response MS Warning</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Support_Case_Score__c.field-meta.xml
<CustomField>
    <fullName>Support_Case_Score__c</fullName>
    <description>To store the prioritisation of this case for Support</description>
    <label>Support Case Score</label>
    <precision>15</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Time_Await_Res_Alloc__c.field-meta.xml
<CustomField>
    <fullName>Time_Await_Res_Alloc__c</fullName>
    <description>The total work days between Awaiting Resource Allocation and Scheduled, calculated using the default business hours.</description>
    <inlineHelpText>The total work days to resource the case after the customer has approved the quote, calculated using the default business hours.</inlineHelpText>
    <label>Time Awaiting Resource Allocation</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Time_With_Customer__c.field-meta.xml
<CustomField>
    <fullName>Time_With_Customer__c</fullName>
    <defaultValue>0</defaultValue>
    <description>The time in the customer&#39;s business hours that this case spent in the hands of the customer.</description>
    <inlineHelpText>The time in the customer&#39;s business hours that this case spent in the hands of the customer.</inlineHelpText>
    <label>Time With Customer</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Update_MS_Warning__c.field-meta.xml
<CustomField>
    <fullName>Update_MS_Warning__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Update Milestone Warning</description>
    <label>Update MS Warning</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Case_Entitlements__c/Case_Entitlements__c.object-meta.xml
<CustomObject>
    <label>Case Entitlement</label>
    <nameField>
        <displayFormat>CE-{0000000}</displayFormat>
        <label>Case Entitlements Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Entitlements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Error_Log__c/Error_Log__c.object-meta.xml
<CustomObject>
    <label>Custom Error Log</label>
    <nameField>
        <displayFormat>E-{000000}</displayFormat>
        <label>Error Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Custom Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Stop_Status__c/Stop_Status__c.object-meta.xml
<CustomObject>
    <description>A case status in which the &quot;clock should stop,&quot; i.e. time calculated in business hours should not be added to the &quot;Time With Support&quot; field.</description>
    <label>Stop Status</label>
    <nameField>
        <label>Stop Status Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stop Statuses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/classes/CaseTriggerHandler.cls
/**
     Case Trigger Handler
 */
public class CaseTriggerHandler {

    public static BusinessHours defaultHours = [select Id, MondayStartTime, MondayEndTime from BusinessHours where IsDefault=true];
	public static Set<String> stopStatusSet = new Set<String>();
    public static Set<String> closedStatusSet = new Set<String>(); 
    public static List<Holiday> holidays=[Select StartTimeInMinutes, Name, ActivityDate From Holiday ]; 
	   
    static public void onAfterInsert(Case[] newCases) {
        SetCreatedDateMod(newCases);
        checkCasesForCreatingEntitlements( newCases ,null );
        
    }

    static public void onBeforeInsert(Case[] newCases) {
        loopKiller(newCases);
        initBusinessHoursAges(newCases);
    }

    static public void onBeforeUpdate(Case[] updatedCases, Map<ID, Case> oldMap) {
        // bypass all processing if Case Score update
        for(Case updatedCase : updatedCases) {
            Case beforeUpdate = oldMap.get(updatedCase.Id);
            if (updatedCase.Support_Case_Score__c != beforeUpdate.Support_Case_Score__c){
                return;
            }
        }
        resetMilestoneWarnings(updatedCases, oldMap);
        setDateToWorkDayOnCase(updatedCases, oldMap);
        calcTimeAwaitResAlloc(updatedCases, oldMap); // must be done prior to calcBusinessHoursAges as that function sets the Last Status Change date
        calcBusinessHoursAges(updatedCases, oldMap);
        // following moved from onAfterUpdate
        reopenCase(updatedCases, oldMap);
        calcCaseDurations(updatedCases, oldMap);
        
    }
    
    static public void onAfterUpdate(Case[] updatedCases, Map<ID, Case> oldMap) {
        checkCasesForCreatingEntitlements( updatedCases ,oldMap );
        // bypass all processing if Case Score update
        for(Case updatedCase : updatedCases) {
            Case beforeUpdate = oldMap.get(updatedCase.Id);
            if (updatedCase.Support_Case_Score__c != beforeUpdate.Support_Case_Score__c){
                return;
            }
        }
        completeMilestones(updatedCases, oldMap);
        updateJiraCases(updatedCases, oldMap);
        calcAssignment(updatedCases, oldMap);
    }

    public static void checkCasesForCreatingEntitlements( Case[] newCases, Map<Id, Case> oldMap ){
        /****************Processing Case Entitlements After Insert/Update *******************/
        Set<Id> caseIds = new Set<Id>();
        for(Case caseVar : newCases){
            if( !String.isempty(caseVar.Priority) && !String.isEmpty(caseVar.Customer_Product__c) ){
                if( oldMap != null ){
                    if( oldMap.get(caseVar.Id).Priority != caseVar.Priority ||  oldMap.get(caseVar.Id).Customer_Product__c != caseVar.Customer_Product__c || oldMap.get(caseVar.Id).RecordTypeId != caseVar.RecordTypeId ){
                        caseIds.add( caseVar.Id );
                    }
                }
                else{
                    caseIds.add( caseVar.Id );
                }
            }
        }
        try{
            if( caseIds.size() > 0 ){
                if( oldMap != null ){
                    List<Case_Entitlements__c> caseEntitlementsToDelete = T1_CaseEntitlementService.getCaseEntitlementsByCaseId( caseIds );
                    delete caseEntitlementsToDelete;
                }
                T1_CaseEntitlementService.processCasesforCreatingEntitlements( caseIds );
            }
        }catch(Exception e){
            system.debug( 'Exception details ' + e.getCause() + e.getMessage() + e.getStackTraceString());
            Error_Log__c errLog = T1_ErrorLogService.createErrorLog( e, caseIds, 'Apex Class',  'CaseTriggerHandler.checkCasesForCreatingEntitlements');
            insert errLog;
        }
        
    }

    static public void SetCreatedDateMod(Case[] newCases) {
    
         list <case> l_cases = new list<case>(); //list of cases to be updated
         set<Id> CaseIds = new set<Id>(); // list of Case Id's for Cases to be updated
            
         for(Case newCase : newCases){
            //if(newCase.CreatedDate_Mod__c == null){ // If our modifiable date is null we want to update this case
                CaseIds.add(newCase.ID); //add all cases - 11/6/18
            //}   
         } 
        
         if (!CaseIds.isEmpty()){
            for (case [] arrCase : [SELECT Id, 
                                           CreatedDate 
                                    FROM case 
                                    WHERE Id IN :caseIds]){      // an array of Cases based on the ID's to be updated 
                for (Case sCase : arrCase){ // Update the field for the Case to be updated and add it to the Update List
                    sCase.CreatedDate_Mod__c = sCase.CreatedDate;
                    l_cases.add(sCase);
                }
            }  
         }
        
        if (!l_cases.isEmpty()){
           	//update l_cases;
           	// following code from CaseAssignment trigger 11/6/18
            Database.DMLOptions dmo = new Database.DMLOptions();
            dmo.assignmentRuleHeader.useDefaultRule = true;
            if(!Test.isRunningTest())
                Database.update(l_cases, dmo);
        }   
    }
    
    // This trigger's purpose is to reset the milestone warnings when Case is closed or Interim Solution provided
    static public void resetMilestoneWarnings(Case[] updatedCases, Map<ID, Case> oldMap) {
        
        for(Case updatedCase : updatedCases) {
            Case beforeUpdate = oldMap.get(updatedCase.Id);
              if (updatedCase.Status != beforeUpdate.Status && (updatedCase.Status == 'Resolved' || updatedCase.Status == 'Closed')) { 
                // clear milestone warnings
                updatedCase.Response_MS_Warning__c = False;
                updatedCase.Update_MS_Warning__c = False;
                updatedCase.Interim_Resolution_MS_Warning__c = False;
                updatedCase.Final_Resolution_MS_Warning__c = False;
                // SCE-104 Clear the Jira Development Status when Case is Resolved or Closed
                if (updatedCase.Jira_Dev_Issue_Count__c > 0){
                    updatedCase.Development_Status__c = '';
                }
             } 
        }

        for(Case updatedCase : updatedCases) {
            Case beforeUpdate = oldMap.get(updatedCase.Id);
             if (updatedCase.Interim_Solution_Provided__c != beforeUpdate.Interim_Solution_Provided__c && updatedCase.Interim_Solution_Provided__c == True) { 
                // clear milestone warnings
                updatedCase.Response_MS_Warning__c = False;
                updatedCase.Update_MS_Warning__c = False;
                updatedCase.Interim_Resolution_MS_Warning__c = False;
             } 
        }        
    }

    static public void setDateToWorkDayOnCase(Case[] updatedCases, Map<ID, Case> oldMap) {
        //Query holidays from Org  
        //List<Holiday> holidays=[Select StartTimeInMinutes, Name, ActivityDate From Holiday ];
        
         for(Case updatedCase : updatedCases) {
             Case beforeUpdate = oldMap.get(updatedCase.Id);
             // Only update if the field has been modified
             if (updatedCase.AwaitInfoFinalFollowupDue__c != beforeUpdate.AwaitInfoFinalFollowupDue__c && updatedCase.AwaitInfoFinalFollowupDue__c != null) { 
                    // Field has been changed! 
                    Date DateOut = updatedCase.AwaitInfoFinalFollowupDue__c.Date();

                    if (WorkDayCalcs.checkifWorkDayFU(DateOut, holidays) == false){
                        DateOut = Date.today();
                        Integer numDays = 3; //the default for all but Urgent
                        if (updatedCase.Priority == 'Urgent')
                            numDays = 2;
                        DateOut = WorkDayCalcs.calculateNthWorkingDay(DateOut, numDays, holidays);
                        // now put date and time back together
                        String sDate = DateOut.day() + '/' + DateOut.month() + '/' + DateOut.year();
                        String sTime = updatedCase.AwaitInfoFinalFollowupDue__c.format('hh:mm a');
                        updatedCase.AwaitInfoFinalFollowupDue__c = DateTime.parse(sDate + ' ' + sTime);
                    }
             } 
                              
             if (updatedCase.AwaitInfoFirstFollowupDue__c != beforeUpdate.AwaitInfoFirstFollowupDue__c && updatedCase.AwaitInfoFirstFollowupDue__c != null) { 
                    // Field has been changed! 
                    Date DateOut = updatedCase.AwaitInfoFirstFollowupDue__c.Date();

                    if (WorkDayCalcs.checkifWorkDayFU(DateOut, holidays) == false){
                        DateOut = Date.today();
                        Integer numDays = 3; //the default for all but Urgent
                        if (updatedCase.Priority == 'Urgent')
                            numDays = 2;
                        DateOut = WorkDayCalcs.calculateNthWorkingDay(DateOut, numDays, holidays);
                        // now put date and time back together
                        String sDate = DateOut.day() + '/' + DateOut.month() + '/' + DateOut.year();
                        String sTime = updatedCase.AwaitInfoFirstFollowupDue__c.format('hh:mm a');
                        updatedCase.AwaitInfoFirstFollowupDue__c = DateTime.parse(sDate + ' ' + sTime);
                    }
             } 
                              
             if (updatedCase.AwaitInfoSecondFollowupDue__c != beforeUpdate.AwaitInfoSecondFollowupDue__c && updatedCase.AwaitInfoSecondFollowupDue__c != null) { 
                    // Field has been changed! 
                    Date DateOut = updatedCase.AwaitInfoSecondFollowupDue__c.Date();

                    if (WorkDayCalcs.checkifWorkDayFU(DateOut, holidays) == false){
                        DateOut = Date.today();
                        Integer numDays = 3; //the default for all but Urgent
                        if (updatedCase.Priority == 'Urgent')
                            numDays = 2;
                        DateOut = WorkDayCalcs.calculateNthWorkingDay(DateOut, numDays, holidays);
                        // now put date and time back together
                        String sDate = DateOut.day() + '/' + DateOut.month() + '/' + DateOut.year();
                        String sTime = updatedCase.AwaitInfoSecondFollowupDue__c.format('hh:mm a');
                        updatedCase.AwaitInfoSecondFollowupDue__c = DateTime.parse(sDate + ' ' + sTime);
                    }
             } 
             // CR 116848 Start
             if (updatedCase.Quote_Reminder__c != beforeUpdate.Quote_Reminder__c && updatedCase.Quote_Reminder__c != null) { 
                    // Field has been changed! 
                    Date DateOut = updatedCase.Quote_Reminder__c.Date();
                    DateOut = WorkDayCalcs.advanceIfNonworking(DateOut, holidays);
                    // now put date and time back together
                    String sDate = DateOut.day() + '/' + DateOut.month() + '/' + DateOut.year();
                    String sTime = updatedCase.Quote_Reminder__c.format('hh:mm a');
                    updatedCase.Quote_Reminder__c = DateTime.parse(sDate + ' ' + sTime);
             } 
             if (updatedCase.Quote_Expiry__c != beforeUpdate.Quote_Expiry__c && updatedCase.Quote_Expiry__c != null) { 
                    // Field has been changed! 
                    Date DateOut = updatedCase.Quote_Expiry__c.Date();
                    DateOut = WorkDayCalcs.advanceIfNonworking(DateOut, holidays);
                    // now put date and time back together
                    String sDate = DateOut.day() + '/' + DateOut.month() + '/' + DateOut.year();
                    String sTime = updatedCase.Quote_Expiry__c.format('hh:mm a');
                    updatedCase.Quote_Expiry__c = DateTime.parse(sDate + ' ' + sTime);
             } 
             // CR 116848 End
         }            
    }   
    
    static public void updateJiraCases(Case[] updatedCases, Map<ID, Case> oldMap) {
        // If Case contains a Jira Issue No then we will want to get the milestone target dates
        List<Id> updateJiraCases = new List<Id>();
        for(Case updatedCase : updatedCases) {
            Case beforeUpdate = oldMap.get(updatedCase.Id);
            
             if ((updatedCase.Jira_Issue_No__c != beforeUpdate.Jira_Issue_No__c 
                 || updatedCase.Priority != beforeUpdate.Priority
                 || updatedCase.Status != beforeUpdate.Status
                 || updatedCase.IsStopped != beforeUpdate.IsStopped
                 || updatedCase.Account != beforeUpdate.Account
                 || updatedCase.Entitlement != beforeUpdate.Entitlement
                 || updatedCase.BusinessHours != beforeUpdate.BusinessHours)
                 && (String.isBlank(updatedCase.Jira_Issue_No__c) == false
                    || updatedCase.Jira_Dev_Issue_Count__c > 0) // include case with any linked jira issues regardless of Issue_no field on Case
                 && updatedCase.Status != 'Resolved'
                 && updatedCase.Status != 'Closed') { 
                updateJiraCases.add(updatedCase.Id);
             } 
     
        }
        
        if (!updateJiraCases.isEmpty()) {
            CaseMilestoneUtils.copyTargetDate(updateJiraCases);
        }
    }

    static public void reopenCase(Case[] updatedCases, Map<ID, Case> oldMap) {    
         
        // If Case is being Reopened we need to set the Exit Entitlement flag
        for(Case updatedCase : updatedCases) {
            Case beforeUpdate = oldMap.get(updatedCase.Id);
        
            if (updatedCase.Status != beforeUpdate.Status && 
                (beforeUpdate.Status == 'Resolved' || beforeUpdate.Status == 'Closed') && 
                (updatedCase.Status != 'Resolved' && updatedCase.Status != 'Closed') &&
                updatedCase.Exit_Entitlement_Process__c <> false){ 
                   updatedCase.Exit_Entitlement_Process__c = false;
             } 
        }
     }
    
    
    static public void completeMilestones(Case[] updatedCases, Map<ID, Case> oldMap) {
        List<Id> updateJiraCases = new List<Id>();
        DateTime completionDate = System.now();
        //String milestoneType = '';    
        // If Case is being Resolved or Closed then we want to stop the Final resolution milestone, and any others that may be running, including Update and Interim Resolution
        List<Id> updateFinResCases = new List<Id>();
        for(Case updatedCase : updatedCases) {
             Case beforeUpdate = oldMap.get(updatedCase.Id);
             
             if (updatedCase.Status != beforeUpdate.Status && (updatedCase.Status == 'Resolved' || updatedCase.Status == 'Closed')) { 
                // Status has been changed to resolved or Closed
                updateFinResCases .add(updatedCase.Id);
              } 
        }
        
        if (updateFinResCases .isEmpty() == false ){
            milestoneUtils.completeMilestone(updateFinResCases , 'Response', completionDate);
            milestoneUtils.completeMilestone(updateFinResCases , 'Update', completionDate);
            milestoneUtils.completeMilestone(updateFinResCases , 'Interim Resolution', completionDate);
            milestoneUtils.completeMilestone(updateFinResCases , 'Final Resolution', completionDate);
            milestoneUtils.completeMilestone(updateFinResCases , 'Action Required', completionDate);
            CaseMilestoneUtils.setExitEntitlement(updateFinResCases, True);
        }
        // If Interim Solution is being supplied then we want to stop current Update and Interim Resolution milestones
        List<Id> updateIntResCases = new List<Id>();
        for(Case updatedCase : updatedCases) {
            Case beforeUpdate = oldMap.get(updatedCase.Id);
        
             if (updatedCase.Interim_Solution_Provided__c != beforeUpdate.Interim_Solution_Provided__c && updatedCase.Interim_Solution_Provided__c == True) { 
                // Field has been changed and set to True meaning our workflow was triggered which sends the Interim Solution email and updates our field
                updateIntResCases .add(updatedCase.Id);
             } 
        }
        
        if (updateIntResCases .isEmpty() == false ){
            milestoneUtils.completeMilestone(updateIntResCases , 'Response', completionDate);
            milestoneUtils.completeMilestone(updateIntResCases , 'Update', completionDate);
            milestoneUtils.completeMilestone(updateIntResCases , 'Interim Resolution', completionDate);
        }
        
        // If Jira Issue No is being supplied then we want to stop current Update
        for(Case updatedCase : updatedCases) {
            Case beforeUpdate = oldMap.get(updatedCase.Id);
            
             if ((updatedCase.Jira_Issue_No__c != beforeUpdate.Jira_Issue_No__c 
                &&  String.isBlank(updatedCase.Jira_Issue_No__c) == false)
                && (updatedCase.Status != 'Resolved' //only update if Case is still open
                && updatedCase.Status != 'Closed')) { 
                // Field has been changed
                updateJiraCases .add(updatedCase.Id);
             } 
        }
        
        if (updateJiraCases .isEmpty() == false ){
            milestoneUtils.completeMilestone(updateJiraCases , 'Update', completionDate);
        } 

        // If all comms flags are cleared then complete Acknowedge Comms
        List<Id> updateAckCases = new List<Id>();
        for(Case updatedCase : updatedCases) {
            Case beforeUpdate = oldMap.get(updatedCase.Id);
            
             if ((updatedCase.New_Customer_Email__c  != beforeUpdate.New_Customer_Email__c ||
                updatedCase.New_Customer_Attachment__c   != beforeUpdate.New_Customer_Attachment__c  ||
                updatedCase.New_Portal_Case_Comment__c   != beforeUpdate.New_Portal_Case_Comment__c  ||
                updatedCase.Priority_Has_Changed__c   != beforeUpdate.Priority_Has_Changed__c )
                &&  (updatedCase.New_Customer_Email__c == false &&
                updatedCase.New_Customer_Attachment__c == false &&
                updatedCase.New_Portal_Case_Comment__c == false &&
                updatedCase.Priority_Has_Changed__c == false)) { 
                // Field has been changed
                updateAckCases .add(updatedCase.Id);
             } 
        }
        
        if (updateAckCases .isEmpty() == false ){
            milestoneUtils.completeMilestone(updateAckCases , 'Action Required', completionDate);
        } 
    }

    static public void loopKiller(Case[] newCases){
        // Will not process a third email if there was already two preceeding identical emails (from
        // the same email address with the same subject) and the previous emails were less than 5 minutes old.
        // Second email to case required for situations where customer meant to include more information on
        // the first email and so recomposed and re-sent. It's unlikely a third deliberate email with identical
        // subject would be submitted within the same 5 minute window this trigger operates within.
    
        //Case newCase : newCases;
     
      // Granth 18/9/15 - The following code was found in UAT and Prod - added 19/3/15 in both. It was missing from Dev so I have reinstated it.
      // Add logic to exclude out of office replies
        if(newCases[0].Subject != null) {
            if (newCases[0].subject.startsWithIgnoreCase('Automatic Reply') || newCases[0].subject.startsWithIgnoreCase('Out of office')){
                if (!Test.isRunningTest()){
                    newCases[0].addError('Out of Office reply has been ignored');
                }
            }
        }
      // Granth 18/9/15 
      
        //case[] check = [select ID, CreatedDate, subject from Case where SuppliedEmail = :newCases[0].SuppliedEmail and subject = :newCases[0].subject order by CreatedDate desc];
        system.debug(newCases[0].SuppliedEmail);
        system.debug(newCases[0].subject);
        DateTime theDate = System.now().addMinutes(-5); // 18/5/18 GH - Variable for query
		
        //if(newCases[0].Subject != null ) {
        if(newCases[0].Subject != null && (String.isNotEmpty(newCases[0].SuppliedEmail) || Test.isRunningTest()) ) { 
            // 18/5/18 GH - Only query if we need to and use calculated date
            case[] check = [select ID, CreatedDate, subject from Case where SuppliedEmail = :newCases[0].SuppliedEmail and subject = :newCases[0].subject and CreatedDate > :theDate order by CreatedDate desc];

            if (Test.isRunningTest()){
                check = [select ID, CreatedDate, subject from Case where subject = :newCases[0].subject and CreatedDate > :theDate order by CreatedDate desc];
            }
            // we have a subject, proceed.
            if(newCases[0].subject.contains('[ ref:')){
                //No Errors.  Email should be attached to the case.
            }else{
                if(check.size() > 1){
                    if((check[0].createddate.addMinutes(5) > System.now()) && check[0].subject.contains(newCases[0].subject)){
                        if (!Test.isRunningTest()){
                            newCases[0].addError('Automatic email loop has been terminated');
                        }
                        //Loop Was Killed.
                    }else{
                        //New Case should be created now!       
                    }
                }
            }
        }
    } 
    
    static public void calcBusinessHoursAges (Case[] updatedCases, Map<ID, Case> oldMap) {   
 
 		//Set<String> stopStatusSet = new Set<String>();
 		if (stopStatusSet.IsEmpty()){
	        //Get the stop statuses
	        List<Stop_Status__c> StopStat = [select name from Stop_Status__c];
	        for (Stop_Status__c stopStatus:StopStat) {
	            stopStatusSet.add(stopStatus.Name);
	        }
 		}
 		
        //Get the default business hours (we might need it)
        //BusinessHours defaultHours = [select Id from BusinessHours where IsDefault=true];

        //Get the closed statuses (because at the point of this trigger Case.IsClosed won't be set yet)
        //Set<String> closedStatusSet = new Set<String>();  
        if (closedStatusSet.IsEmpty()){
	        List<CaseStatus> cStat = [Select MasterLabel From CaseStatus where IsClosed=true];
	        for (CaseStatus status:cStat) {
	            closedStatusSet.add(status.MasterLabel);
	        }
        }
        //For any case where the status is changed, recalc the business hours in the buckets
        for (Case updatedCase:updatedCases) {
            Case oldCase = oldMap.get(updatedCase.Id);

            if (updatedCase.Last_Status_Change__c == null) {
                updatedCase.Last_Status_Change__c = System.now();
            }
            if (oldCase.Status!=updatedCase.Status && updatedCase.Last_Status_Change__c!=null) {
                //OK, the status has changed
                if (!oldCase.IsClosed) {
                    //We only update the buckets for open cases

                    //On the off-chance that the business hours on the case are null, use the default ones instead
                    Id hoursToUse = updatedCase.BusinessHoursId!=null?updatedCase.BusinessHoursId:defaultHours.Id;
                    
                    if (updatedCase.Time_With_Customer__c == null) {
                        updatedCase.Time_With_Customer__c = 0;
                    }
                    if (updatedCase.Time_With_Support__c == null) {
                        updatedCase.Time_With_Support__c = 0;
                    }
                    if (updatedCase.Case_Age_In_Business_Hours__c == null) {
                        updatedCase.Case_Age_In_Business_Hours__c = 0;
                    }
                        
                    //The diff method comes back in milliseconds, so we divide by 3600000 to get hours.
                    Double timeSinceLastStatus =  0.00;
                    
                    if (updatedCase.Last_Status_Change__c != System.now()){
                        timeSinceLastStatus = BusinessHours.diff(hoursToUse, updatedCase.Last_Status_Change__c, System.now())/3600000.0;
                        System.debug('Milliseconds ' + BusinessHours.diff(hoursToUse, updatedCase.Last_Status_Change__c, System.now()));
                    }
                    System.debug('Time since last status change ' + timeSinceLastStatus);

                    //We decide which bucket to add it to based on whether it was in a stop status before
                    if (stopStatusSet.contains(oldCase.Status)) {
                        updatedCase.Time_With_Customer__c += timeSinceLastStatus;
                    } else {
                        updatedCase.Time_With_Support__c += timeSinceLastStatus;
                    }

                    if (closedStatusSet.contains(updatedCase.Status)) {
                        updatedCase.Case_Age_In_Business_Hours__c = updatedCase.Time_With_Customer__c + updatedCase.Time_With_Support__c;
                    }
                }

                updatedCase.Last_Status_Change__c = System.now();
            }
        }
    }   

    static public void initBusinessHoursAges (Case[] newCases) {   
        for(Case newCase : newCases) {
            newCase.Last_Status_Change__c = System.now();
            newCase.Time_With_Customer__c = 0;
            newCase.Time_With_Support__c = 0;
            newCase.Case_Age_In_Business_Hours__c = 0;
            if (newCase.Status <> 'New') // cr 150222
                newCase.Status = 'New'; 
        }
    } 
    
    static public void calcCaseDurations (Case[] updatedCases, Map<ID, Case> oldMap) {   
 
        // As at 18/8/16 we shifted from Calendar days to Work Days
        list <case> c = new list<case>(); //list of cases to be updated
        Double Closed_Cal_Days = 0;
        Double Resolved_Cal_Days = 0;
        Boolean Close_Calc = false;
        Boolean Resolve_Calc = false;
        Id busHrsToUse;
        Integer hrsInDay = 12;
        
        //Get the default business hours 
        //Default Business Hours carry the work day hours. We take Monday Start and End Times to calculate the hours in the day.
        //
        //BusinessHours defaultHours = [select Id from BusinessHours where IsDefault=true limit 1]; 
        //
        //List<BusinessHours> BusHrs = [select Id, MondayStartTime, MondayEndTime from BusinessHours where IsDefault=true limit 1];
        //for (BusinessHours BusHr:BusHrs){
        //    busHrsToUse = BusHr.Id;
        //    hrsInDay = (BusHr.MondayEndTime.hour() - BusHr.MondayStartTime.hour());
        //}
        //
        hrsInDay = (defaultHours.MondayEndTime.hour() - defaultHours.MondayStartTime.hour());

        //For any case where the status is changed, recalc the business hours in the buckets
        for (Case updatedCase:updatedCases) {
            Case oldCase = oldMap.get(updatedCase.Id);
            
            Close_Calc = false;
            Resolve_Calc = false;
            Resolved_Cal_Days = 0;
            Closed_Cal_Days = 0;
            
            if (oldCase.ClosedDate != updatedCase.ClosedDate || oldCase.Resolved_Date__c != updatedCase.Resolved_Date__c) {
                if (oldCase.ClosedDate!=updatedCase.ClosedDate) {
                    if (updatedCase.ClosedDate!=null) {
                        //The diff method comes back in milliseconds, so we divide by 3600000 to get hours.
                        //Calculate Duration to Closed
                        Double duration;
                        duration = BusinessHours.diff(defaultHours.Id, updatedCase.CreatedDate, updatedCase.ClosedDate)/3600000.0;
                        Closed_Cal_Days = duration / hrsInDay;
                    }
                    
                    Close_Calc = true;
                }
                if (oldCase.Resolved_Date__c!=updatedCase.Resolved_Date__c) {
                    if (updatedCase.Resolved_Date__c!=null) {
                        //The diff method comes back in milliseconds, so we divide by 3600000 to get hours.
                        //Calculate Duration to Resolved
                        Double duration;
                        duration = BusinessHours.diff(defaultHours.Id, updatedCase.CreatedDate, updatedCase.Resolved_Date__c)/3600000.0;
                        Resolved_Cal_Days = duration / hrsInDay;
                    }
                    
                    Resolve_Calc = true;
                }
                
            }
            
            If (Close_Calc && Resolve_Calc){
                /*c.add(new Case(id = updatedCase.id, 
                               Duration_to_Closed_Cal_Days__c = Closed_Cal_Days,
                               Duration_to_Resolved_Cal_Days__c = Resolved_Cal_Days));*/
                               updatedCase.Duration_to_Closed_Cal_Days__c = Closed_Cal_Days;
                               updatedCase.Duration_to_Resolved_Cal_Days__c = Resolved_Cal_Days;
            }else if (Close_Calc) {
                        /*c.add(new Case(id = updatedCase.id, 
                               Duration_to_Closed_Cal_Days__c = Closed_Cal_Days));*/
                               updatedCase.Duration_to_Closed_Cal_Days__c = Closed_Cal_Days;
            }else if (Resolve_Calc) {
                        /*c.add(new Case(id = updatedCase.id, 
                               Duration_to_Resolved_Cal_Days__c = Resolved_Cal_Days));*/
                               updatedCase.Duration_to_Resolved_Cal_Days__c = Resolved_Cal_Days;
            }

        }
        
        /*if (!c.isEmpty()) {
            update c;
        }*/
    }   

    static public void calcTimeAwaitResAlloc (Case[] updatedCases, Map<ID, Case> oldMap) {   
 
        //if(!Test.isRunningTest()){
            //Get the default business hours 
            //BusinessHours defaultHours = [select Id, MondayStartTime, MondayEndTime from BusinessHours where IsDefault=true limit 1];
            Id hoursToUse = null;
            hoursToUse = defaultHours.Id;
            Integer hrsInDay = (defaultHours.MondayEndTime.hour() - defaultHours.MondayStartTime.hour());
                
            if (hoursToUse <> null){
                for (Case updatedCase:updatedCases) {
                    Case oldCase = oldMap.get(updatedCase.Id);
                    
                    if (oldCase.Status=='Awaiting Resource Allocation' && updatedCase.Status=='Scheduled') {
                        
                        //OK, the status has changed to match our conditions and the case was not closed
                        //The diff method comes back in milliseconds, so we divide by 3600000 to get hours.
                        Double timeSinceLastStatus =  0;
                        // Use the last status change date from the oldcase as this is when Awaiting Resource Allocation was set
                        if (updatedCase.Last_Status_Change__c != System.now()){
                            timeSinceLastStatus = BusinessHours.diff(hoursToUse, updatedCase.Last_Status_Change__c, System.now()) / 3600000.0 / hrsInDay;
                        }
                        updatedCase.Time_Await_Res_Alloc__c = timeSinceLastStatus; 
                        
                    }
                }
            }
        //}
    } 
    static public void calcAssignment(Case[] updatedCases, Map<ID, Case> oldMap) {
        List<Id> assignCases = new List<Id>();
        for(Case updatedCase : updatedCases) {
             Case beforeUpdate = oldMap.get(updatedCase.Id);
             
             if ((updatedCase.Customer_Product__c != beforeUpdate.Customer_Product__c || updatedCase.RecordType != beforeUpdate.RecordType ) && updatedCase.Status == 'New') { 
                // Status has been changed to resolved or Closed
                assignCases .add(updatedCase.Id);
              } 
        }
        
        if (assignCases .isEmpty() == false ){
             calcCaseAssignment.calcAssignment(assignCases);  
        } 
    }
    
}