unpackaged/main/default/objects/Case/fields/Case_Record_Type_Name__c.field-meta.xml
<CustomField>
    <fullName>Case_Record_Type_Name__c</fullName>
    <formula>RecordType.DeveloperName</formula>
    <label>Case Record Type Name</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Customer_Product__c.field-meta.xml
<CustomField>
    <fullName>Customer_Product__c</fullName>
    <label>Product Affected</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Applicable</fullName>
            </value>
            <value>
                <fullName>Asset Management (AM)</fullName>
            </value>
            <value>
                <fullName>Business Process Management (BPM)</fullName>
            </value>
            <value>
                <fullName>Corporate Performance Management (CPM)</fullName>
            </value>
            <value>
                <fullName>Customer Relationship Management (CRM)</fullName>
            </value>
            <value>
                <fullName>Enterprise Cash Receipting (ECR)</fullName>
            </value>
            <value>
                <fullName>Enterprise Content Management (ECM)</fullName>
            </value>
            <value>
                <fullName>Financials (FIN)</fullName>
            </value>
            <value>
                <fullName>Human Resource &amp; Payroll (HRP)</fullName>
            </value>
            <value>
                <fullName>Property &amp; Rating (P&amp;R)</fullName>
            </value>
            <value>
                <fullName>Spatial</fullName>
            </value>
            <value>
                <fullName>Student Management (SM)</fullName>
            </value>
            <value>
                <fullName>Supply Chain Management (SCM)</fullName>
            </value>
            <value>
                <fullName>Enterprise App Store</fullName>
            </value>
            <value>
                <fullName>Customer Community</fullName>
            </value>
            <value>
                <fullName>Technical</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Case_Entitlements__c/Case_Entitlements__c.object-meta.xml
<CustomObject>
    <label>Case Entitlement</label>
    <nameField>
        <displayFormat>CE-{0000000}</displayFormat>
        <label>Case Entitlements Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Entitlements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Case_Entitlements__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Case Entitlements</relationshipLabel>
    <relationshipName>Case_Entitlements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Case_Entitlements__c/fields/Contract_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>Contract_Line_Item__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contract Line Item</label>
    <referenceTo>ContractLineItem</referenceTo>
    <relationshipLabel>Case Entitlements</relationshipLabel>
    <relationshipName>Case_Entitlements</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ContractLineItem/fields/End_Terminated_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Terminated_Date__c</fullName>
    <description>Shows end date unless there is a terminated date.</description>
    <formula>IF(ISBLANK(SBQQSC__TerminatedDate__c),   SBQQSC__SubscriptionEndDate__c , SBQQSC__TerminatedDate__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>End/ Terminated Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/ContractLineItem/fields/Entitlement_Case_Type__c.field-meta.xml
<CustomField>
    <fullName>Entitlement_Case_Type__c</fullName>
    <label>Entitlement Case Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Entitlement_Case_Type</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ContractLineItem/fields/Entitlement_Priority__c.field-meta.xml
<CustomField>
    <fullName>Entitlement_Priority__c</fullName>
    <label>Entitlement Priority</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Entitlement_Priority</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Error_Log__c/Error_Log__c.object-meta.xml
<CustomObject>
    <label>Custom Error Log</label>
    <nameField>
        <displayFormat>E-{000000}</displayFormat>
        <label>Error Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Custom Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Product_Mapping__c/Product_Mapping__c.object-meta.xml
<CustomObject>
    <description>Links the Current Licensed Products to Service Cloud Product for Product Affected on Cases</description>
    <label>Product Mapping</label>
    <nameField>
        <displayFormat>Prod-{000000}</displayFormat>
        <label>Product Mapping Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Mapping</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Product_Mapping__c/fields/Sales_Product__c.field-meta.xml
<CustomField>
    <fullName>Sales_Product__c</fullName>
    <label>Sales Product</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Product_Mapping__c/fields/Service_Product__c.field-meta.xml
<CustomField>
    <fullName>Service_Product__c</fullName>
    <label>Service Product</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Service_Product__c/Service_Product__c.object-meta.xml
<CustomObject>
    <description>Product terminology utilised by Service Cloud contact centre</description>
    <label>Service Product</label>
    <nameField>
        <label>Service Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Shared_Entitlements__c/Shared_Entitlements__c.object-meta.xml
<CustomObject>
    <description>Store the shared accounts for shared services</description>
    <label>Shared Entitlement</label>
    <nameField>
        <displayFormat>SE-{000000}</displayFormat>
        <label>Shared Entitlements Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shared Entitlements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Shared_Entitlements__c/fields/Source_Account__c.field-meta.xml
<CustomField>
    <fullName>Source_Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Store Parent Account</description>
    <label>Source Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Shared Entitlements</relationshipLabel>
    <relationshipName>Shared_Entitlements</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Shared_Entitlements__c/fields/Target_Account__c.field-meta.xml
<CustomField>
    <fullName>Target_Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Target Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Shared Entitlements (Target Account)</relationshipLabel>
    <relationshipName>Shared_Entitlements1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/globalValueSets/Entitlement_Case_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Change Control</fullName>
    </customValue>
    <customValue>
        <fullName>Consultant Question or Issue</fullName>
    </customValue>
    <customValue>
        <fullName>Consulting - Question</fullName>
    </customValue>
    <customValue>
        <fullName>I am experiencing an issue</fullName>
    </customValue>
    <customValue>
        <fullName>I have a Question</fullName>
    </customValue>
    <customValue>
        <fullName>I require an AMS service</fullName>
    </customValue>
    <customValue>
        <fullName>I require a TechnologyOne Cloud service</fullName>
    </customValue>
    <customValue>
        <fullName>I require Consulting services</fullName>
    </customValue>
    <customValue>
        <fullName>Problem</fullName>
    </customValue>
    <customValue>
        <fullName>Service Request</fullName>
    </customValue>
    <customValue>
        <fullName>All</fullName>
    </customValue>
    <masterLabel>Entitlement Case Type</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Entitlement_Priority.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Medium</fullName>
    </customValue>
    <customValue>
        <fullName>High</fullName>
    </customValue>
    <customValue>
        <fullName>Urgent</fullName>
    </customValue>
    <customValue>
        <fullName>Critical</fullName>
    </customValue>
    <customValue>
        <fullName>All</fullName>
    </customValue>
    <masterLabel>Entitlement Priority</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/T1_CaseEntitlementService.cls
/*
DEscription: Case Entitlement service class to process cases and generate their servie packs entitlement as per the account on case
*/

public class T1_CaseEntitlementService {
    
    // product category for which entitlements need to be generated
    public static final Set<String>  CONTRACT_LINEITEM_SERVICE_CATEGORY = new Set<String>{'Support Fee'};
    public static final Map<Id,Schema.RecordTypeInfo> caseRecordTypeIdNameMap = getCaseRecordTypeMap();
    
    /* DEcription: Future Method to process  the cases called by Case Trigger handler
    * return type: void
    * param: set of case Ids
    ****************/
    @future
    public static void processCasesforCreatingEntitlements( Set<Id> caseIds ){
        
        // query case priority,customer product and record Type
        List<Case> caseList = queryCaseById( caseIds );  // Query 1
        createEntitlements(caseList, caseIds);                        

    }
    
    public static void createEntitlements( List<Case> caseList ,Set<Id> caseIds ){
        //  storemap of Case Id and  customer product name
        Map<Id,String> caseIdcustProductNameMap = new Map<Id,String>();

        // create Map of case Id and account Id
        Map<Id,Id> caseIdAccountIdMap = new Map<Id,Id>();

        if( caseList.size() > 0 ){
            for( Case caseLoopVar: caseList){
                caseIdcustProductNameMap.put( caseLoopVar.Id, caseLoopVar.Customer_Product__c );
                caseIdAccountIdMap.put( caseLoopVar.Id, caseLoopVar.AccountId );
            }
        }

        // create map of service product and Sales Product Names
        Map<String,Set<String>> serviceProdSalesProductMap = new Map<String,Set<String>>();

        // set to store list of sales product names
        Set<String> salesProductNameSet = new Set<String>();

        for( Product_Mapping__c prodMapVar : getProductMappingByServiceProduct( new Set<String>(caseIdcustProductNameMap.values())) ){              // query 2
            salesProductNameSet.add( prodMapVar.Sales_Product__c );
            if(  !serviceProdSalesProductMap.keyset().contains( prodMapVar.Service_Product__c ) ){
                serviceProdSalesProductMap.put(prodMapVar.Service_Product__c,new Set<String>{prodMapVar.Sales_Product__c});
            }
            else{
                Set<String> salesProductList = serviceProdSalesProductMap.get(prodMapVar.Service_Product__c);
                salesProductList.add( prodMapVar.Sales_Product__c );
                serviceProdSalesProductMap.put(prodMapVar.Service_Product__c,salesProductList);
            }
        }

        system.debug('serviceProdSalesProductMap ' + serviceProdSalesProductMap);

        // create Map of Case Id and corresponding sales product
        Map<Id,Set<String>> caseIdSalesProductsMap = new Map<Id,Set<String>>();
        try{ 
            for( Case caseLoopVar: caseList){
                for( String servProdVar : serviceProdSalesProductMap.keyset() ){
                    if( caseLoopVar.Customer_Product__c == servProdVar){
                        caseIdSalesProductsMap.put(caseLoopVar.Id,serviceProdSalesProductMap.get(servProdVar));
                    }
                }
            }
            system.debug( 'caseIdSalesProductsMap ' + caseIdSalesProductsMap);
        }
        catch( Exception e){
            String message = ' No Sales Product mapping exists for case product';
            system.debug( 'Exception details ' + e.getCause() + e.getMessage()+ ' ' + message + ' '+ e.getStackTraceString());
            Error_Log__c errLog = T1_ErrorLogService.createErrorLog( e, caseIds, 'Apex Class',  'T1_CaseEntitlementService');
            insert errLog;
        }

        // add shared accounts id to set and create Map of target and source account
        Map<Id,Set<Id>> targetSourceAccountIdMap = new Map<Id,Set<Id>>();
        for( Shared_Entitlements__c sharedEntitlmentVar : getSourceAccountIds( new Set<Id>(caseIdAccountIdMap.values()) ) ){        // query 3
            if( sharedEntitlmentVar != null ){
             
                if( !targetSourceAccountIdMap.keyset().contains( sharedEntitlmentVar.Target_Account__c ) ){
                    targetSourceAccountIdMap.put( sharedEntitlmentVar.Target_Account__c, new Set<Id>{sharedEntitlmentVar.Source_Account__c} );
                }
                else{
                    Set<Id> sourceAccountIds = targetSourceAccountIdMap.get( sharedEntitlmentVar.Target_Account__c);
                    sourceAccountIds.add( sharedEntitlmentVar.Source_Account__c );
                    targetSourceAccountIdMap.put(sharedEntitlmentVar.Target_Account__c,sourceAccountIds );
                }
            }
        }
        
        // create set of account ids related to case 
        Set<Id> accountIdSet = new Set<Id>( caseIdAccountIdMap.values() );
        // add all account ids to set which are shared to above accounts
        if( targetSourceAccountIdMap.keyset().size() > 0 ){
            for( Id idVar: targetSourceAccountIdMap.keyset() ){
                accountIdSet.addAll(  targetSourceAccountIdMap.get(idVar)  );
            }
            
        }
        // query Service Contract for all those account Ids along with contract line items and create Map
        List<ServiceContract> serviceContractsList = getServiceContractByAccountId( accountIdSet, salesProductNameSet );        // query 4
        
        // Map of Account and corresponding service contracts
        Map<Id,List<ServiceContract>> accountServiceContractMap = new Map<Id,List<ServiceContract>>();
        for( ServiceContract scVar :  serviceContractsList){
           system.debug(' Inside Service Contracts Loop ' + scVar.AccountId);
            if( !accountServiceContractMap.keyset().contains( scVar.AccountId ) ){
                system.debug('Inside account map does not have service contract ');
                accountServiceContractMap.put( scVar.AccountId , new List<ServiceContract>{ scVar } );
            }
            else{
                List<ServiceContract> scList = accountServiceContractMap.get( scVar.AccountId );
                scList.add( scVar );
                accountServiceContractMap.put( scVar.AccountId , scList );
            }
            system.debug('accountServiceContractMap '+ accountServiceContractMap);
           
        }
        system.debug('accountServiceContractMap after loop *****'+ accountServiceContractMap);
        // Map of Case and corresponding service contracts
        Map<Id,List<ServiceContract>> caseServiceContractMap = new Map<Id,List<ServiceContract>>();
        for( Case caseVar: caseList ){

            system.debug('Case CreatedDate '+ caseVar );
            Id accountId = caseIdAccountIdMap.get( caseVar.Id );
            //  get source accounts for the case account if any
            Set<Id> sourceAccntIds = targetSourceAccountIdMap.get(accountId);
            if( sourceAccntIds == null ) sourceAccntIds = new Set<Id>();
            sourceAccntIds.add( accountId );
            system.debug('sourceAccntIds ' + sourceAccntIds);
            // loop through each account and theit service contracts
            Integer i =0;
            for(Id accountIdVar: sourceAccntIds){
                system.debug('accountIdVar '+ accountIdVar);
                i++;
                // get all service contracts for all accounts
                List<ServiceContract> serviceContracts = accountServiceContractMap.get(accountIdVar);
                system.debug('serviceContracts for account '+ accountIdVar + ' are ' + serviceContracts);
                // system.debug( serviceContracts.size() );
                if( serviceContracts != null ){
                    for(ServiceContract serviceContractVar : serviceContracts){
                        system.debug( 'Inside ServiceContract loop Contract Line Items for Service COntract ' + serviceContractVar.Name);
                        system.debug(serviceContractVar.ContractLineItems);
                        
                        if( caseVar.CreatedDate >= serviceContractVar.StartDate && caseVar.CreatedDate <= serviceContractVar.EndDate ){
                            if( !caseServiceContractMap.keyset().contains(caseVar.Id) ){
                                caseServiceContractMap.put( caseVar.Id, new List<ServiceContract>{ serviceContractVar });
                            }
                            else{
                                List<ServiceContract> serviceContractListForCase = caseServiceContractMap.get( caseVar.Id );
                                serviceContractListForCase.add( serviceContractVar );
                                caseServiceContractMap.put( caseVar.Id, serviceContractListForCase );
                            }
                            
                        }
                    }
                }
            }
        }
        system.debug('caseServiceContractMap ' + caseServiceContractMap);
        List<Case_Entitlements__c> caseEntitlements = new List<Case_Entitlements__c>();
        try{
            // create Map of case and each entitlements
           
            for(Case caseVar : caseList ){
                String caseRecordType = caseRecordTypeIdNameMap.get(caseVar.RecordTypeId).getName();
                Set<String> caseSalesProductNames  = caseIdSalesProductsMap.get(caseVar.Id);
                system.debug('caseRecordType ' + caseRecordType );
                for( ServiceContract serviceContractVar : caseServiceContractMap.get(caseVar.Id) ){
                    
                    // generate map of Contract line item corresponding to Id for sales product corresponding to Service Product on case
                    Map<Id,ContractLineItem> caseMasterProductContractLineItems = new Map<Id,ContractLineItem>();
                    Map<Id,ContractLineItem> validContractLineItemsMap = new Map<Id,ContractLineItem>();
                    for(ContractLineItem lineItemVar : serviceContractVar.ContractLineItems){
                        if( caseVar.CreatedDate >= lineItemVar.SBQQSC__SubscriptionStartDate__c && caseVar.CreatedDate <= lineItemVar.End_Terminated_Date__c && caseSalesProductNames.contains( lineItemVar.SBQQSC__ProductName__c) ){
                            
                            caseMasterProductContractLineItems.put( lineItemVar.Id,lineItemVar );
                            validContractLineItemsMap.put( lineItemVar.Id,lineItemVar );
                        }
                            
                    }
                    // if  case sales product matches contract line item's product  , the add their service packs
                    if( caseMasterProductContractLineItems.keyset().size() > 0 ){
                        for(ContractLineItem lineItemVar : serviceContractVar.ContractLineItems){
                            if( caseMasterProductContractLineItems.keyset().contains(lineItemVar.SBQQSC__RequiredById__c) ){
                                validContractLineItemsMap.put(lineItemVar.Id,lineItemVar);
                            }
                        }
                        for(ContractLineItem lineItemVar : serviceContractVar.ContractLineItems){
                            if( validContractLineItemsMap.keyset().contains(lineItemVar.SBQQSC__RequiredById__c) ){
                                validContractLineItemsMap.put(lineItemVar.Id,lineItemVar);
                            } 
                        }
                        system.debug('validContractLineItemsMap '+ validContractLineItemsMap);
                        system.debug('validContractLineItemsMap size() ' + validContractLineItemsMap.size() );
                        Integer i=0;
                        for(Id lineItemId : validContractLineItemsMap.keyset() ){
                            ContractLineItem lineItemVar = validContractLineItemsMap.get( lineItemId );
                            system.debug('Line Items ' + i + ' ' + lineItemVar);
                            i++;
                            if( CONTRACT_LINEITEM_SERVICE_CATEGORY.contains(lineItemVar.Category__c) && !String.isEmpty(lineItemVar.Entitlement_Case_Type__c) && !String.isEmpty(lineItemVar.Entitlement_Priority__c) ){
                                if( !caseMasterProductContractLineItems.keyset().contains(lineItemVar.SBQQSC__RequiredById__c) &&  (lineItemVar.Entitlement_Case_Type__c == 'All' || lineItemVar.Entitlement_Case_Type__c.contains(caseRecordType) )  &&  (lineItemVar.Entitlement_Priority__c == 'All' || lineItemVar.Entitlement_Priority__c.contains(caseVar.Priority)) ){
                                    Case_Entitlements__c caseEntitleMent = new Case_Entitlements__c(Case__c=caseVar.Id,Contract_Line_Item__c=lineItemVar.Id);
                                    caseEntitlements.add(caseEntitleMent);
                                }
                            }
                        
                        }
                    }
                }
            }
        }
        catch( Exception e){
            system.debug('It is just Data issue ' + e.getCause() + ' ' + e.getMessage() );
            system.debug('It is just Data issue ' + e.getCause() + ' ' + e.getStackTraceString() );
        }
        system.debug('caseEntitlements '+ caseEntitlements);
        if( caseEntitlements.size() > 0){
            try{ 
                insert caseEntitlements;
            }
            catch( Exception e){
               
                system.debug( 'Exception details ' + e.getCause() + e.getMessage() + ' '+ e.getStackTraceString());
                Error_Log__c errLog = T1_ErrorLogService.createErrorLog( e, caseIds, 'Apex Class',  'T1_CaseEntitlementService');
                insert errLog;
            }
    
        }
    }

    public static Map<Id,Schema.RecordTypeInfo> getCaseRecordTypeMap( ){
        return Schema.getGlobalDescribe().get('Case').getDescribe().getRecordTypeInfosById();
    }

    public static List<ServiceContract> getServiceContractByAccountId( Set<Id> accountIds, Set<String> salesProductNameSet ){
        return [ SELECT Name,AccountId,StartDate,EndDate,(SELECT SBQQSC__ProductName__c,SBQQSC__RequiredById__c,SBQQSC__SubscriptionStartDate__c,End_Terminated_Date__c,Category__c,Entitlement_Case_Type__c,Entitlement_Priority__c FROM ContractLineItems WHERE Category__c = :CONTRACT_LINEITEM_SERVICE_CATEGORY OR SBQQSC__ProductName__c IN :salesProductNameSet) FROM ServiceContract WHERE AccountId IN :accountIds ];
    }


    public static List<Shared_Entitlements__c> getSourceAccountIds( Set<Id> accountIds ){
        return [ SELECT Active__c,Source_Account__c,Target_Account__c FROM Shared_Entitlements__c WHERE Target_Account__c IN :accountIds AND Active__c = true ];
    } 

    

    public static List<Product_Mapping__c> getProductMappingByServiceProduct( Set<String> productNames ){
        return [ SELECT Sales_Product__c,Service_Product__c FROM Product_Mapping__c WHERE Service_Product__c IN :productNames ];
    }

    

    public static List<Case> queryCaseById( set<Id> caseIds ){
        return [ SELECT AccountId,RecordTypeId,Case_Record_Type_Name__c,CreatedDate,Customer_Product__c,Priority FROM Case WHERE ID IN :caseIds ];
    }

    public static List<Case_Entitlements__c> getCaseEntitlementsByCaseId( set<Id> caseIds ){
        return [ SELECT Case__c FROM Case_Entitlements__c WHERE Case__c IN :caseIds ];
    }

}