unpackaged/main/default/objects/Case/fields/Development_Status__c.field-meta.xml
<CustomField>
    <fullName>Development_Status__c</fullName>
    <label>Development Status</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Fix_Version__c.field-meta.xml
<CustomField>
    <fullName>Fix_Version__c</fullName>
    <description>Synched Jira field - to indicate the version the issue is fixed in.</description>
    <label>Fix Version</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Resolution__c.field-meta.xml
<CustomField>
    <fullName>Resolution__c</fullName>
    <label>Resolution</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Case/recordTypes/Question.recordType-meta.xml
<RecordType>
    <fullName>Question</fullName>
    <active>true</active>
    <businessProcess>Product Support Process</businessProcess>
    <description>Select this to log a Question Case</description>
    <label>I have a Question</label>
</RecordType>

unpackaged/main/default/objects/Jira_Dev_Issue__c/Jira_Dev_Issue__c.object-meta.xml
<CustomObject>
    <description>Link to one or more Jira Dev Issues and Service Cloud</description>
    <label>Jira Dev Issue</label>
    <nameField>
        <label>Jira Dev Issue Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jira Dev Issues</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Jira_Dev_Issue__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Jira Dev Issues</relationshipLabel>
    <relationshipName>Jira_Dev_Issues</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Jira_Dev_Issue__c/fields/Fix_Version__c.field-meta.xml
<CustomField>
    <fullName>Fix_Version__c</fullName>
    <label>Fix Version</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Jira_Dev_Issue__c/fields/Issue_Type__c.field-meta.xml
<CustomField>
    <fullName>Issue_Type__c</fullName>
    <description>Jira Issue Type, (eg Bug, Story)</description>
    <label>Issue Type</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Jira_Dev_Issue__c/fields/Resolution__c.field-meta.xml
<CustomField>
    <fullName>Resolution__c</fullName>
    <description>Resolution Jira Dev Issue</description>
    <label>Resolution</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Jira_Dev_Issue__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of individual Jira Dev Issue</description>
    <label>Status</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Jira_Dev_Project_Prefix__c/Jira_Dev_Project_Prefix__c.object-meta.xml
<CustomObject>
    <description>The prefix of the Issue ID that denotes the Project to be included</description>
    <label>Jira Dev Project Prefix</label>
    <nameField>
        <label>Jira Dev Project Prefix</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jira Dev Project Prefix</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Jira_Dev_Status__c/Jira_Dev_Status__c.object-meta.xml
<CustomObject>
    <label>Jira Dev Status</label>
    <nameField>
        <label>Jira Dev Status Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jira Dev Status</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/classes/Jira_Dev_IssueTriggerHandler.cls
public class Jira_Dev_IssueTriggerHandler {

    static public void onAfterInsert(Jira_Dev_Issue__c[] newJDIs) {
        updateCaseDevStatus(newJDIs);
        completeMilestones(newJDIs);
    }

    static public void onAfterUpdate(Jira_Dev_Issue__c[] updatedJDIs, Map<ID, Jira_Dev_Issue__c> oldMap) {
        updateCaseDevStatus(updatedJDIs);
    }

    static public void onAfterDelete(Jira_Dev_Issue__c[] updatedJDIs) {
        updateCaseDevStatus(updatedJDIs);
    }

    static public void updateCaseDevStatus(Jira_Dev_Issue__c[] newJDIs) {
    
            // get the list of Status values and their sequence
            Map<String, Integer> devStat = new Map<String, Integer>();
            for (Jira_Dev_Status__c jds : [Select Name, Sequence__c From Jira_Dev_Status__c ]){
                devStat.put(jds.name, Integer.valueof(jds.Sequence__c));
            }

            // get the list of Project Prefixes
            Map<String, String> devPP = new Map<String, String>();
            for (Jira_Dev_Project_Prefix__c jdpp : [Select Name From Jira_Dev_Project_Prefix__c ]){
                devPP.put(jdpp.name, jdpp.name);
            }

            String newcaseDevStatus = '';
            String currentcaseDevStatus = '';

            //build the list of affected Cases
            list <case> lcases = new list<case>(); // to be updated
            set<Id> caseIds = new set<Id>(); // list of Case Id's related to updated Jira Dev Issues
            for(Jira_Dev_Issue__c jdi : newJDIs){
                    caseIds.add(jdi.case__c); 
            }

            if (caseIds.isEmpty()){
                return;
            }

            for (case [] arrCase : [SELECT Id, 
                                            Development_Status__c 
                                FROM case 
                                    WHERE Status <> 'Resolved' and Status <> 'Closed' and Id IN :caseIds]){      // an array of Cases based on the ID's to be updated 
                for (Case sCase : arrCase){ // Update the field for the Case to be updated and add it to the Update List
                    currentcaseDevStatus = sCase.Development_Status__c;
                    //process each related Jira Dev Issue
                    list<String> devStatuses = new list<String>();
                    newcaseDevStatus = '';
                    Integer iCount = 0; 
                    Integer intIndex = 0;
                    String sPrefix = '';
                    
                    for (Jira_Dev_Issue__c jdi2 : [select name, issue_type__c, fix_version__c, status__c, resolution__c from jira_dev_issue__c
                                                where case__c = :sCase.Id])
                    {
                        // See if this issue is within one of the desired Projects
                        intIndex = 0;
                        sPrefix = '';
                        intIndex = jdi2.name.indexOf('-');
                        
                        if (intIndex <= 0){
                            continue;    
                        }
                        sPrefix = jdi2.name.left(intIndex + 1);
                        if (sPrefix == ''){
                            continue;
                        }
                        if (!devPP.containsKey(sPrefix)){
                            continue;
                        }
                        
                        iCount ++;
                        //determine the new status
                        if((jdi2.issue_type__c == 'Support Triage' || jdi2.issue_type__c == 'R&D Triage' || jdi2.issue_type__c == 'Question')
                            && jdi2.Status__c == 'Closed'){
                            newcaseDevStatus = 'Completed';
                        }
                        else if(jdi2.resolution__c == 'Cancelled'){
                            newcaseDevStatus = 'Completed';
                        }
                        else if(jdi2.issue_type__c == 'Support Triage'){
                            newcaseDevStatus = 'Under Review';
                        }
                        else if(jdi2.issue_type__c == 'R&D Triage'){
                            newcaseDevStatus = 'Under Investigation';
                        }
                        else if(jdi2.status__c == 'Closed' || jdi2.status__c == 'Release Merge' || jdi2.status__c == 'Release QA'){
                            newcaseDevStatus = 'Awaiting Release';
                        }
                        else if(jdi2.fix_version__c > '' || jdi2.status__c == 'Development Complete' || jdi2.status__c == 'ITQA'){
                            newcaseDevStatus = 'Planned for Release';
                        }
                        else if(jdi2.issue_type__c == 'Bug' || jdi2.issue_type__c == 'User Story' ){
                            newcaseDevStatus = 'Requires a Software Change';
                        }
                        else if(jdi2.issue_type__c == 'Question'){
                            newcaseDevStatus = 'Requires Research';
                        }
                    
                        if (newcaseDevStatus > ''){
                            Integer intSeq = devStat.Get(newcaseDevStatus);
                            devStatuses.add(string.valueOf(intSeq) + ' ' + newcaseDevStatus);
                        }
                    }

                    if (iCount == 0){
                        sCase.Development_Status__c = '';
                        lcases.add(sCase);
                    }

                    // now get the earliest status in the list
                    if (!devStatuses.isEmpty()){
                        devStatuses.sort();
                        String finalStatus = devStatuses[0]; // get the first string
                        String theStatus = finalStatus.substring(finalStatus.indexof(' ')+1); // get rid of the sequence
                        if (theStatus <> currentcaseDevStatus){
                            sCase.Development_Status__c = theStatus;
                            lcases.add(sCase);
                        }
                    }
                }
            }  
    
            if (!lcases.isEmpty()){
                update lcases;
            }
    }
    static public void completeMilestones(Jira_Dev_Issue__c[] newJDIs) {
            // Cannot be a portal user
            if (UserInfo.getUserType() == 'Standard' || UserInfo.getUserType() == 'PowerPartner') {
                DateTime completionDate = System.now();
                String milestoneType = '';
                List<Id> caseIds = new List<Id>();
                for (Jira_Dev_Issue__c jdi : newJDIs) {
                    caseIds.add(jdi.case__c);
                }
                if (caseIds.isEmpty() == false){
                    List<Case> caseList = [Select c.Id, c.Status, c.EntitlementId, c.SlaStartDate, c.SlaExitDate
                        From Case c
                        Where c.Id IN :caseIds];
                    if (caseList.isEmpty() == false){
                        List<Id> updateCases = new List<Id>();
                        for (Case caseObj:caseList) {
                            if  ((caseObj.EntitlementId != null)&&
                                (caseObj.SlaStartDate <= completionDate)&&
                                (caseObj.SlaStartDate != null)&&
                                (caseObj.SlaExitDate == null)&&
                                (caseObj.Status != 'Resolved') && //only update if Case is still open
                                (caseObj.Status != 'Closed')){
                                updateCases.add(caseObj.Id);
                                milestoneType = 'Update';
                            }
                        }

                        if (updateCases.isEmpty() == false ){
                            if (milestoneType  == 'Update')               
                                milestoneUtils.completeMilestone(updateCases, 'Update', completionDate);
                            
                        }
                    }
                }
            }
    }
}