unpackaged/main/default/objects/Case/fields/Exit_Entitlement_Process__c.field-meta.xml
<CustomField>
    <fullName>Exit_Entitlement_Process__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used to determine when the Entitlement process will be exited. This is required to overcome an issue with Competing Milestones after a Case has been closed.</description>
    <label>Exit Entitlement Process</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Final_Resolution_Target__c.field-meta.xml
<CustomField>
    <fullName>Final_Resolution_Target__c</fullName>
    <description>Final Resolution Target date from Case Milestone.  Updated via Flow and Process.</description>
    <label>Final Resolution Target</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Interim_Resolution_Target__c.field-meta.xml
<CustomField>
    <fullName>Interim_Resolution_Target__c</fullName>
    <description>Target Date from Interim Resolution Milestone. Updated from Flow called by Process</description>
    <label>Interim Resolution Target</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/classes/CaseMilestoneUtils.cls
public class CaseMilestoneUtils {

    @future
    public static void copyTargetDate(List<Id> caseIds) {

            List<Case> casesToUpdate = new List<Case>();

            for (CaseMilestone milestone : [
                select CaseId,
                    MilestoneType.Name,
                    TargetDate
                from CaseMilestone
                where CaseId in :caseIds and
                    MilestoneType.Name = 'Final Resolution'
            ]) {
                casesToUpdate.add(new Case(
                    Id = milestone.CaseId,
                    Final_Resolution_Target__c = milestone.TargetDate
                ));
            }

            if (!casesToUpdate.isEmpty()) {
                update casesToUpdate;
            }
        
            List<Case> casesToUpdate2 = new List<Case>();

            for (CaseMilestone milestone : [
                select CaseId,
                    MilestoneType.Name,
                    TargetDate
                from CaseMilestone
                where CaseId in :caseIds and
                    MilestoneType.Name = 'Interim Resolution'
            ]) {
                casesToUpdate2.add(new Case(
                    Id = milestone.CaseId,
                    Interim_Resolution_Target__c = milestone.TargetDate
                ));
            }

            if (!casesToUpdate2.isEmpty()) {
                update casesToUpdate2;
            }
    }

    @future
    public static void setExitEntitlement(List<Id> caseIds, Boolean setTo) {
            List<Case> casesToUpdate = new List<Case>();

            for (Case c: [
                select Id,
                    Exit_Entitlement_Process__c
                    from Case
                where Id in :caseIds
            ]) {
                if (c.Exit_Entitlement_Process__c <> setTo){
                    casesToUpdate.add(new Case(
                        Id = c.Id,
                        Exit_Entitlement_Process__c = setTo
                    ));
                }
            }

            if (!casesToUpdate.isEmpty()) {
                update casesToUpdate;
            }
        
    
    }
}