unpackaged/main/default/objects/Asset/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Assets</relationshipLabel>
    <relationshipName>Current_Licences_ASMs</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Asset/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Earnie IQ</fullName>
            </value>
            <value>
                <fullName>Escrow</fullName>
            </value>
            <value>
                <fullName>Health Metrics</fullName>
            </value>
            <value>
                <fullName>IT Glovebox</fullName>
            </value>
            <value>
                <fullName>ScanWatcher</fullName>
            </value>
            <value>
                <fullName>TechnologyOne Adaptive Solutions</fullName>
            </value>
            <value>
                <fullName>TechnologyOne ADF</fullName>
            </value>
            <value>
                <fullName>TechnologyOne Breakout Packs</fullName>
            </value>
            <value>
                <fullName>TechnologyOne Corporate Performance Management</fullName>
            </value>
            <value>
                <fullName>TechnologyOne CPM External Systems Connectors</fullName>
            </value>
            <value>
                <fullName>TechnologyOne ECM</fullName>
            </value>
            <value>
                <fullName>TechnologyOne ECR External Systems</fullName>
            </value>
            <value>
                <fullName>TechnologyOne Enterprise Asset Management</fullName>
            </value>
            <value>
                <fullName>TechnologyOne Enterprise Cash Receipting</fullName>
            </value>
            <value>
                <fullName>TechnologyOne Fax Gateway</fullName>
            </value>
            <value>
                <fullName>TechnologyOne Financials</fullName>
            </value>
            <value>
                <fullName>TechnologyOne Fleet Solution</fullName>
            </value>
            <value>
                <fullName>TechnologyOne HR and Payroll</fullName>
            </value>
            <value>
                <fullName>TechnologyOne Mobile</fullName>
            </value>
            <value>
                <fullName>TechnologyOne Performance Planning</fullName>
            </value>
            <value>
                <fullName>TechnologyOne PLUS</fullName>
            </value>
            <value>
                <fullName>TechnologyOne Property</fullName>
            </value>
            <value>
                <fullName>TechnologyOne Publisher</fullName>
            </value>
            <value>
                <fullName>TechnologyOne R &amp; D</fullName>
            </value>
            <value>
                <fullName>TechnologyOne Services Only</fullName>
            </value>
            <value>
                <fullName>TechnologyOne Solution Fee</fullName>
            </value>
            <value>
                <fullName>TechnologyOne Solution Template</fullName>
            </value>
            <value>
                <fullName>TechnologyOne Stock Usage</fullName>
            </value>
            <value>
                <fullName>TechnologyOne Student Management</fullName>
            </value>
            <value>
                <fullName>TechnologyOne Supply Chain Management</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/PCSM_Visit_Cyc__c/PCSM_Visit_Cyc__c.object-meta.xml
<CustomObject>
    <description>Products &amp; Services including SDM scheduled visits, Executive Response engagements</description>
    <label>Products &amp; Services</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Visit Cycle</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Products &amp; Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/PCSM_Visit_Cyc__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Account_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/PCSM_Visit_Cyc__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <description>Products list from SRS ASMs Modules</description>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Additional Cloud - Different Anniversary Date</fullName>
            </value>
            <value>
                <fullName>Application Managed Services</fullName>
            </value>
            <value>
                <fullName>Customer Success</fullName>
            </value>
            <value>
                <fullName>EmpLive</fullName>
            </value>
            <value>
                <fullName>Escrow</fullName>
            </value>
            <value>
                <fullName>Executive Response</fullName>
            </value>
            <value>
                <fullName>Health Metrics</fullName>
            </value>
            <value>
                <fullName>IT Glovebox</fullName>
            </value>
            <value>
                <fullName>Kofax Capture</fullName>
            </value>
            <value>
                <fullName>My Recruit Online</fullName>
            </value>
            <value>
                <fullName>Roster Live</fullName>
            </value>
            <value>
                <fullName>ScanWatcher</fullName>
            </value>
            <value>
                <fullName>Tanda</fullName>
            </value>
            <value>
                <fullName>TechnologyOne Adaptive Solutions</fullName>
            </value>
            <value>
                <fullName>TechnologyOne Additional Breakout Packs</fullName>
            </value>
            <value>
                <fullName>TechnologyOne ADF</fullName>
            </value>
            <value>
                <fullName>TechnologyOne Application Submission Management</fullName>
            </value>
            <value>
                <fullName>TechnologyOne Breakout Packs</fullName>
            </value>
            <value>
                <fullName>TechnologyOne Business Process Management</fullName>
            </value>
            <value>
                <fullName>TechnologyOne Cloud Storage (ECM)</fullName>
            </value>
            <value>
                <fullName>TechnologyOne Community Consultation (Local Govt)</fullName>
            </value>
            <value>
                <fullName>TechnologyOne Community Consultation &amp; Engagement</fullName>
            </value>
            <value>
                <fullName>TechnologyOne Community Engagement</fullName>
            </value>
            <value>
                <fullName>Technology One Contracts</fullName>
            </value>
            <value>
                <fullName>TechnologyOne Corporate Performance Management</fullName>
            </value>
            <value>
                <fullName>TechnologyOne CPM External Systems Connectors</fullName>
            </value>
            <value>
                <fullName>TechnologyOne Custom Stakeholder Management</fullName>
            </value>
            <value>
                <fullName>TechnologyOne ECM</fullName>
            </value>
            <value>
                <fullName>TechnologyOne ECR External Systems</fullName>
            </value>
            <value>
                <fullName>TechnologyOne Enterprise Asset Management</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/PCSMVisitModules.cls
public with sharing class PCSMVisitModules 
{
    private PCSM_Visit_Cyc__c productRecord;
    public List<Asset> modules {get;set;}
    
    public PCSMVisitModules(ApexPages.StandardController controller)
    {
        //controller.addFields(new String[]{'id', 'Account__c', 'Product__c'});
        PCSM_Visit_Cyc__c pcsmVisit = (PCSM_Visit_Cyc__c) controller.getRecord();
        this.productRecord = [Select id, account__c, product__c from PCSM_Visit_Cyc__c
                            where id =: pcsmVisit.id];
            
        this.modules = [Select a.Product__c, a.Product2.Family, a.Product2.ProductCode, a.Product2.Name, a.Product2Id, a.Name, a.Id, 
        a.Description, a.AccountId, a.Status From Asset a
                where a.accountId =: productRecord.Account__c
                and a.product__c =: productRecord.Product__c];        
    }

}