unpackaged/main/default/objects/Service_Only_Consulting_Request__c/Service_Only_Consulting_Request__c.object-meta.xml
<CustomObject>
    <description>Resource/Rate information for Service Only/Consulting Request Opportunity type</description>
    <label>Service Only/Consulting Request</label>
    <nameField>
        <displayFormat>R-{0000000}</displayFormat>
        <label>Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Only/Consulting Request</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Service_Only_Consulting_Request__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Service Only/Consulting Request</relationshipLabel>
    <relationshipName>Service_Only_Consulting_Request</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Service_Only_Consulting_Request__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Resource</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Technology One Employee</value>
        </filterItems>
        <infoMessage>Search Technology One Employees</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Service Only/Consulting Request</relationshipLabel>
    <relationshipName>Service_Only_Consulting_Request</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Survey_Response_Opportunity__c/Survey_Response_Opportunity__c.object-meta.xml
<CustomObject>
    <description>Used to link GetFeedback survey results to Salesforce Service Only / Consulting Request Opportunities</description>
    <label>Survey Response Opportunity</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Survey Response Opportunities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Survey_Response_Opportunity__c/fields/Opportunity_Number__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Number__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Survey Response Opportunities</relationshipLabel>
    <relationshipName>Survey_Response_Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Survey_Response_Opportunity__c/fields/Resources__c.field-meta.xml
<CustomField>
    <fullName>Resources__c</fullName>
    <description>Populate Resource Names from Services Only/Consulting Request</description>
    <label>Resources</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/CR_Resources.cls
public class CR_Resources {

    public void InsertResources (Map<Id, Survey_Response_Opportunity__c> oppMap){
 
    Set<Id> SurveyIds;  
    List<Survey_Response_Opportunity__c> SurveyValues;
    SurveyIds = oppMap.keySet();
    SurveyValues = oppMap.values();
    
    Id SvId =  SurveyValues.get(0).Id  ;                  
   	Id oppId =  SurveyValues.get(0).Opportunity_Number__c  ;
        
    String ResourceNames ='';
   
      If (oppId !=Null) {
      AggregateResult[]   CR = [Select Resource__r.Name ResourceName From Service_Only_Consulting_Request__c
              Where Opportunity__c =: oppId 
              Group by Resource__r.Name];
        For (AggregateResult I: CR) {
           ResourceNames = (String)(I.get('ResourceName'))  + '; ' + ResourceNames ;
        }
 	    
        Survey_Response_Opportunity__c SR;
        
        try {
            SR = [Select Resources__c from Survey_Response_Opportunity__c where id =: SvId Limit 1];
            SR.Resources__c = ResourceNames; 
            Update SR;
           
        } catch(DmlException e) {
           System.debug('An unexpected error has occurred: ' + e.getMessage());
        }  
      }        
   }     
}