unpackaged/main/default/objects/Increase_Rate_Types__c/Increase_Rate_Types__c.object-meta.xml
<CustomObject>
    <label>Increase Rate Type</label>
    <nameField>
        <label>Increase Rate Types Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Increase Rate Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ServiceContract/fields/Auto_Amendment_Control__c.field-meta.xml
<CustomField>
    <fullName>Auto_Amendment_Control__c</fullName>
    <formula>If( EndDate &gt;= TODAY() &amp;&amp;(Term/12) &gt; No_of_Auto_Ammendments__c + 1,FALSE,TRUE)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Auto Amendment Control</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/ServiceContract/fields/Auto_Amendment_Override_Date__c.field-meta.xml
<CustomField>
    <fullName>Auto_Amendment_Override_Date__c</fullName>
    <label>Auto Amendment Override Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/ServiceContract/fields/Deal_Type__c.field-meta.xml
<CustomField>
    <fullName>Deal_Type__c</fullName>
    <label>Deal Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Deal_Type</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ServiceContract/fields/Initial_Period_Increase_Rate__c.field-meta.xml
<CustomField>
    <fullName>Initial_Period_Increase_Rate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Initial Period Increase Rate</label>
    <referenceTo>Increase_Rate_Types__c</referenceTo>
    <relationshipLabel>Service Contracts (Initial Period Increase Rate)</relationshipLabel>
    <relationshipName>Service_Contracts1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ServiceContract/fields/Start_End_Date_Difference__c.field-meta.xml
<CustomField>
    <fullName>Start_End_Date_Difference__c</fullName>
    <description>Used to location contracts with End Date - Start Date &gt; 12 months</description>
    <formula>EndDate - StartDate</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Start End Date Difference</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/ServiceContract/fields/X28_Days_before_Anniversary__c.field-meta.xml
<CustomField>
    <fullName>X28_Days_before_Anniversary__c</fullName>
    <formula>IF(
  AND(
    MONTH(  StartDate ) = 2,
    DAY( StartDate ) = 29,
    NOT( 
      OR( 
        MOD( YEAR( StartDate ), 400 ) = 0, 
        AND( 
          MOD( YEAR( StartDate ), 4 ) = 0,
          MOD( YEAR( StartDate ), 100 ) != 0
        )
      )
    ) 
  ),
  DATE( YEAR(StartDate) + IF(No_of_Auto_Ammendments__c  = null,1,No_of_Auto_Ammendments__c + 1), 3, 1) - 28,
  DATE( YEAR(StartDate) + IF(No_of_Auto_Ammendments__c  = null,1,No_of_Auto_Ammendments__c + 1), MONTH(StartDate), DAY(StartDate)) - 28
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>28 Days before Anniversary</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/globalValueSets/Deal_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Perpetual</fullName>
    </customValue>
    <customValue>
        <fullName>Saas</fullName>
    </customValue>
    <customValue>
        <fullName>Term</fullName>
    </customValue>
    <customValue>
        <fullName>Subscription</fullName>
    </customValue>
    <customValue>
        <fullName>Perpetual on Cloud</fullName>
    </customValue>
    <customValue>
        <fullName>AMS</fullName>
    </customValue>
    <masterLabel>Deal Type</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/T1_AutoAmendmentBatch.cls
/*******************************************************************************************************
* Class Name      	: T1_AutoAmendmentBatch
* Description		: Batch Class for Auto Amendment - System.schedule('Auto Amendment Batch', '0 0 * * * ?', new T1_AutoAmendmentBatch());
* Author          	: Simplus - Gerald Arzadon	
* Created On      	: 2-12-2020
* -----------------------------------------------------------------------------------------------------
* Developer				Date				Description
* -----------------------------------------------------------------------------------------------------
* Gerald Arzadon    	2-12-2020			Initial version 
* Yi Zhang              04/03/2021          Amended query to include contracts for Flip to SaaS & Perpetual on Cloud
******************************************************************************************************/
global class T1_AutoAmendmentBatch implements Database.Batchable<sObject>, Database.AllowsCallouts, Schedulable {
    private Id ServiceContractId;
    global T1_AutoAmendmentBatch(){}
    global T1_AutoAmendmentBatch(Id ServiceContractId){
        This.ServiceContractId = ServiceContractId;
    }
    
    global Database.QueryLocator start(Database.BatchableContext bc) {
        String query = ' SELECT Id,Initial_Period_Increase_Rate__r.Name ' +
        ' FROM ServiceContract ' +
        ' WHERE Initial_Period_Increase_Rate__c != null ' +
        ' AND (X28_Days_before_Anniversary__c <= TODAY OR Auto_Amendment_Override_Date__c <= TODAY)' +
        ' AND Auto_Amendment_Control__c = FALSE ' +
        ' AND Initial_Period_Increase_Rate__r.Name != \'NOINCREASE\'' +
        ' AND (' +
        ' Deal_Type__c = \'Term\' ' +
        ' OR (Deal_Type__c = \'SaaS\' AND SBQQSC__Quote__r.Transaction_Type__c = \'Flip to SaaS\' AND Start_End_Date_Difference__c > 365)' +
        ' OR (Deal_Type__c IN (\'Perpetual on Cloud\') AND Start_End_Date_Difference__c > 365)' +
        ' )';
        If(ServiceContractId <> null){
            query += ' AND Id = \''+ServiceContractId+'\'';
        }
        return Database.getQueryLocator(query);
    }
    
    
    global void execute(Database.BatchableContext bc, List<ServiceContract> scope){
        System.debug(LoggingLevel.ERROR, 'SCOPE: ' + scope);
        Set<String> contractIds = new Set<String>();
        for(ServiceContract ServCont :scope){
            contractIds.add(ServCont.Id); 
        }
        System.debug(LoggingLevel.ERROR,'CONTRACT IDS ' + contractIds);
        System.debug(LoggingLevel.ERROR, 'ENTERING AUTO AMENDMENTS');
        // PROCESS RECORDS FOR AUTO AMENDMENT
        T1_ContractAmender.doAutoAmendment(contractIds);
    }
    
    global void finish(Database.BatchableContext bc){}
    
    // SCHEDULABLE JOB TO SCHEDULE THIS JOB
    global void execute(SchedulableContext ctx) {
        Database.executeBatch(new T1_AutoAmendmentBatch(),1);
    }
}