unpackaged/main/default/objects/Opportunity/fields/Pricebook_Overridden__c.field-meta.xml
<CustomField>
    <fullName>Pricebook_Overridden__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Pricebook Overridden</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/OpportunityGroupedProduct__c/OpportunityGroupedProduct__c.object-meta.xml
<CustomObject>
    <description>Opportunity Grouped Product from Opportunity Item Spit</description>
    <label>Opportunity Grouped Product</label>
    <nameField>
        <label>Opportunity Grouped Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Grouped Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/OpportunityGroupedProduct__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <inlineHelpText>Grouped amount from Opportunity Item Split</inlineHelpText>
    <label>Product Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/OpportunityGroupedProduct__c/fields/AUD_Amount__c.field-meta.xml
<CustomField>
    <fullName>AUD_Amount__c</fullName>
    <description>Calculate Product Amount from Dated Conversion Rate</description>
    <inlineHelpText>Calculate Product Amount from Dated Conversion Rate</inlineHelpText>
    <label>AUD Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/OpportunityGroupedProduct__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Grouped Products</relationshipLabel>
    <relationshipName>Opportunity_Grouped_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/OpportunityItemSplit__c/OpportunityItemSplit__c.object-meta.xml
<CustomObject>
    <description>Opportunity Item Split from OpportunityLineItem and OpportunityModuleItem based on GL Product Connector Percentage in Product2 mapping table</description>
    <label>Opportunity Item Split</label>
    <nameField>
        <label>OpportunityItem Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Item Splits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/OpportunityItemSplit__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Product Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/OpportunityItemSplit__c/fields/AUD_Amount__c.field-meta.xml
<CustomField>
    <fullName>AUD_Amount__c</fullName>
    <description>Calculate Product Amount from dated conversion rate</description>
    <label>AUD Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/OpportunityItemSplit__c/fields/Connector_Percent__c.field-meta.xml
<CustomField>
    <fullName>Connector_Percent__c</fullName>
    <label>Connector Percent</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

unpackaged/main/default/objects/OpportunityItemSplit__c/fields/GL_Product_Name__c.field-meta.xml
<CustomField>
    <fullName>GL_Product_Name__c</fullName>
    <label>Product Name</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>3rd Party</fullName>
            </value>
            <value>
                <fullName>Application Development Framework</fullName>
            </value>
            <value>
                <fullName>Asset Management</fullName>
            </value>
            <value>
                <fullName>Business Intelligence</fullName>
            </value>
            <value>
                <fullName>Business Process Management</fullName>
            </value>
            <value>
                <fullName>Corporate Performance Management</fullName>
            </value>
            <value>
                <fullName>Enterprise Content Management</fullName>
            </value>
            <value>
                <fullName>Financials</fullName>
            </value>
            <value>
                <fullName>HR &amp; Payroll</fullName>
            </value>
            <value>
                <fullName>Inactive Product</fullName>
            </value>
            <value>
                <fullName>Not in Use</fullName>
            </value>
            <value>
                <fullName>Performance Planning</fullName>
            </value>
            <value>
                <fullName>Property</fullName>
            </value>
            <value>
                <fullName>Solutions</fullName>
            </value>
            <value>
                <fullName>Spatial</fullName>
            </value>
            <value>
                <fullName>Stakeholder Management</fullName>
            </value>
            <value>
                <fullName>Student Management</fullName>
            </value>
            <value>
                <fullName>Supply Chain Management</fullName>
            </value>
            <value>
                <fullName>T1 Cloud</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/OpportunityItemSplit__c/fields/Indicator__c.field-meta.xml
<CustomField>
    <fullName>Indicator__c</fullName>
    <label>Indicator</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Connector Product Price</fullName>
            </value>
            <value>
                <fullName>GL Product Price</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/OpportunityItemSplit__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Item Splits</relationshipLabel>
    <relationshipName>OpportunityItemSplits</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/OpportunityItemSplit__c/fields/Product2__c.field-meta.xml
<CustomField>
    <fullName>Product2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Opportunity Item Splits</relationshipLabel>
    <relationshipName>OpportunityItemSplits</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/OpportunityItemSplit__c/fields/TotalPrice__c.field-meta.xml
<CustomField>
    <fullName>TotalPrice__c</fullName>
    <description>Total Price Before Split</description>
    <label>Total Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/OpportunityLineItem/fields/Pricebook_Overridden__c.field-meta.xml
<CustomField>
    <fullName>Pricebook_Overridden__c</fullName>
    <formula>Opportunity.Pricebook_Overridden__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Pricebook Overridden</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/OpportunityModuleItem__c/OpportunityModuleItem__c.object-meta.xml
<CustomObject>
    <description>Module Items from SRS Price Book</description>
    <label>Opportunity Module Item</label>
    <nameField>
        <label>OpportunityModule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Module Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/OpportunityModuleItem__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <description>OPPORTUNITY ID</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>OpportunityModuleItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/OpportunityModuleItem__c/fields/Product2__c.field-meta.xml
<CustomField>
    <fullName>Product2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>read only permission for end users</description>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Opportunity Module Items</relationshipLabel>
    <relationshipName>Opportunity_Module_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/OpportunityModuleItem__c/fields/ProductCode__c.field-meta.xml
<CustomField>
    <fullName>ProductCode__c</fullName>
    <description>Product Code</description>
    <label>Product Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/OpportunityModuleItem__c/fields/TotalPrice__c.field-meta.xml
<CustomField>
    <fullName>TotalPrice__c</fullName>
    <description>Total Price - read only permission for end users</description>
    <label>Total Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Connector_GL_Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Connector_GL_Product_Name__c</fullName>
    <label>Connector Product</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>3rd Party</fullName>
            </value>
            <value>
                <fullName>Adapt</fullName>
            </value>
            <value>
                <fullName>Application Development Framework</fullName>
            </value>
            <value>
                <fullName>Application Managed Services</fullName>
            </value>
            <value>
                <fullName>Asset Management</fullName>
            </value>
            <value>
                <fullName>Business Intelligence</fullName>
            </value>
            <value>
                <fullName>Business Process Management</fullName>
            </value>
            <value>
                <fullName>Corporate Performance Management</fullName>
            </value>
            <value>
                <fullName>Enterprise Content Management</fullName>
            </value>
            <value>
                <fullName>Financials</fullName>
            </value>
            <value>
                <fullName>HR &amp; Payroll</fullName>
            </value>
            <value>
                <fullName>Inactive Product</fullName>
            </value>
            <value>
                <fullName>Mobility</fullName>
            </value>
            <value>
                <fullName>Not in Use</fullName>
            </value>
            <value>
                <fullName>Performance Planning</fullName>
            </value>
            <value>
                <fullName>Project Services</fullName>
            </value>
            <value>
                <fullName>Property</fullName>
            </value>
            <value>
                <fullName>Solutions</fullName>
            </value>
            <value>
                <fullName>Stakeholder Management</fullName>
            </value>
            <value>
                <fullName>Student Management</fullName>
            </value>
            <value>
                <fullName>Supply Chain Management</fullName>
            </value>
            <value>
                <fullName>T1 Cloud</fullName>
            </value>
            <value>
                <fullName>Human Resources and Payroll</fullName>
            </value>
            <value>
                <fullName>Technical Services</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Connector_Percent__c.field-meta.xml
<CustomField>
    <fullName>Connector_Percent__c</fullName>
    <label>Connector Percent</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/GL_Product_Name__c.field-meta.xml
<CustomField>
    <fullName>GL_Product_Name__c</fullName>
    <description>Product Name for revenue</description>
    <inlineHelpText>Product Name for revenue</inlineHelpText>
    <label>Product Name</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>3rd Party</fullName>
            </value>
            <value>
                <fullName>Adapt</fullName>
            </value>
            <value>
                <fullName>Application Development Framework</fullName>
            </value>
            <value>
                <fullName>Application Managed Services</fullName>
            </value>
            <value>
                <fullName>Asset Management</fullName>
            </value>
            <value>
                <fullName>Business Intelligence</fullName>
            </value>
            <value>
                <fullName>Business Process Management</fullName>
            </value>
            <value>
                <fullName>Corporate Performance Management</fullName>
            </value>
            <value>
                <fullName>DXP</fullName>
            </value>
            <value>
                <fullName>Enterprise Content Management</fullName>
            </value>
            <value>
                <fullName>Financials</fullName>
            </value>
            <value>
                <fullName>HR &amp; Payroll</fullName>
            </value>
            <value>
                <fullName>Inactive Product</fullName>
            </value>
            <value>
                <fullName>Mobility</fullName>
            </value>
            <value>
                <fullName>Not Allocated</fullName>
            </value>
            <value>
                <fullName>Not in Use</fullName>
            </value>
            <value>
                <fullName>Performance Planning</fullName>
            </value>
            <value>
                <fullName>Project Services</fullName>
            </value>
            <value>
                <fullName>Property</fullName>
            </value>
            <value>
                <fullName>Solutions</fullName>
            </value>
            <value>
                <fullName>Spatial</fullName>
            </value>
            <value>
                <fullName>Stakeholder Management</fullName>
            </value>
            <value>
                <fullName>Student Management</fullName>
            </value>
            <value>
                <fullName>Supply Chain Management</fullName>
            </value>
            <value>
                <fullName>T1 Cloud</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/OpportunityItemSplit.cls
public class OpportunityItemSplit {
     
     public void deleteItemSplit(Map<Id, Opportunity> oppMap){
 
      Set<Id> oppIds;  
      List<Opportunity> oppValues;
      oppIds = oppMap.keySet();
      oppValues = oppMap.values();
        
     //0. delete ItemSplits where Opportunity__c = oppIds
     List <OpportunityItemSplit__c> OppItemSplits = New List<OpportunityItemSplit__c>();              
     OppItemSplits = [SELECT Id FROM OpportunityItemSplit__c WHERE Opportunity__c =: oppIds]; 
       
      If (OppItemSplits.size()>0) {   
        Try {
     	  Delete OppItemSplits;            
         } Catch (DmlException e) {
           System.debug('An unexpected error has occurred: ' + e.getMessage());
 
         }
       }    
    }      
 
    public void deleteModuleItem(Map<Id, Opportunity> oppMap){
 
      Set<Id> oppIds;  
      List<Opportunity> oppValues;
      oppIds = oppMap.keySet();
      oppValues = oppMap.values();
        
     //0. delete ItemSplits where Opportunity__c = oppIds
     List <OpportunityModuleItem__c> OppModuleItem = New List<OpportunityModuleItem__c>();              
     OppModuleItem = [SELECT Id FROM OpportunityModuleItem__c WHERE Opportunity__c =: oppIds]; 
       
      If (OppModuleItem.size()>0) {   
        Try {
     	  Delete OppModuleItem;            
         } Catch (DmlException e) {
           System.debug('An unexpected error has occurred: ' + e.getMessage());
 
         }
       }    
    }      

    public void deleteGroupedProduct(Map<Id, Opportunity> oppMap){
 
      Set<Id> oppIds;  
      List<Opportunity> oppValues;
      oppIds = oppMap.keySet();
      oppValues = oppMap.values();
        
     //0. delete GroupedProduct where Opportunity__c = oppIds
     List <OpportunityGroupedProduct__c> OppGroupedProduct = New List<OpportunityGroupedProduct__c>();              
     OppGroupedProduct = [SELECT Id FROM OpportunityGroupedProduct__c WHERE Opportunity__c =: oppIds]; 
       
      If (OppGroupedProduct.size()>0) {   
        Try {
     	  Delete OppGroupedProduct;            
         } Catch (DmlException e) {
           System.debug('An unexpected error has occurred: ' + e.getMessage());
 
         }
       }    
    } 

    
   //Insert OpportunityLineItem data into OpportunityItemSplit Object
   // for Opportunity pricebookoverwritten = false 
    public void insertLineItemSplit(Map<Id, Opportunity> oppMap){
      Set<Id> oppIds = oppMap.keySet();   
      List<Opportunity> oppValues = oppMap.values();
        
    //0. Get data from OpportunityLineItem for pricebookoverwritten = false  
    List <OpportunityLineItem> OppLineItems = new List<OpportunityLineItem> ();
    OpportunityItemSplit__c[] ItemSplits = new OpportunityItemSplit__c[]{};



    Map<Id,  List <OpportunityLineItem>> OppLineItemsPerOpp = new Map<Id,  List <OpportunityLineItem>>();
    for(OpportunityLineItem oli:[SELECT Product2.GL_PRODUCT_NAME__C, ID, OPPORTUNITYID, PRODUCT2ID, PRODUCTCODE, Product2.NAME, TOTALPRICE, Product2.CONNECTOR_PERCENT__C, Product2.Connector_GL_Product_Name__c, CURRENCYISOCODE FROM OpportunityLineItem WHERE OPPORTUNITYID in: oppIds and PRICEBOOK_OVERRIDDEN__C = false and TOTALPRICE<>0])    {
        List <OpportunityLineItem> tempOppLineItems = new List<OpportunityLineItem> ();
        if(OppLineItemsPerOpp.containsKey(oli.OPPORTUNITYID)){
            tempOppLineItems = OppLineItemsPerOpp.get(oli.OPPORTUNITYID);
        }
        tempOppLineItems.add(oli);
        OppLineItemsPerOpp.put(oli.OPPORTUNITYID, tempOppLineItems);

    }


    For (Opportunity Lo: oppValues)  {   
      /*
      aug 3, 2018 move to a map outside loop

      OppLineItems = [SELECT Product2.GL_PRODUCT_NAME__C, ID, OPPORTUNITYID, PRODUCT2ID, PRODUCTCODE, Product2.NAME,
                    TOTALPRICE, Product2.CONNECTOR_PERCENT__C, 
                    Product2.Connector_GL_Product_Name__c, CURRENCYISOCODE 
        FROM OpportunityLineItem WHERE OPPORTUNITYID =: Lo.Id and PRICEBOOK_OVERRIDDEN__C = false and TOTALPRICE<>0];
     */
        if(OppLineItemsPerOpp.containsKey(Lo.Id)){
            OppLineItems = OppLineItemsPerOpp.get(Lo.Id);
        }

       //1. Get Dated Conversion Rate 
       Decimal Conversion_Rate = 1;
       If (Lo.CurrencyIsoCode <> 'AUD') {
           Date rateDate =  Date.newInstance(Lo.CloseDate.year(),Lo.CloseDate.month(),1);
           //call class cDatedConversionRate
           Conversion_Rate = cDatedConversionRate.getDatedConversionRate(Lo.CurrencyIsoCode, rateDate);  
    	}   
        
      For (OpportunityLineItem LI: OppLineItems)   { 
    
        Decimal Connector_Pnct = LI.Product2.CONNECTOR_PERCENT__C;
        If (Connector_Pnct == Null) {
            Connector_Pnct = 0 ;
        }
        
       //2. Create a ItemSplit record for original product 
       OpportunityItemSplit__c s1 = new OpportunityItemSplit__c ();
        s1.Indicator__c = 'Product Price';
        s1.Name = LI.Product2.NAME ;  
        s1.Opportunity__c = LI.OPPORTUNITYID; 
        s1.Product2__c=LI.Product2Id;
        s1.ProductCode__c = LI.PRODUCTCODE;
        s1.GL_Product_Name__c = LI.Product2.GL_Product_Name__c;
        s1.Amount__c = LI.TotalPrice * (100 - Connector_Pnct)/100;
        s1.Connector_Percent__c = Connector_Pnct;
        s1.CurrencyIsoCode = LI.CurrencyIsoCode;
        s1.TotalPrice__c = LI.TotalPrice;
        s1.AUD_Amount__c = s1.Amount__c / Conversion_Rate;
 
        ItemSplits.add(s1); 
        
          // 3. Create a ItemSplit record for connector product  
         If (Connector_Pnct <>0) {  
           OpportunityItemSplit__c s2 = new OpportunityItemSplit__c ();
       	   s2.Indicator__c = 'Connector Product Price';
           s2.Name = LI.Product2.NAME ;  
           s2.Opportunity__c = LI.OPPORTUNITYID; 
           s2.Product2__c=LI.Product2Id;
           s2.ProductCode__c = LI.PRODUCTCODE;
           s2.GL_Product_Name__c = LI.Product2.Connector_GL_Product_Name__c;
           s2.Amount__c = LI.TotalPrice * Connector_Pnct/100;
		   s2.Connector_Percent__c = Connector_Pnct;
           s2.CurrencyIsoCode = LI.CurrencyIsoCode;
           s2.TotalPrice__c = LI.TotalPrice;
           s2.AUD_Amount__c = s2.Amount__c / Conversion_Rate;  
             
          ItemSplits.add(s2);        
        
        }   
      }

     }
        
       If (ItemSplits.size()>0) {  
         try { insert ItemSplits;  
          } catch (DmlException e) 
          { System.debug(e.getMessage()); 
          }   
       }       
        
    }
 
 //Insert OpportunityModuleItem data into OpportunityItemSplit Object
 // for Opportunity pricebookoverwritten = true 
    public void insertModuleItemSplit(Map<Id, Opportunity> oppMap){
      Set<Id> oppIds = oppMap.keySet();  
      List<Opportunity> oppValues = oppMap.values();
        
     //0. Get data from OpportunityModuleItem for Opportunity pricebookoverwritten = true  
     List <OpportunityModuleItem__c> OppLineItems = new List<OpportunityModuleItem__c> ();
     OpportunityItemSplit__c[] ItemSplits = new OpportunityItemSplit__c[]{};


    Map<Id,  List <OpportunityModuleItem__c>> OppLineItemsPerOpp = new Map<Id,  List <OpportunityModuleItem__c>>();
    for(OpportunityModuleItem__c oli:[SELECT OPPORTUNITY__r.id, Product2__r.GL_PRODUCT_NAME__C, Opportunity__c, Product2__c, ProductCode__c,NAME, TotalPrice__c, Product2__r.CONNECTOR_PERCENT__C,Product2__r.Connector_GL_Product_Name__c, CURRENCYISOCODE
                                        FROM OpportunityModuleItem__c WHERE OPPORTUNITY__c in: oppIds and TotalPrice__c<>0])    {
        List <OpportunityModuleItem__c> tempOppLineItems = new List<OpportunityModuleItem__c> ();
        if(OppLineItemsPerOpp.containsKey(oli.OPPORTUNITY__r.id)){
            tempOppLineItems = OppLineItemsPerOpp.get(oli.OPPORTUNITY__r.id);
        }
        tempOppLineItems.add(oli);
        OppLineItemsPerOpp.put(oli.OPPORTUNITY__r.id, tempOppLineItems);

    }

    For (Opportunity Lo: oppValues)  {    
        
    /*
    aug 3, 2018 move to a map outside loop
    OppLineItems = [SELECT Product2__r.GL_PRODUCT_NAME__C, Opportunity__c, Product2__c, ProductCode__c,
                     NAME, TotalPrice__c, Product2__r.CONNECTOR_PERCENT__C, 
                    Product2__r.Connector_GL_Product_Name__c, CURRENCYISOCODE 
       FROM OpportunityModuleItem__c WHERE OPPORTUNITY__c =: Lo.Id and TotalPrice__c<>0];
  */
        if(OppLineItemsPerOpp.containsKey(Lo.Id)){
            OppLineItems = OppLineItemsPerOpp.get(Lo.Id);
        }


        //1. Get Dated Conversion Rate 
       Decimal Conversion_Rate = 1;
       If (Lo.CurrencyIsoCode <> 'AUD') {
           Date rateDate =  Date.newInstance(Lo.CloseDate.year(),Lo.CloseDate.month(),1);
           //call class cDatedConversionRate
           Conversion_Rate = cDatedConversionRate.getDatedConversionRate(Lo.CurrencyIsoCode, rateDate);  
    	} 
        
    For (OpportunityModuleItem__c LI: OppLineItems)   { 
        Decimal Connector_Pnct = LI.Product2__r.CONNECTOR_PERCENT__C;
        If (Connector_Pnct == Null) {
            Connector_Pnct = 0 ;
        }
               
       //2. Create a ItemSplit record for original product 
       OpportunityItemSplit__c s1 = new OpportunityItemSplit__c ();
        s1.Indicator__c = 'Product Price';
        s1.Name = LI.NAME ;  
        s1.Opportunity__c = LI.Opportunity__c; 
        s1.Product2__c = LI.Product2__c;
        s1.ProductCode__c = LI.ProductCode__c;
        s1.GL_Product_Name__c = LI.Product2__r.GL_PRODUCT_NAME__C;
        s1.Amount__c = LI.TotalPrice__c * (100-Connector_Pnct)/100;
		s1.Connector_Percent__c = LI.Product2__r.CONNECTOR_PERCENT__C;
        s1.CurrencyIsoCode = LI.CurrencyIsoCode;
        s1.TotalPrice__c = LI.TotalPrice__c;
        s1.AUD_Amount__c = s1.Amount__c / Conversion_Rate;
        
        ItemSplits.add(s1); 
        
          // 3. Create a ItemSplit record for connector product 
         If (Connector_Pnct <>0) {  
           OpportunityItemSplit__c s2 = new OpportunityItemSplit__c ();
       	   s2.Indicator__c = 'Connector Product Price';
           s2.Name = LI.NAME ;  
           s2.Opportunity__c = LI.Opportunity__c; 
           s2.Product2__c=LI.Product2__c;
           s2.ProductCode__c = LI.ProductCode__c;
           s2.GL_Product_Name__c = LI.Product2__r.Connector_GL_Product_Name__c;
           s2.Amount__c = LI.TotalPrice__c * Connector_Pnct/100;
		   s2.Connector_Percent__c = LI.Product2__r.CONNECTOR_PERCENT__C;
           s2.CurrencyIsoCode = LI.CurrencyIsoCode;
           s2.TotalPrice__c = LI.TotalPrice__c;
           s2.AUD_Amount__c = s2.Amount__c / Conversion_Rate;  
             
           ItemSplits.add(s2);        
        }   
      }  
    }      
       If (ItemSplits.size()>0) {  
         try { insert ItemSplits;  
          } catch (DmlException e) 
          { System.debug(e.getMessage()); 
          }   
       }       

}
  
 //Insert OpportunityGroupProduct data Object
    public void insertGroupedProduct(Map<Id, Opportunity> oppMap){
      Set<Id> oppIds;  
      List<Opportunity> oppValues;
      oppIds = oppMap.keySet();
      oppValues = oppMap.values();
	  String targetCurrency = 'AUD';
        
      // 1. Create an object
      OpportunityGroupedProduct__c[] GroupedProduct = new OpportunityGroupedProduct__c[]{};   
      
      // 2. Group data from OpportunityItemSplit
      AggregateResult[] groupedResults = [SELECT Opportunity__c, GL_Product_Name__c,
                                         CurrencyIsoCode, SUM(AUD_Amount__c) AUD_Amount, SUM(Amount__c) Amount
      FROM  OpportunityItemSplit__c Where Opportunity__c =: oppIds 
      GROUP BY Opportunity__c, GL_Product_Name__c, CurrencyIsoCode ] ;
      
        //3. add group data to grouped product
        For (AggregateResult ar : groupedResults) {
            OpportunityGroupedProduct__c gp = new OpportunityGroupedProduct__c();
            gp.Name = (String)(ar.get('GL_Product_Name__c'));
            gp.GL_Product_Name__c = (String)(ar.get('GL_Product_Name__c'));
            gp.Opportunity__c = (ID)ar.get('Opportunity__c');
            gp.CurrencyIsoCode = (String)ar.get('CurrencyIsoCode');
            gp.Amount__c = (Decimal)ar.get('Amount');
            gp.AUD_Amount__c = (Decimal)ar.get('AUD_Amount');
            
            targetCurrency = (String)ar.get('CurrencyIsoCode');
            
            //Get default currency rate
            if(targetCurrency.contains('AUD') == false){
            Decimal conversionRate = [SELECT conversionrate FROM currencytype 
                                       WHERE isocode = :targetCurrency LIMIT 1].conversionRate;
            gp.Amount__c =  gp.Amount__c *   conversionRate; 
            
            }
            
            
            GroupedProduct.add(gp);
        }
        
        //4. insert grouped product
        If (GroupedProduct.size()>0) {  
         try { insert GroupedProduct;  
          } catch (DmlException e) 
          { System.debug(e.getMessage()); 
          }   
       } 
    }
    
}