unpackaged/main/default/objects/CiAnywhereSetting__c/CiAnywhereSetting__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>common integration settings to be used in CiAnywhere integration</description>
    <label>CiAnywhere Settings</label>
</CustomObject>

unpackaged/main/default/objects/CiAnywhereSetting__c/fields/Host_URL__c.field-meta.xml
<CustomField>
    <fullName>Host_URL__c</fullName>
    <description>CIAnywhere API Endpoint. This URL must be added in Remote Site Setting to authorise calls to network addresses</description>
    <label>Host URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/CiAnywhereSetting__c/fields/Password__c.field-meta.xml
<CustomField>
    <fullName>Password__c</fullName>
    <description>API password  to be passed in authentication header request</description>
    <label>Password</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/CiAnywhereSetting__c/fields/Username__c.field-meta.xml
<CustomField>
    <fullName>Username__c</fullName>
    <description>API username to be passed in authentication header request</description>
    <label>Username</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/CIAnywhereTestClassHelper.cls
/*********************************************************************************************
* @author         Cludo
* @date           22/8/18
* @description:   Helper class for test classes
* @Version:
**********************************************************************************************/

public without sharing class CIAnywhereTestClassHelper {
    /**
    *    Description     : Creates custom setting
    **/
    public static void createCustomSetting(){
        CiAnywhereSetting__c wsSettings = new CiAnywhereSetting__c();
        wsSettings.Username__c = 'testUserName';
        wsSettings.Host_URL__c = 'AU';
        wsSettings.Password__c = 'EN';
        insert wsSettings;
    }

}