unpackaged/main/default/objects/CiAnywhereSetting__c/CiAnywhereSetting__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>common integration settings to be used in CiAnywhere integration</description>
    <label>CiAnywhere Settings</label>
</CustomObject>

unpackaged/main/default/objects/CiAnywhereSetting__c/fields/Host_URL__c.field-meta.xml
<CustomField>
    <fullName>Host_URL__c</fullName>
    <description>CIAnywhere API Endpoint. This URL must be added in Remote Site Setting to authorise calls to network addresses</description>
    <label>Host URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/CiAnywhereSetting__c/fields/Password__c.field-meta.xml
<CustomField>
    <fullName>Password__c</fullName>
    <description>API password  to be passed in authentication header request</description>
    <label>Password</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/CiAnywhereSetting__c/fields/Username__c.field-meta.xml
<CustomField>
    <fullName>Username__c</fullName>
    <description>API username to be passed in authentication header request</description>
    <label>Username</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/CIAnywhereAPI.cls
/**
 * Created by armievergara on 21/8/18.
 */

public with sharing class CIAnywhereAPI {
    public static final String CI_METHOD_URL =  '/Api/WS/v1/ETLProcessCi/CiSubmit';
    public APIGateway apiGateway = new APIGateway();
    public CiAnywhereSetting__c ciAnywhereCustomSettings = CiAnywhereSetting__c.getInstance();

    public CIAnywhereAPI(){
        apiGateway.addBasicAuthentication(ciAnywhereCustomSettings.Username__c, ciAnywhereCustomSettings.Password__c);
    }


    public HttpResponse submit(string processType, string processName, List<CIAnywhere_SubmitDTO.PresetVariableValuesWrapper> variableValues) {
        CIAnywhere_SubmitDTO.Request submitRequest = new CIAnywhere_SubmitDTO.Request();
        submitRequest.ProcessType = processType;
        submitRequest.ProcessName = processName;
        submitRequest.PresetVariableValues = variableValues;
        string requestInJSON = (String) JSON.serializePretty(submitRequest, true);
        System.debug(requestInJSON);
        String uri = ciAnywhereCustomSettings.Host_URL__c + CI_METHOD_URL;
        String encodedURL = EncodingUtil.urlEncode(uri, 'UTF-8');
        return apiGateway.execute(uri, 'POST', requestInJSON);
    }
}