unpackaged/main/default/objects/ContractLineItem/fields/Scheduled_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Scheduled_End_Date__c</fullName>
    <label>Scheduled End Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Auto_Order__c.field-meta.xml
<CustomField>
    <fullName>Auto_Order__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Auto Order</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Auto_Renew__c.field-meta.xml
<CustomField>
    <fullName>Auto_Renew__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Auto Renew</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Auto_Renewal_Date__c.field-meta.xml
<CustomField>
    <fullName>Auto_Renewal_Date__c</fullName>
    <label>Auto-Renewal Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Auto_Renewal_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Auto_Renewal_End_Date__c</fullName>
    <label>Auto-Renewal End Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Auto_Renewal_Treatment__c.field-meta.xml
<CustomField>
    <fullName>Auto_Renewal_Treatment__c</fullName>
    <label>Auto-Renewal Treatment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Auto_Renewal_Treatment</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Deal_Type__c.field-meta.xml
<CustomField>
    <fullName>Deal_Type__c</fullName>
    <label>Deal Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Deal_Type</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Renewal_Pricing_Method__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Pricing_Method__c</fullName>
    <defaultValue>&quot;Uplift&quot;</defaultValue>
    <description>This value will come in from the Service Contract and is made read only for anyone but system admin, default set to list.</description>
    <label>Renewal Pricing Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Renewal_Pricing_Method</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Stop_Auto_Renewal__c.field-meta.xml
<CustomField>
    <fullName>Stop_Auto_Renewal__c</fullName>
    <label>Stop Auto-Order</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/recordTypes/Cloud.recordType-meta.xml
<RecordType>
    <fullName>Cloud</fullName>
    <active>false</active>
    <businessProcess>Cloud</businessProcess>
    <label>Cloud</label>
</RecordType>

unpackaged/main/default/objects/Order/fields/Deal_Type__c.field-meta.xml
<CustomField>
    <fullName>Deal_Type__c</fullName>
    <label>Deal Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ServiceContract/fields/Auto_Order__c.field-meta.xml
<CustomField>
    <fullName>Auto_Order__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Auto Order</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/ServiceContract/fields/Auto_Renew__c.field-meta.xml
<CustomField>
    <fullName>Auto_Renew__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Auto Renew</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/ServiceContract/fields/Auto_Renewal_Date__c.field-meta.xml
<CustomField>
    <fullName>Auto_Renewal_Date__c</fullName>
    <label>Auto-Renewal Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/ServiceContract/fields/Auto_Renewal_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Auto_Renewal_End_Date__c</fullName>
    <label>Auto-Renewal End Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/ServiceContract/fields/Auto_Renewal_Treatment__c.field-meta.xml
<CustomField>
    <fullName>Auto_Renewal_Treatment__c</fullName>
    <label>Auto-Renewal Treatment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Auto_Renewal_Treatment</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ServiceContract/fields/Deal_Type__c.field-meta.xml
<CustomField>
    <fullName>Deal_Type__c</fullName>
    <label>Deal Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Deal_Type</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ServiceContract/fields/Renewal_Pricing_Method__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Pricing_Method__c</fullName>
    <description>Custom Renewal Pricing field because OOTB functionality does not meet business requirement to represent detailed pricing.</description>
    <inlineHelpText>Defines renewal pricing.</inlineHelpText>
    <label>Renewal Pricing Method</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Renewal_Pricing_Method</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ServiceContract/fields/Stop_Auto_Renewal__c.field-meta.xml
<CustomField>
    <fullName>Stop_Auto_Renewal__c</fullName>
    <label>Stop Auto-Order</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/globalValueSets/Auto_Renewal_Treatment.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Auto-Renew continuously – 12 months</fullName>
        <default>true</default>
        <label>Auto-Renew continuously – 12 months</label>
    </customValue>
    <customValue>
        <fullName>Auto-Create Opportunity and Quote</fullName>
    </customValue>
    <customValue>
        <fullName>Do Not Auto-Renew</fullName>
    </customValue>
    <masterLabel>Auto-Renewal Treatment</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Deal_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Perpetual</fullName>
    </customValue>
    <customValue>
        <fullName>Saas</fullName>
    </customValue>
    <customValue>
        <fullName>Term</fullName>
    </customValue>
    <customValue>
        <fullName>Subscription</fullName>
    </customValue>
    <customValue>
        <fullName>Perpetual on Cloud</fullName>
    </customValue>
    <customValue>
        <fullName>AMS</fullName>
    </customValue>
    <masterLabel>Deal Type</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Renewal_Pricing_Method.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>List</fullName>
    </customValue>
    <customValue>
        <fullName>Uplift</fullName>
        <default>true</default>
        <label>Uplift</label>
    </customValue>
    <description>Custom Renewal Pricing field because OOTB functionality does not meet business requirement to represent detailed pricing.</description>
    <masterLabel>Renewal Pricing Method</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/RenewalServiceContractsBatch.cls
/*******************************************************************************************************
* @Class Name   : RenewalServiceContractsBatch
* @description  : Batch class to Renew Service Contract
* @author       : Carlos Roy Billones
* @date         : 16/12/2020
* @mod-log 
* -----------------------------------------------------------------------------------------------------
* Developer             Date            Mod ID      Description
* -----------------------------------------------------------------------------------------------------
* Carlos Roy Billones   16/12/2020      1000        Initial version
* Yi Zhang              12/03/2021      2000        Applied comments
* Yi Zhang              16/03/2021      3000        Applied fix around auto order
******************************************************************************************************/
public class RenewalServiceContractsBatch implements
Database.Batchable<sObject>, Database.Stateful {
    // instance member to retain state across transactions
    public Integer recordsProcessed = 0;
    Set<id> oppIdset = new Set<Id>();

    private String contractId;
    
    public RenewalServiceContractsBatch() {}

    public RenewalServiceContractsBatch(String contractId) {
        this.contractId = contractId;
    }
    /***
    * @name	        : start
    * @description  : Standard start method for batch class 
    * @author		: Carlos Roy Billones
    * @param 		: Database.BatchableContext bc - required parameter for standard batch methods
    */    
    public Database.QueryLocator start(Database.BatchableContext bc){
        return Database.getQueryLocator(
            'SELECT ID, SBQQSC__RenewalOpportunity__c, Auto_Renewal_Date__c, Auto_Renewal_End_Date__c, Auto_Order__c, Stop_Auto_Renewal__c, SBQQSC__RenewalForecast__c, AccountId, SBQQSC__Opportunity__c ' +
            'FROM ServiceContract ' +
            'WHERE Deal_Type__c NOT IN (\'Term\', \'Perpetual on Cloud\') AND SBQQSC__RenewalOpportunity__c = NULL AND Auto_Renewal_Date__c <= TODAY AND '+ 
            'Auto_Renewal_Treatment__c IN (\'Auto-Renew continuously – 12 months\', \'Auto-Create Opportunity and Quote\') AND '+
            '(Auto_Renewal_End_Date__c >= TODAY OR Auto_Renewal_End_Date__c = NULL) '
            + ((contractId == null) ? '' : ' AND Id = \''+ contractId + '\'')
        );
    }

    /***
    * @name	        : execute
    * @description  : Required function for batchable context
    * @author		: Carlos Roy Billones
    * @param 		: Database.BatchableContext bc - required parameter for standard batch methods
    * @param 		: List<ServiceContract> scope - Batch scope
    */    
    public void execute(Database.BatchableContext bc, List<ServiceContract> scope){
        // process each batch of records
        System.debug('Scope: ' + scope);
        List<ServiceContract> serviceContracts = new List<ServiceContract>();
        Map<Id,List<ServiceContract>> serviceContractMap = new Map<Id,List<ServiceContract>>();
        
        // group service contracts by account
        for(ServiceContract serviceContract : scope) {
            if(serviceContractMap.get(serviceContract.AccountId) == null)
            {
                serviceContractMap.put(serviceContract.AccountId, new List<ServiceContract>{serviceContract});
            }
            else{
                serviceContractMap.get(serviceContract.AccountId).add(serviceContract);
            }
        }
        
        // update in-scope service contracts
        List<ServiceContract> sctoupdate = new List<ServiceContract>();
        
        for(ServiceContract sc : scope){
             	sc.Renewal_Pricing_Method__c = 'Uplift';
            	sctoupdate.add(sc);
        }
       
        if(sctoupdate.size() > 0){
            try{
                update sctoupdate;
            }catch(exception e){
                INSERT DM_ApplicationLog.createApplicationLog(e); 
                System.debug(e.getMessage());
            }
        }
        
        for(Id acctId : serviceContractMap.keySet()){
            if(serviceContractMap.get(acctId) != null){
                for(ServiceContract servcon :serviceContractMap.get(acctId)){
                    
                    ServiceContract serviceContract = new ServiceContract();
                    
                    if(serviceContract.Auto_Renewal_Treatment__c == 'Auto-Renew continuously – 12 months' && String.isBlank(serviceContract.Stop_Auto_Renewal__c)){
                        serviceContract.Auto_Order__c = true;
                    }
                    serviceContract.Id = servcon.Id;
                    serviceContract.Auto_Renew__c = true;
                    //serviceContract.SBQQSC__RenewalUpliftRate__c = 0;
                    serviceContract.SBQQSC__RenewalForecast__c = true;
                    serviceContract.SBQQSC__RenewalQuoted__c = true;
                    serviceContracts.add(serviceContract);
                    recordsProcessed = recordsProcessed + 1;
                    oppIdset.add(serviceContract.SBQQSC__Opportunity__c);
                }
            }
        }
        
        if(serviceContracts.size() > 0){
            try{
                update serviceContracts;
            }catch(exception e){
                INSERT DM_ApplicationLog.createApplicationLog(e); 
                System.debug(e.getMessage());
            }
        }
        
        // update quote lines
        List<ContractLineItem> contractlineitem = [SELECT ID, SBQQSC__QuoteLine__c, Scheduled_End_Date__c FROM ContractLineItem WHERE ServiceContractId IN :serviceContracts];
        System.debug('contractlineitem: ' + contractlineitem);
        List<SBQQ__QuoteLine__c> quotelineitems = [SELECT ID,SBQQSC__RenewedContractLine__c FROM SBQQ__QuoteLine__c WHERE SBQQSC__RenewedContractLine__c IN :contractlineitem];
        Map<Id, ContractLineItem> contractlineitemMap = new Map<Id,ContractLineItem>(contractlineitem);
        
        for(SBQQ__QuoteLine__c quotelineitem: quotelineitems)
        {
            if(contractlineitemMap.get(quotelineitem.SBQQSC__RenewedContractLine__c).Scheduled_End_Date__c != null){
                quotelineitem.SBQQ__EndDate__c = contractlineitemMap.get(quotelineitem.SBQQSC__RenewedContractLine__c).Scheduled_End_Date__c;
                System.debug('Quote Line Item SBQQ__EndDate__c: ' + quotelineitem.SBQQ__EndDate__c);
            }
        }
        
        if(quotelineitems.size() > 0){
            update quotelineitems;
        }
    }
    


    /***
    * @name	        : finish
    * @description  : Required function for batchable context
    * @author		: Carlos Roy Billones
    * @param 		: Database.BatchableContext bc - required parameter for standard batch methods
    */
    public void finish(Database.BatchableContext bc){
        System.debug(recordsProcessed + ' records processed. Shazam!');
        AsyncApexJob job = [SELECT Id, Status, NumberOfErrors,
            JobItemsProcessed,
            TotalJobItems, CreatedBy.Email
            FROM AsyncApexJob
            WHERE Id = :bc.getJobId()];
        System.debug('Apex Async Job ' + job);
        
        //Database.executeBatch(new OrderAndContractOpportunityBatch(oppIdset));
    }    
}